export const ca = {
  'app.titulo': 'FocusFlow',
  'app.eslogan': 'Organitza els teus objectius, enfoca el teu temps.',
  'bienvenida.mensaje': 'Benvingut a FocusFlow!',
  'selector.idioma.etiqueta': 'Idioma',
  'auth.registro.titulo': 'Crear compte',
  'auth.registro.nombre': 'Nom',
  'auth.registro.correo': 'Correu electrònic',
  'auth.registro.contrasena': 'Contrasenya',
  'auth.registro.boton': 'Registrar-me',
  'auth.registro.enlaceLogin': 'Ja tens compte? Inicia sessió',
  'auth.login.titulo': 'Iniciar sessió',
  'auth.login.correo': 'Correu electrònic',
  'auth.login.contrasena': 'Contrasenya',
  'auth.login.boton': 'Entrar',
  'auth.login.enlaceRegistro': 'No tens compte? Registra\'t',
  'auth.cerrarSesion': 'Tancar sessió',
  'auth.bienvenidoUsuario': 'Hola, {nombre}',
  'inicio.irAObjetivos': 'Veure els meus objectius',
  'objetivos.titulo': 'Els meus objectius',
  'objetivos.nuevo.tituloPlaceholder': 'Títol de l\'objectiu',
  'objetivos.nuevo.descripcionPlaceholder': 'Descripció (opcional)',
  'objetivos.nuevo.boton': 'Crear objectiu',
  'objetivos.vacio': 'Encara no tens objectius. Crea el primer!',
  'objetivos.eliminar': 'Eliminar objectiu',
  'objetivos.progreso': '{completadas} de {total} tasques',
  'fechaLimite.etiqueta': 'Data límit (opcional)',
  'inicio.proximos.titulo': 'Pròxims 7 dies',
  'inicio.proximos.vacio': 'No tens tasques amb data límit en els pròxims 7 dies.',
  'tareas.tituloPlaceholder': 'Nova tasca',
  'tareas.anadir': 'Afegir',
  'tareas.sueltas.titulo': 'Tasques soltes',
  'tareas.eliminar': 'Eliminar tasca',
  'tareas.marcarCompletada': 'Marcar "{titulo}" com a completada',
  'tarea.detalle.descripcion': 'Notes',
  'tarea.detalle.recurrencia': 'Repetir',
  'tarea.recurrencia.ninguna': 'No es repeteix',
  'tarea.recurrencia.diaria': 'Cada dia',
  'tarea.recurrencia.semanal': 'Cada setmana',
  'tarea.detalle.etiquetas': 'Etiquetes',
  'tarea.detalle.nuevaEtiqueta': 'Nova etiqueta',
  'tarea.detalle.quitarEtiqueta': 'Treure l\'etiqueta {nombre}',
  'tarea.detalle.subtareas': 'Subtasques ({completadas} de {total})',
  'tarea.detalle.nuevaSubtarea': 'Nou pas',
  'tarea.detalle.tiempoEstimado': 'Temps estimat (minuts)',
  'tarea.detalle.tiempoEstimadoPlaceholder': 'p. ex. 30',
  'tarea.detalle.tiempoReal': 'Temps real: {minutos} min',
  'inicio.irAPomodoro': 'Temporitzador Pomodoro',
  'pomodoro.fase.trabajo': 'Treball',
  'pomodoro.fase.descansoCorto': 'Descans curt',
  'pomodoro.fase.descansoLargo': 'Descans llarg',
  'pomodoro.ciclo': 'Cicle {actual} de {total}',
  'pomodoro.iniciar': 'Iniciar',
  'pomodoro.pausar': 'Pausar',
  'pomodoro.reiniciar': 'Reiniciar',
  'pomodoro.tareaAsociada.etiqueta': 'Tasca associada (opcional)',
  'pomodoro.tareaAsociada.ninguna': 'Cap',
  'pomodoro.historial.titulo': 'Historial recent',
  'pomodoro.historial.vacio': 'Encara no has completat cap sessió.',
  'pomodoro.historial.minutos': '{minutos} min',
  'inicio.irAKanban': 'Tauler Kanban',
  'kanban.titulo': 'Tauler Kanban',
  'kanban.columna.porHacer': 'Per fer',
  'kanban.columna.enProceso': 'En procés',
  'kanban.columna.hecha': 'Feta',
  'kanban.mover.anterior': 'Moure a la columna anterior',
  'kanban.mover.siguiente': 'Moure a la columna següent',
  'inicio.irAEisenhower': 'Matriu d\'Eisenhower',
  'eisenhower.titulo': 'Matriu d\'Eisenhower',
  'eisenhower.cuadrante.hacer': 'Fer ja',
  'eisenhower.cuadrante.planificar': 'Planificar',
  'eisenhower.cuadrante.delegar': 'Delegar',
  'eisenhower.cuadrante.eliminar': 'Eliminar',
  'eisenhower.marcar.urgente': 'Urgent',
  'eisenhower.marcar.importante': 'Important',
  'eisenhower.autoUrgente': 'Urgent per data',
  'captura.placeholder': 'Què tens en ment?',
  'captura.boton': 'Capturar',
  'inicio.irAEstadisticas': 'Estadístiques',
  'estadisticas.titulo': 'Estadístiques',
  'estadisticas.progresoGlobal': 'Progrés global',
  'estadisticas.distribucion.titulo': 'Distribució de tasques',
  'estadisticas.objetivos.titulo': 'Progrés per objectiu',
  'estadisticas.pareto.titulo': 'Tasques d\'alt impacte (Pareto 80/20)',
  'estadisticas.pareto.leyendaAltoImpacto': 'Alt impacte',
  'estadisticas.pareto.descripcion':
    '{marcadas} de {total} tasques estan marcades com d\'alt impacte ({porcentaje}%).',
  'estadisticas.pareto.vacio':
    'Encara no has marcat cap tasca com d\'alt impacte. Marca-les amb ★ des del tauler Kanban.',
  'pareto.marcar': 'Marcar com d\'alt impacte',
  'estadisticas.pomodoro.titulo': 'Pomodoro',
  'estadisticas.pomodoro.hoy': 'Completats avui',
  'estadisticas.pomodoro.semana': 'Completats aquesta setmana',
  'estadisticas.pomodoro.minutosSemana': 'Minuts de treball aquesta setmana',
  'estadisticas.pomodoro.vacio': 'Encara no has completat cap sessió de treball.',
  'estadisticas.racha': '{racha, plural, one {Ratxa: # dia seguit} other {Ratxa: # dies seguits}}',
  'estadisticas.racha.vacia': 'Encara no tens una ratxa activa. Comença avui!',
  'tema.activarOscuro': 'Activar mode fosc',
  'tema.activarClaro': 'Activar mode clar',
  'inicio.irARevision': 'Revisió setmanal',
  'revision.titulo': 'Revisió setmanal',
  'revision.eslogan': 'Una ullada setmanal al que has avançat i al que s\'ha quedat enrere.',
  'revision.vencidas.titulo': 'Tasques vençudes',
  'revision.vencidas.vacio': 'No tens tasques vençudes. Molt bé!',
  'revision.completadas.titulo': 'Completades aquesta setmana',
  'revision.completadas.vacio': 'No has completat cap tasca aquesta setmana.',
  'revision.objetivosSinTocar.titulo': 'Objectius sense tocar',
  'revision.objetivosSinTocar.vacio': 'Tots els teus objectius tenen moviment recent.',
  'revision.objetivosSinTocar.diasInactivo':
    '{dias, plural, one {Sense canvis des de fa # dia} other {Sense canvis des de fa # dies}}',
  'revision.sueltas.titulo': 'Tasques soltes per organitzar',
  'revision.sueltas.vacio': 'Tot organitzat! No tens tasques soltes pendents.',
  'revision.sueltas.organizar': 'Organitzar a Objectius',
  'estadisticas.actividad.titulo': 'Activitat diària',
  'estadisticas.actividad.tooltip': '{cantidad, plural, =0 {Sense pomodors} one {# pomodor} other {# pomodors}}',
  'estadisticas.actividad.menos': 'Menys',
  'estadisticas.actividad.mas': 'Més',
  'estadisticas.tiempoComparado.titulo': 'Temps estimat vs. real',
  'estadisticas.tiempoComparado.vacio':
    'Posa un temps estimat en una tasca (des del seu detall) i registra-hi sessions de Pomodor per veure-la comparada aquí.',
  'estadisticas.tiempoComparado.estimado': 'Estimat: {minutos} min',
  'estadisticas.tiempoComparado.real': 'Real: {minutos} min',
  'estadisticas.exportar.csv': 'Exportar CSV',
  'estadisticas.exportar.pdf': 'Imprimir / PDF',
  'inicio.irAAjustes': 'Configuració',
  'ajustes.titulo': 'Configuració',
  'ajustes.google.titulo': 'Google Calendar',
  'ajustes.google.descripcion':
    'Sincronitza les teves tasques amb data límit i les teves sessions de Pomodoro completades amb el teu Google Calendar, en tots dos sentits.',
  'ajustes.google.conectar': 'Connectar amb Google',
  'ajustes.google.desconectar': 'Desconnectar',
  'ajustes.google.conectado': 'Compte connectat',
  'ajustes.google.noConectado': 'No connectat',
  'ajustes.google.ultimaSincronizacion': 'Última sincronització: {fecha}',
  'ajustes.google.nunca': 'mai',
  'ajustes.google.sincronizarAhora': 'Sincronitzar ara',
  'ajustes.google.sincronizando': 'Sincronitzant…',
  'ajustes.google.autoSyncInfo':
    'Mentre aquesta pestanya estigui oberta i connectada, la sincronització també es repetirà automàticament cada pocs minuts.',
  'ajustes.google.resumen':
    '{creados} creats, {actualizados} actualitzats, {eliminados} eliminats, {importados} importats des de Google.',
  'ajustes.google.conectadoOk': 'Compte de Google connectat correctament.',
  'ajustes.google.errorConexion': 'No s\'ha pogut completar la connexió amb Google.',
  'ajustes.google.noConfigurado':
    'La sincronització amb Google Calendar encara no està configurada al servidor.',
};
