export const ca = {
  'app.titulo': 'FocusFlow',
  'app.eslogan': 'Organitza els teus objectius, enfoca el teu temps.',
  'bienvenida.mensaje': 'Benvingut a FocusFlow!',
  'selector.idioma.etiqueta': 'Idioma',
  'auth.registro.titulo': 'Crear compte',
  'auth.registro.nombre': 'Nom',
  'auth.registro.correo': 'Correu electrònic',
  'auth.registro.contrasena': 'Contrasenya',
  'auth.registro.fechaNacimiento': 'Data de naixement',
  'auth.registro.correoTutor': 'Correu del pare, la mare o el tutor legal',
  'auth.registro.correoTutorAyuda':
    'En ser menor d\'edat, necessitem que el teu tutor confirmi l\'ús d\'aquest compte.',
  'auth.registro.boton': 'Registrar-me',
  'auth.registro.enlaceLogin': 'Ja tens compte? Inicia sessió',
  'auth.login.titulo': 'Iniciar sessió',
  'auth.login.correo': 'Correu electrònic',
  'auth.login.contrasena': 'Contrasenya',
  'auth.login.boton': 'Entrar',
  'auth.login.enlaceRegistro': 'No tens compte? Registra\'t',
  'auth.cerrarSesion': 'Tancar sessió',
  'auth.bienvenidoUsuario': 'Hola, {nombre}',
  'objetivos.titulo': 'Els meus objectius',
  'objetivos.nuevo.tituloPlaceholder': 'Títol de l\'objectiu',
  'objetivos.nuevo.descripcionPlaceholder': 'Descripció (opcional)',
  'objetivos.nuevo.boton': 'Crear objectiu',
  'objetivos.vacio': 'Encara no tens objectius. Crea el primer!',
  'objetivos.eliminar': 'Eliminar objectiu',
  'objetivos.progreso': '{completadas} de {total} tasques',
  'fechaLimite.etiqueta': 'Data límit (opcional)',
  'inicio.proximos.titulo': 'Pròxims 7 dies',
  'inicio.proximos.vacio': 'No tens tasques amb data límit en els pròxims 7 dies.',
  'tareas.tituloPlaceholder': 'Nova tasca',
  'tareas.anadir': 'Afegir',
  'tareas.sueltas.titulo': 'Tasques soltes',
  'tareas.eliminar': 'Eliminar tasca',
  'tareas.marcarCompletada': 'Marcar "{titulo}" com a completada',
  'tarea.detalle.descripcion': 'Notes',
  'tarea.detalle.recurrencia': 'Repetir',
  'tarea.recurrencia.ninguna': 'No es repeteix',
  'tarea.recurrencia.diaria': 'Cada dia',
  'tarea.recurrencia.semanal': 'Cada setmana',
  'tarea.detalle.ambito': 'Àmbit',
  'ambito.selector': 'Àmbit',
  'ambito.todos': 'Tot',
  'ambito.personal': 'Personal',
  'ambito.escolar': 'Escolar',
  'tarea.detalle.etiquetas': 'Etiquetes',
  'tarea.detalle.nuevaEtiqueta': 'Nova etiqueta',
  'tarea.detalle.quitarEtiqueta': 'Treure l\'etiqueta {nombre}',
  'tarea.detalle.subtareas': 'Subtasques ({completadas} de {total})',
  'tarea.detalle.nuevaSubtarea': 'Nou pas',
  'tarea.detalle.tiempoEstimado': 'Temps estimat (minuts)',
  'tarea.detalle.tiempoEstimadoPlaceholder': 'p. ex. 30',
  'tarea.detalle.tiempoReal': 'Temps real: {minutos} min',
  'tarea.detalle.fechaLimite': 'Data límit',
  'tarea.detalle.horaInicio': "Hora d'inici",
  'tarea.detalle.duracion': 'Durada (minuts)',
  'pomodoro.fase.trabajo': 'Treball',
  'pomodoro.fase.descansoCorto': 'Descans curt',
  'pomodoro.fase.descansoLargo': 'Descans llarg',
  'pomodoro.ciclo': 'Cicle {actual} de {total}',
  'pomodoro.iniciar': 'Iniciar',
  'pomodoro.pausar': 'Pausar',
  'pomodoro.reiniciar': 'Reiniciar',
  'pomodoro.tareaAsociada.etiqueta': 'Tasca associada (opcional)',
  'pomodoro.tareaAsociada.ninguna': 'Cap',
  'pomodoro.historial.titulo': 'Historial recent',
  'pomodoro.historial.vacio': 'Encara no has completat cap sessió.',
  'pomodoro.historial.minutos': '{minutos} min',
  'kanban.titulo': 'Tauler Kanban',
  'kanban.columna.porHacer': 'Per fer',
  'kanban.columna.enProceso': 'En procés',
  'kanban.columna.hecha': 'Feta',
  'kanban.mover.anterior': 'Moure a la columna anterior',
  'kanban.mover.siguiente': 'Moure a la columna següent',
  'eisenhower.titulo': 'Matriu d\'Eisenhower',
  'eisenhower.cuadrante.hacer': 'Fer ja',
  'eisenhower.cuadrante.planificar': 'Planificar',
  'eisenhower.cuadrante.delegar': 'Delegar',
  'eisenhower.cuadrante.eliminar': 'Eliminar',
  'eisenhower.marcar.urgente': 'Urgent',
  'eisenhower.marcar.importante': 'Important',
  'eisenhower.autoUrgente': 'Urgent per data',
  'captura.placeholder': 'Què tens en ment?',
  'captura.boton': 'Capturar',
  'estadisticas.titulo': 'Estadístiques',
  'estadisticas.progresoGlobal': 'Progrés global',
  'estadisticas.distribucion.titulo': 'Distribució de tasques',
  'estadisticas.objetivos.titulo': 'Progrés per objectiu',
  'estadisticas.pareto.titulo': 'Tasques d\'alt impacte (Pareto 80/20)',
  'estadisticas.pareto.leyendaAltoImpacto': 'Alt impacte',
  'estadisticas.pareto.descripcion':
    '{marcadas} de {total} tasques estan marcades com d\'alt impacte ({porcentaje}%).',
  'estadisticas.pareto.vacio':
    'Encara no has marcat cap tasca com d\'alt impacte. Marca-les amb ★ des del tauler Kanban.',
  'pareto.marcar': 'Marcar com d\'alt impacte',
  'estadisticas.pomodoro.titulo': 'Pomodoro',
  'estadisticas.pomodoro.hoy': 'Completats avui',
  'estadisticas.pomodoro.semana': 'Completats aquesta setmana',
  'estadisticas.pomodoro.minutosSemana': 'Minuts de treball aquesta setmana',
  'estadisticas.pomodoro.vacio': 'Encara no has completat cap sessió de treball.',
  'estadisticas.racha': '{racha, plural, one {Ratxa: # dia seguit} other {Ratxa: # dies seguits}}',
  'estadisticas.racha.vacia': 'Encara no tens una ratxa activa. Comença avui!',
  'tema.activarOscuro': 'Activar mode fosc',
  'tema.activarClaro': 'Activar mode clar',
  'revision.titulo': 'Revisió setmanal',
  'revision.eslogan': 'Una ullada setmanal al que has avançat i al que s\'ha quedat enrere.',
  'revision.vencidas.titulo': 'Tasques vençudes',
  'revision.vencidas.vacio': 'No tens tasques vençudes. Molt bé!',
  'revision.completadas.titulo': 'Completades aquesta setmana',
  'revision.completadas.vacio': 'No has completat cap tasca aquesta setmana.',
  'revision.objetivosSinTocar.titulo': 'Objectius sense tocar',
  'revision.objetivosSinTocar.vacio': 'Tots els teus objectius tenen moviment recent.',
  'revision.objetivosSinTocar.diasInactivo':
    '{dias, plural, one {Sense canvis des de fa # dia} other {Sense canvis des de fa # dies}}',
  'revision.sueltas.titulo': 'Tasques soltes per organitzar',
  'revision.sueltas.vacio': 'Tot organitzat! No tens tasques soltes pendents.',
  'revision.sueltas.organizar': 'Organitzar a Objectius',
  'estadisticas.actividad.titulo': 'Activitat diària',
  'estadisticas.actividad.tooltip': '{cantidad, plural, =0 {Sense pomodors} one {# pomodor} other {# pomodors}}',
  'estadisticas.actividad.menos': 'Menys',
  'estadisticas.actividad.mas': 'Més',
  'estadisticas.tiempoComparado.titulo': 'Temps estimat vs. real',
  'estadisticas.tiempoComparado.vacio':
    'Posa un temps estimat en una tasca (des del seu detall) i registra-hi sessions de Pomodor per veure-la comparada aquí.',
  'estadisticas.tiempoComparado.estimado': 'Estimat: {minutos} min',
  'estadisticas.tiempoComparado.real': 'Real: {minutos} min',
  'estadisticas.exportar.csv': 'Exportar CSV',
  'estadisticas.exportar.pdf': 'Imprimir / PDF',
  'agenda.titulo': 'Agenda',
  'agenda.filtro.dia': 'Dia',
  'agenda.filtro.semana': 'Setmana',
  'agenda.filtro.mes': 'Mes',
  'agenda.anterior': 'Anterior',
  'agenda.siguiente': 'Següent',
  'agenda.hoy': 'Avui',
  'agenda.sinHora': 'Tot el dia',
  'agenda.sinTareas': 'No hi ha tasques en aquest període.',
  'agenda.masTareas': '+{cantidad} més',
  'ajustes.titulo': 'Configuració',
  'ajustes.google.titulo': 'Google Calendar',
  'ajustes.google.descripcion':
    'Sincronitza les teves tasques amb data límit i les teves sessions de Pomodoro completades amb el teu Google Calendar, en tots dos sentits.',
  'ajustes.google.conectar': 'Connectar amb Google',
  'ajustes.google.desconectar': 'Desconnectar',
  'ajustes.google.conectado': 'Compte connectat',
  'ajustes.google.noConectado': 'No connectat',
  'ajustes.google.ultimaSincronizacion': 'Última sincronització: {fecha}',
  'ajustes.google.nunca': 'mai',
  'ajustes.google.sincronizarAhora': 'Sincronitzar ara',
  'ajustes.google.sincronizando': 'Sincronitzant…',
  'ajustes.google.autoSyncInfo':
    'Mentre aquesta pestanya estigui oberta i connectada, la sincronització també es repetirà automàticament cada pocs minuts.',
  'ajustes.google.resumen':
    '{creados} creats, {actualizados} actualitzats, {eliminados} eliminats, {importados} importats des de Google.',
  'ajustes.google.conectadoOk': 'Compte de Google connectat correctament.',
  'ajustes.google.errorConexion': 'No s\'ha pogut completar la connexió amb Google.',
  'ajustes.google.noConfigurado':
    'La sincronització amb Google Calendar encara no està configurada al servidor.',
  'ajustes.google.errores':
    '{cantidad, plural, one {# esdeveniment no s\'ha pogut sincronitzar amb Google Calendar.} other {# esdeveniments no s\'han pogut sincronitzar amb Google Calendar.}}',
  'nav.principal': 'Navegació principal',
  'nav.abrirMenu': 'Obre el menú',
  'nav.cerrarMenu': 'Tanca el menú',
  'nav.seccion.planificar': 'Planificar',
  'nav.seccion.concentrarse': 'Concentrar-se',
  'nav.seccion.revisar': 'Revisar',
  'nav.inicio': 'Inici',
  'nav.objetivos': 'Objectius',
  'nav.agenda': 'Agenda',
  'nav.kanban': 'Kanban',
  'nav.eisenhower': 'Eisenhower',
  'nav.pomodoro': 'Pomodoro',
  'nav.revision': 'Revisió setmanal',
  'nav.estadisticas': 'Estadístiques',
  'nav.ajustes': 'Configuració',
  'consentimiento.pendiente.titulo': 'El teu compte està pendent de confirmació',
  'consentimiento.pendiente.explicacion': 'Com que ets menor d’edat, hem enviat un correu al teu pare, mare o tutor legal perquè confirmi que pots fer servir FocusFlow. Tan aviat com ho confirmi, podràs començar.',
  'consentimiento.pendiente.comprobar': 'Ja ho ha confirmat',
  'consentimiento.pendiente.reenviar': 'Torna a enviar el correu',
  'consentimiento.pendiente.reenviado': 'Correu reenviat. Demana al teu tutor que revisi la safata d’entrada.',
  'consentimiento.pendiente.errorReenvio': 'No s’ha pogut tornar a enviar el correu',
  'consentimiento.pendiente.viaFamilia': 'El teu pare, mare o tutor té compte a FocusFlow? Genera un codi i dona-li’l en persona: quan l’introdueixi a la seva pàgina Família, el teu compte quedarà confirmat al moment. Només serveix una vegada i caduca en 48 hores.',
  'consentimiento.pendiente.generarCodigo': 'Genera el codi',
  'consentimiento.pendiente.errorCodigo': 'No s’ha pogut generar el codi',
  'consentimiento.confirmar.titulo': 'Confirmació del consentiment',
  'consentimiento.confirmar.confirmando': 'Confirmant…',
  'consentimiento.confirmar.exito': 'Gràcies! El compte ja està confirmat i es pot fer servir FocusFlow amb normalitat.',
  'consentimiento.confirmar.error': 'No s’ha pogut confirmar el compte',
  'consentimiento.confirmar.sinToken': 'L’enllaç no és vàlid: falta el codi de confirmació.',
  'verificacion.aviso.texto': 'Confirma el teu correu: t’hem enviat un enllaç a {correo}.',
  'verificacion.aviso.reenviar': 'Torna a enviar el correu',
  'verificacion.aviso.reenviado': 'Correu reenviat. Si no el veus, mira també al correu brossa.',
  'verificacion.aviso.comprobar': 'Ja l’he confirmat',
  'verificacion.aviso.errorReenvio': 'No s’ha pogut reenviar el correu',
  'verificacion.pagina.titulo': 'Verificació del correu',
  'verificacion.pagina.verificando': 'S’està verificant…',
  'verificacion.pagina.exito': 'Fet! El teu correu ja està verificat.',
  'verificacion.pagina.error': 'No s’ha pogut verificar el correu',
  'verificacion.pagina.sinToken': 'L’enllaç no és vàlid: falta el codi de verificació.',
  'nav.planificador': 'Planificador escolar',
  'tarea.detalle.tipoEscolar': 'Tipus',
  'tipoEscolar.ninguno': 'Sense tipus',
  'tipoEscolar.examen': 'Examen',
  'tipoEscolar.examen.plural': 'Exàmens',
  'tipoEscolar.trabajo': 'Treball',
  'tipoEscolar.trabajo.plural': 'Treballs',
  'tipoEscolar.presentacion': 'Presentació',
  'tipoEscolar.presentacion.plural': 'Presentacions',
  'planificador.titulo': 'Planificador escolar',
  'planificador.descripcion': 'Els teus propers exàmens, treballs i presentacions, ordenats per data.',
  'planificador.nueva.titulo': 'Afegeix un examen o un lliurament',
  'planificador.nueva.tituloPlaceholder': 'p. ex. Examen del tema 3',
  'planificador.nueva.boton': 'Afegeix al planificador',
  'planificador.filtro': 'Filtra per tipus',
  'planificador.filtro.todos': 'Tot',
  'planificador.seccion.vencidas': 'Vençudes ({cantidad})',
  'planificador.seccion.estaSemana': 'Propers 7 dies ({cantidad})',
  'planificador.seccion.masAdelante': 'Més endavant ({cantidad})',
  'planificador.seccion.sinFecha': 'Sense data ({cantidad})',
  'planificador.seccion.vacia': 'Res per aquí.',
  'planificador.vacio': 'No tens exàmens, treballs ni presentacions pendents. Afegeix el primer!',
  'planificador.marcarHecha': 'Marca «{titulo}» com a fet',
  'ajustes.modoEscolar.titulo': 'Mode escolar',
  'ajustes.modoEscolar.descripcion':
    'Afegeix el selector d’àmbit (Personal/Escolar) i el planificador d’exàmens, treballs i presentacions, per separar la vida escolar de la resta. Si el desactives no s’esborra res: simplement tornes a veure totes les tasques juntes.',
  'ajustes.modoEscolar.activar': 'Activa el mode escolar',
  'nav.horario': 'Horari de classe',
  'horario.titulo': 'Horari de classe',
  'horario.cabecera': 'Horari de classe',
  'horario.subtitulo': '{curso} · Curs {periodo} · {comunidad}',
  'horario.curso': '{numero, selectordinal, one {#r} two {#n} few {#t} other {#è}} de {etapa}',
  'horario.etapa.PRIMARIA': 'Primària',
  'horario.etapa.ESO': 'ESO',
  'horario.etapa.BACHILLERATO': 'Batxillerat',
  'horario.columnaHora': 'Hora',
  'horario.descanso': 'Descans',
  'horario.celda': '{dia}, {hora}: {asignatura}',
  'horario.celdaVacia': 'buida',
  'horario.celda.sinAsignaturas': 'Primer afegeix assignatures a l’horari (tauler «Assignatures», a sota).',
  'horario.celda.elegir': 'Assignatura',
  'horario.celda.aula': 'Aula (opcional)',
  'horario.celda.vaciar': 'Buida',
  'horario.guardar': 'Desa',
  'horario.guardado': 'Desat.',
  'horario.editar': 'Edita',
  'horario.terminar': 'Acaba',
  'horario.editarAyuda': 'Prem una casella per posar o canviar l’assignatura.',
  'horario.franjas.titulo': 'Hores i descansos',
  'horario.franjas.ayuda': 'Ajusta les hores al teu centre: pots tenir un o dos esbarjos, o jornada partida amb el dinar i classes a la tarda.',
  'horario.franjas.inicio': 'Inici de la franja {numero}',
  'horario.franjas.fin': 'Final de la franja {numero}',
  'horario.franjas.tipo': 'Tipus de la franja {numero}',
  'horario.franjas.etiqueta': 'Nom del descans {numero}',
  'horario.franjas.clase': 'Classe',
  'horario.franjas.recreo': 'Esbarjo',
  'horario.franjas.subir': 'Puja la franja {numero}',
  'horario.franjas.bajar': 'Baixa la franja {numero}',
  'horario.franjas.quitar': 'Treu la franja {numero}',
  'horario.franjas.error': 'Cada franja ha de començar abans d’acabar.',
  'horario.franjas.anadirClase': '+ Classe',
  'horario.franjas.anadirDescanso': '+ Descans',
  'horario.franjas.guardar': 'Desa les hores',
  'horario.asignaturas.titulo': 'Assignatures',
  'horario.asignaturas.vacio': 'Encara no has afegit assignatures.',
  'horario.asignaturas.color': 'Color de {asignatura}',
  'horario.asignaturas.quitar': 'Treu {asignatura}',
  'horario.asignaturas.catalogo': 'Afegeix del currículum…',
  'horario.asignaturas.anadir': 'Afegeix',
  'horario.asignaturas.optativaPropia': 'Una altra assignatura o optativa (p. ex. Escacs)',
  'horario.asignaturas.errorOptativa': 'No s’ha pogut afegir l’assignatura',
  'horario.categoria.OBLIGATORIA': 'Obligatòries',
  'horario.categoria.AUTONOMICA': 'Llengua de la comunitat',
  'horario.categoria.DE_OPCION': 'D’opció',
  'horario.categoria.OPTATIVA': 'Optatives',
  'horario.categoria.PROPIA': 'Afegides per tu',
  'horario.datos.tituloSeccion': 'Dades de l’horari',
  'horario.datos.titulo': 'Grup',
  'horario.datos.tituloEjemplo': 'p. ex. 3r B',
  'horario.datos.periodo': 'Curs escolar',
  'horario.datos.curso': 'Curs',
  'horario.datos.comunidad': 'Comunitat autònoma',
  'horario.datos.elegir': 'Tria…',
  'horario.datos.activarNuevo': 'Fes servir aquest horari a partir d’ara',
  'horario.datos.plantillaAyuda': 'Començarà amb una jornada de 9.00 a 14.00 i un esbarjo; després pots canviar les hores.',
  'horario.crear': 'Crea l’horari',
  'horario.crearPrimero': 'Crea el teu horari de classe',
  'horario.crearPrimeroAyuda': 'Tria el teu curs i la teva comunitat autònoma per veure les assignatures del currículum, inclosa la llengua pròpia de la teva comunitat.',
  'horario.otros': 'Altres horaris',
  'horario.usarEste': 'Fes servir aquest',
  'horario.nuevo': 'Horari nou',
  'horario.borrar': 'Esborra aquest horari',
  'horario.borrarConfirmar': 'Sí, esborra’l',
  'horario.cancelar': 'Cancel·la',
  'comunidad.ANDALUCIA': 'Andalusia',
  'comunidad.ARAGON': 'Aragó',
  'comunidad.ASTURIAS': 'Astúries',
  'comunidad.BALEARES': 'Illes Balears',
  'comunidad.CANARIAS': 'Canàries',
  'comunidad.CANTABRIA': 'Cantàbria',
  'comunidad.CASTILLA_LA_MANCHA': 'Castella - la Manxa',
  'comunidad.CASTILLA_Y_LEON': 'Castella i Lleó',
  'comunidad.CATALUNA': 'Catalunya',
  'comunidad.COMUNITAT_VALENCIANA': 'Comunitat Valenciana',
  'comunidad.EXTREMADURA': 'Extremadura',
  'comunidad.GALICIA': 'Galícia',
  'comunidad.MADRID': 'Madrid',
  'comunidad.MURCIA': 'Regió de Múrcia',
  'comunidad.NAVARRA': 'Navarra',
  'comunidad.PAIS_VASCO': 'País Basc',
  'comunidad.LA_RIOJA': 'La Rioja',
  'comunidad.CEUTA': 'Ceuta',
  'comunidad.MELILLA': 'Melilla',
  'tarea.detalle.asignatura': 'Assignatura',
  'tarea.detalle.sinAsignatura': 'Sense assignatura',
  'planificador.sinHorario': 'Crea el teu horari de classe per triar l’assignatura',
  'agenda.clase.hasta': 'fins a les {hora}',
  'nav.recordatorios': 'Recordatoris',
  'nav.avisosSinLeer': '{cantidad, plural, one {# avís sense llegir} other {# avisos sense llegir}}',
  'periodo.navidad': 'Vacances de Nadal',
  'periodo.semana-santa': 'Vacances de Setmana Santa',
  'periodo.verano': 'Vacances d’estiu',
  'periodo.hispanidad': 'Festa Nacional d’Espanya',
  'periodo.inmaculada': 'Dia de la Immaculada Concepció',
  'aviso.revision.titulo': 'Revisió setmanal de deures',
  'aviso.revision.cuerpo': 'Tens {pendientes, plural, one {# tasca pendent} other {# tasques pendents}}: {vencidas, plural, one {# vençuda} other {# vençudes}} i {proximos, plural, one {# venç} other {# vencen}} en els propers 7 dies.',
  'aviso.entrega.titulo': 'Lliurament en {horas} h: {titulo}',
  'aviso.entrega.cuerpo': '«{titulo}» venç el {fecha}.',
  'aviso.vacaciones.titulo': '{nombre}: {dias, plural, =0 {comencen avui} one {comencen demà} other {comencen d’aquí a # dies}}',
  'aviso.vacaciones.tituloDia': '{nombre}: {dias, plural, =0 {és avui} one {és demà} other {d’aquí a # dies}}',
  'aviso.vacaciones.cuerpo': 'Del {inicio} al {fin} no hi ha classe.',
  'aviso.vacaciones.cuerpoDia': 'El {inicio} no hi ha classe.',
  'aviso.vacaciones.tareasAntes': '{cantidad, plural, one {Tens # tasca que venç abans.} other {Tens # tasques que vencen abans.}}',
  'aviso.emergencia.titulo': 'Alarma! «{titulo}» fa {dias, plural, one {# dia} other {# dies}} que no es revisa',
  'aviso.emergencia.cuerpo': 'Revisa-la al més aviat possible perquè no se t’escapi.',
  'avisos.notificacion.varios': 'Tens {cantidad} avisos nous a FocusFlow',
  'avisos.emergencia.titulo': 'Mode emergència',
  'avisos.emergencia.descripcion': '{cantidad, plural, one {Hi ha # tasca que fa dies que no es revisa.} other {Hi ha # tasques que fa dies que no es revisen.}}',
  'avisos.emergencia.diasSinTocar': '{dias, plural, one {# dia sense revisar} other {# dies sense revisar}}',
  'avisos.emergencia.revisada': 'Ja l’he revisada',
  'avisos.emergencia.irKanban': 'Anar al Kanban',
  'avisos.emergencia.posponer': 'Recorda-m’ho més tard',
  'recordatorios.titulo': 'Recordatoris i alarmes',
  'recordatorios.comprobarAhora': 'Comprovar ara',
  'recordatorios.comprobando': 'Comprovant…',
  'recordatorios.resultadoComprobacion': '{cantidad, plural, =0 {No hi ha avisos nous.} one {# avís nou.} other {# avisos nous.}}',
  'recordatorios.avisos.titulo': 'Avisos',
  'recordatorios.avisos.leerTodos': 'Marca-los tots com a llegits',
  'recordatorios.avisos.vacio': 'Encara no tens avisos. Crea una alarma aquí sota per començar.',
  'recordatorios.avisos.enviadoCorreo': 'enviat per correu',
  'recordatorios.avisos.marcarLeido': 'Marca com a llegit',
  'recordatorios.navegador.titulo': 'Notificacions en aquest navegador',
  'recordatorios.navegador.descripcion': 'Amb FocusFlow obert (encara que sigui en una altra pestanya), els avisos sonen i apareixen com a notificació del sistema. Amb l’aplicació tancada, només arriben els que tinguin activat el correu.',
  'recordatorios.navegador.permiso.default': 'Les notificacions del navegador estan desactivades: només sonarà l’avís dins de l’aplicació.',
  'recordatorios.navegador.permiso.granted': 'Les notificacions del navegador estan activades.',
  'recordatorios.navegador.permiso.denied': 'Has bloquejat les notificacions de FocusFlow. Pots permetre-les des de la configuració del lloc al navegador.',
  'recordatorios.navegador.permiso.no-disponible': 'Aquest navegador no admet notificacions.',
  'recordatorios.navegador.activar': 'Activa les notificacions',
  'recordatorios.navegador.probarSonido': 'Prova el so',
  'recordatorios.navegador.probarAlarma': 'Prova l’alarma',
  'recordatorios.alarmas.titulo': 'Alarmes',
  'recordatorios.alarmas.vacio': 'Encara no tens cap alarma.',
  'recordatorios.emergencia.titulo': 'Mode emergència',
  'recordatorios.emergencia.descripcion': 'Si una tasca pendent passa {dias, plural, one {# dia} other {# dies}} sense que la toquis, salta una alarma sonora (i un correu, si l’actives) perquè la revisis immediatament.',
  'recordatorios.emergencia.activar': 'Activa el mode emergència',
  'recordatorios.emergencia.dias': 'Dies sense tocar perquè salti:',
  'recordatorios.porCorreo': 'Avisa’m també per correu',
  'recordatorios.correoNoConfigurado': 'L’enviament de correu no està configurat al servidor: de moment l’avís només apareixerà a l’aplicació.',
  'recordatorios.ia.info': 'Els resums setmanals i les alarmes d’emergència es redacten amb IA local (Ollama) quan està disponible; si no respon, es fa servir el text normal.',
  'recordatorios.ia.etiqueta': 'Redactat amb IA',
  'recordatorios.tipo.REVISION_SEMANAL': 'Revisió setmanal de deures',
  'recordatorios.tipo.ENTREGA': 'Lliurament de tasca',
  'recordatorios.tipo.VACACIONES': 'Vacances i festius escolars',
  'recordatorios.tipo.REVISION_SEMANAL.descripcion': 'Cada {dia} a les {hora}',
  'recordatorios.tipo.ENTREGA.descripcion': '{horas, plural, one {# hora} other {# hores}} abans de cada data límit',
  'recordatorios.tipo.ENTREGA.descripcionEscolar': '{horas, plural, one {# hora} other {# hores}} abans de cada data límit (només tasques escolars)',
  'recordatorios.tipo.VACACIONES.descripcion': '{dias, plural, =0 {El mateix dia} one {# dia abans} other {# dies abans}} de cada període sense classe',
  'recordatorios.activo': 'Activa',
  'recordatorios.eliminar': 'Elimina l’alarma',
  'recordatorios.nueva.titulo': 'Nova alarma',
  'recordatorios.nueva.tipo': 'Tipus d’alarma',
  'recordatorios.nueva.dia': 'Dia',
  'recordatorios.nueva.hora': 'Hora',
  'recordatorios.nueva.horasAntes': 'Hores abans del lliurament:',
  'recordatorios.nueva.soloEscolar': 'Només tasques escolars',
  'recordatorios.nueva.diasAntes': 'Dies abans:',
  'recordatorios.nueva.anadir': 'Afegeix l’alarma',
  'recordatorios.calendario.titulo': 'Calendari escolar {curso}',
  'recordatorios.calendario.comunidad': '{comunidad}: les classes van del {inicio} al {fin}.',
  'recordatorios.calendario.sinHorario': 'No tens un horari de classe actiu, així que no se sap la teva comunitat: només es tenen en compte els teus dies no lectius propis.',
  'recordatorios.calendario.rango': 'del {inicio} al {fin}',
  'recordatorios.calendario.propios': 'Els teus dies no lectius',
  'recordatorios.calendario.propiosVacio': 'Festes locals o dies de lliure disposició del teu centre que no surten a dalt.',
  'recordatorios.calendario.eliminarPropio': 'Elimina {nombre}',
  'recordatorios.calendario.nombre': 'Nom',
  'recordatorios.calendario.desde': 'Des de',
  'recordatorios.calendario.hasta': 'Fins a (opcional)',
  'recordatorios.calendario.anadir': 'Afegeix',
  'recordatorios.calendario.fuente': 'Dates oficials de cada departament d’educació. Les festes locals les afegeixes tu.',
  'ambito.eventual': 'Eventual',
  'kanban.columna.bajoControl': 'Sota control',
  'kanban.columna.pospuesta': 'Ajornada',
  'kanban.columna.archivada': 'Arxivada',
  'tarea.detalle.estado': 'Estat',
  'tarea.detalle.revisor': 'Revisió',
  'tarea.detalle.sinRevisor': 'Ningú no la revisa',
  'tarea.detalle.revisorAyuda': 'Quan la marquis com a feta, se li demanarà que la revisi.',
  'revision.estado.PENDIENTE': 'Esperant la revisió.',
  'revision.estado.APROBADA': 'Revisió aprovada.',
  'revision.estado.DEVUELTA': 'Retornada per corregir:',
  'revision.insignia.PENDIENTE': 'Per revisar',
  'revision.insignia.APROBADA': 'Aprovada',
  'revision.insignia.DEVUELTA': 'Retornada',
  'revision.asignadaPor': 'Assignada per {nombre}',
  'aviso.revisionSolicitada.titulo': '{nombre} espera la teva revisió',
  'aviso.revisionSolicitada.cuerpo': '{nombre} ha acabat «{titulo}» i et demana que la revisis.',
  'aviso.revisionAprobada.titulo': '{nombre} ha aprovat «{titulo}»',
  'aviso.revisionAprobada.cuerpo': 'Tot està bé.',
  'aviso.revisionDevuelta.titulo': '{nombre} t’ha retornat «{titulo}»',
  'aviso.revisionDevuelta.cuerpo': 'Revisa-la i torna a marcar-la com a feta.',
  'nav.familia': 'Família',
  'familia.titulo': 'Família',
  'familia.descripcion': 'Vincula el teu compte amb el del teu pare, mare o tutor (o amb el del teu fill o filla) per demanar i fer revisions de tasques. Qui revisa només veu les tasques que li demanes revisar o que t’ha assignat, mai la resta del teu compte.',
  'familia.responsables.titulo': 'Qui revisa les teves tasques',
  'familia.responsables.vacio': 'Encara ningú no revisa les teves tasques.',
  'familia.desvincular': 'Desvincula',
  'familia.codigo.explicacion': 'Perquè algú revisi les teves tasques, genera un codi i dona-li en persona: l’haurà d’introduir al seu compte de FocusFlow. Només serveix una vegada i caduca en 48 hores.',
  'familia.codigo.etiqueta': 'Codi de vincle',
  'familia.codigo.caduca': 'Caduca el {fecha}',
  'familia.codigo.otro': 'Genera un altre codi',
  'familia.codigo.generar': 'Genera un codi',
  'familia.vincular.titulo': 'Revisar les tasques d’una altra persona',
  'familia.vincular.codigo': 'Codi',
  'familia.vincular.boton': 'Vincula',
  'familia.vincular.ayuda': 'Introdueix el codi que t’ha donat el teu fill o filla (el genera en aquesta mateixa pàgina, des del seu compte).',
  'familia.vincular.consentimientoConcedido': 'Has confirmat el compte de {nombre}: ja pot fer servir FocusFlow.',
  'familia.supervisado.titulo': 'Tasques de {nombre}',
  'familia.supervisado.pendientes': '{cantidad, plural, =0 {Per revisar} other {Per revisar (#)}}',
  'familia.supervisado.pendientesVacio': 'No hi ha res pendent de revisar.',
  'familia.supervisado.resto': 'Altres tasques que revises o has assignat',
  'familia.revision.comentario': 'Què cal corregir?',
  'familia.revision.enviarDevolucion': 'Retorna amb aquest comentari',
  'familia.revision.cancelar': 'Cancel·la',
  'familia.revision.aprobar': 'Aprova',
  'familia.revision.devolver': 'Retorna',
  'familia.asignar.titulo': 'Assigna una tasca',
  'familia.asignar.tarea': 'Tasca que vols assignar',
  'familia.asignar.boton': 'Assigna',
  'familia.asignar.ayuda': 'Apareixerà al seu compte, i quan l’acabi et arribarà un avís per revisar-la.',
  'nav.notas': 'Notes i To-Do',
  'nav.etiquetas': 'Etiquetes',
  'etiquetas.filtro': 'Filtra per etiqueta',
  'etiquetas.filtro.todas': 'Totes les etiquetes',
  'etiquetas.primerNivel': 'Primer nivell',
  'etiquetas.titulo': 'Etiquetes i categories',
  'etiquetas.descripcion': 'Organitza les teves etiquetes en categories de fins a {niveles} nivells, per exemple Estudi › Matemàtiques › Càlcul. En filtrar per una etiqueta s’inclouen també les que en pengen.',
  'etiquetas.nueva': 'Nova etiqueta',
  'etiquetas.nombre': 'Nom',
  'etiquetas.dentroDe': 'Dins de',
  'etiquetas.crear': 'Crea',
  'etiquetas.tuyas': 'Les teves etiquetes',
  'etiquetas.vacio': 'Encara no tens etiquetes. Crea’n una a dalt o escriu-la al detall d’una tasca.',
  'etiquetas.renombrar': 'Canvia el nom de {nombre}',
  'etiquetas.mover': 'Mou {nombre} dins de',
  'etiquetas.eliminar': 'Elimina {nombre}',
  'notas.titulo': 'Notes i To-Do',
  'notas.pestana.notas': 'Notes',
  'notas.pestana.todo': 'To-Do',
  'notas.sinVinculo': 'Sense associar',
  'notas.objetivos': 'Objectius',
  'notas.tareas': 'Tasques',
  'notas.filtrar': 'Mostra:',
  'notas.filtrar.todas': 'Totes',
  'notas.vacio': 'Encara no hi ha notes aquí.',
  'notas.todo.vacio': 'Encara no hi ha to-dos aquí.',
  'notas.nueva': 'Nova nota',
  'notas.todo.nuevo': 'Nou to-do',
  'notas.placeholder': 'Escriu una nota…',
  'notas.todo.placeholder': 'Què cal fer?',
  'notas.asociarA': 'Associa a',
  'notas.conCasilla': 'Amb casella',
  'notas.anadir': 'Afegeix',
  'notas.marcar': 'Marca «{contenido}»',
  'notas.editar': 'Edita la nota',
  'notas.vinculo.tarea': 'Tasca: {titulo}',
  'notas.vinculo.objetivo': 'Objectiu: {titulo}',
  'notas.quitarCasilla': 'Treu la casella',
  'notas.ponerCasilla': 'Afegeix casella',
  'notas.eliminar': 'Elimina',
  'ajustes.perfil.titulo': 'Perfil',
  'ajustes.perfil.descripcion': 'Tria per a què fas servir FocusFlow: l’Inici s’adapta als perfils marcats. En pots marcar diversos.',
  'ajustes.perfil.sugeridos': 'Ara mateix es fan servir els perfils que suggereix l’aplicació segons el que utilitzes. Marca o desmarca per triar-los tu.',
  'perfil.ESTUDIANTE': 'Estudiant',
  'perfil.PROFESIONAL': 'Professional',
  'perfil.PADRE': 'Pare o mare',
  'inicio.perfiles.sugeridos': 'Inici pensat per a: {perfiles} (suggerit; <enlace>canvia-ho a Configuració</enlace>).',
  'inicio.perfiles.elegidos': 'Inici pensat per a: {perfiles} (<enlace>canvia</enlace>).',
  'inicio.verTodo': 'Mostra-ho tot',
  'inicio.verAgenda': 'Mostra l’agenda',
  'inicio.todos.titulo': 'To-Do pendents',
  'inicio.todos.vacio': 'No tens to-dos pendents.',
  'inicio.clases.titulo': 'Classes d’avui',
  'inicio.clases.vacio': 'Avui no hi ha classe.',
  'inicio.clases.sinModoEscolar': 'Activa el mode escolar a Configuració per veure aquí les teves classes.',
  'inicio.clases.sinHorario': 'Crea el teu horari de classe per veure aquí les classes d’avui.',
  'inicio.entregas.titulo': 'Properes entregues',
  'inicio.entregas.vacio': 'No tens entregues escolars pendents.',
  'inicio.vacaciones.titulo': 'Properes vacances',
  'inicio.vacaciones.vacio': 'No hi ha vacances a la vista (activa el mode escolar i crea el teu horari).',
  'inicio.prioridades.titulo': 'Prioritats',
  'inicio.prioridades.vacio': 'Res urgent i important ni d’alt impacte pendent.',
  'inicio.pomodoros.titulo': 'Pomodoros d’avui',
  'inicio.pomodoros.empezar': 'Comença’n un',
  'inicio.pomodoros.hoy': '{cantidad, plural, =0 {Encara cap pomodoro avui.} one {pomodoro completat avui} other {pomodoros completats avui}}',
  'inicio.revisiones.titulo': 'Revisions pendents',
  'inicio.revisiones.sinVinculo': 'Encara no supervises ningú. Vincula’t des de Família.',
  'inicio.revisiones.pendientes': '{cantidad, plural, =0 {res per revisar} one {# per revisar} other {# per revisar}}',
  'tarea.detalle.notas': '{cantidad, plural, =0 {Notes i to-dos} other {Notes i to-dos (#)}}',
  'tarea.detalle.abrirNotas': 'Obre a Notes',
  'tarea.detalle.nuevoTodo': 'Nou to-do per a aquesta tasca',
  'objetivos.notas': '{cantidad, plural, =0 {📝 Afegeix notes o to-dos} one {📝 # nota o to-do} other {📝 # notes i to-dos}}',
  'busqueda.abrir': 'Cerca',
  'busqueda.titulo': 'Cerca a FocusFlow',
  'busqueda.placeholder': 'Tasques, subtasques, objectius, notes, etiquetes…',
  'busqueda.minimo': 'Escriu almenys 2 lletres. No importen els accents ni les majúscules.',
  'busqueda.sinResultados': 'No hi ha res que coincideixi amb «{consulta}».',
  'busqueda.grupo.tareas': 'Tasques',
  'busqueda.grupo.objetivos': 'Objectius',
  'busqueda.grupo.notas': 'Notes i To-Do',
  'busqueda.grupo.etiquetas': 'Etiquetes',
  'busqueda.enSubtarea': 'A la subtasca: {titulo}',
  'busqueda.tipo.nota': 'Nota',
  'busqueda.tipo.todo': 'To-Do',
  'busqueda.verEtiqueta': 'Veure les seves tasques al Kanban',
  'estadisticas.porCategoria.tituloEtiqueta': 'Temps de concentració per etiqueta',
  'estadisticas.porCategoria.tituloAsignatura': 'Temps de concentració per assignatura',
  'estadisticas.porCategoria.agrupar': 'Agrupa per',
  'estadisticas.porCategoria.etiquetas': 'Etiquetes',
  'estadisticas.porCategoria.asignaturas': 'Assignatures',
  'estadisticas.porCategoria.periodo': 'Període',
  'estadisticas.porCategoria.semana': '7 dies',
  'estadisticas.porCategoria.mes': '30 dies',
  'estadisticas.porCategoria.siempre': 'Sempre',
  'estadisticas.porCategoria.vacio': 'Encara no hi ha pomodoros de treball en aquest període.',
  'estadisticas.porCategoria.total': 'Total de concentració: {duracion}.',
  'estadisticas.porCategoria.horasMinutos': '{horas} h {minutos} min',
  'estadisticas.porCategoria.minutos': '{minutos} min',
  'estadisticas.porCategoria.sinEtiqueta': 'Tasques sense etiqueta',
  'estadisticas.porCategoria.sinAsignatura': 'Tasques sense assignatura',
  'estadisticas.porCategoria.sinTarea': 'Pomodoros sense tasca',
  'estadisticas.porCategoria.notaVariasEtiquetas': 'Una tasca amb diverses etiquetes suma el seu temps a totes.',
  'ajustes.push.titulo': 'Avisos en aquest dispositiu',
  'ajustes.push.descripcion': 'Rep els recordatoris, les alarmes i les revisions com a notificació del mòbil o de l’ordinador, encara que FocusFlow estigui tancat. S’activa a cada dispositiu per separat.',
  'ajustes.push.activar': 'Activa els avisos en aquest dispositiu',
  'ajustes.push.desactivar': 'Desactiva',
  'ajustes.push.probar': 'Envia un avís de prova',
  'ajustes.push.pruebaEnviada': 'Avís de prova enviat: hauria d’aparèixer d’aquí a uns segons.',
  'ajustes.push.activo': 'Activats en aquest dispositiu.',
  'ajustes.push.noSoportado': 'Aquest navegador no permet avisos amb l’app tancada. A l’iPhone o l’iPad, primer afegeix FocusFlow a la pantalla d’inici (Comparteix → Afegeix a la pantalla d’inici) i obre’l des d’allà.',
  'ajustes.push.noConfigurado': 'El servidor encara no té configurats els avisos amb l’app tancada.',
  'ajustes.push.bloqueado': 'Les notificacions de FocusFlow estan bloquejades en aquest navegador. Permet-les des del cadenat al costat de l’adreça i torna a entrar a Configuració.',
  'ajustes.push.error': 'No s’han pogut canviar els avisos d’aquest dispositiu',
  'ajustes.push.instalar': 'Consell: instal·la FocusFlow com una app més des del menú del navegador (Instal·la l’aplicació o Afegeix a la pantalla d’inici).',
  'error.CORREO_O_CONTRASENA_INCORRECTOS': 'Correu o contrasenya incorrectes',
  'error.USUARIO_YA_EXISTE': 'Ja existeix un usuari amb aquest correu',
  'error.USUARIO_NO_ENCONTRADO': 'No s’ha trobat l’usuari',
  'error.CORREO_NO_VALIDO': 'El correu electrònic no és vàlid',
  'error.CONTRASENA_CORTA': 'La contrasenya ha de tenir almenys 8 caràcters',
  'error.CONTRASENA_DEBIL': 'La contrasenya ha d’incloure majúscules, minúscules i números',
  'error.FECHA_NACIMIENTO_NO_VALIDA': 'La data de naixement no és vàlida',
  'error.FALTA_CORREO_TUTOR': 'Cal el correu d’un tutor legal per als menors de 18 anys',
  'error.CONSENTIMIENTO_PENDIENTE': 'Compte pendent de confirmació d’un tutor legal',
  'error.ENLACE_CONFIRMACION_NO_VALIDO': 'Enllaç de confirmació caducat o no vàlid',
  'error.SIN_CORREO_TUTOR': 'Aquest compte no té cap correu de tutor registrat',
  'error.ESPERA_REENVIO_CORREO': 'Espera uns minuts abans de tornar a demanar el correu',
  'error.ENLACE_VERIFICACION_NO_VALIDO': 'Enllaç de verificació caducat o no vàlid',
  'error.CORREO_NO_CONFIGURADO': 'L’enviament de correu no està configurat al servidor',
  'error.TAREA_NO_ENCONTRADA': 'No s’ha trobat la tasca',
  'error.SUBTAREA_NO_ENCONTRADA': 'No s’ha trobat la subtasca',
  'error.OBJETIVO_NO_ENCONTRADO': 'No s’ha trobat l’objectiu',
  'error.NOTA_NO_ENCONTRADA': 'No s’ha trobat la nota',
  'error.TODO_SIEMPRE_CON_CASILLA': 'Un to-do sempre té casella',
  'error.ETIQUETA_NO_ENCONTRADA': 'No s’ha trobat l’etiqueta',
  'error.ETIQUETA_YA_EXISTE': 'Ja tens una etiqueta amb aquest nom',
  'error.ETIQUETA_DENTRO_DE_SI_MISMA': 'Una etiqueta no pot anar dins d’ella mateixa',
  'error.HORARIO_NO_ENCONTRADO': 'No s’ha trobat l’horari',
  'error.CURSO_NO_ENCONTRADO': 'No s’ha trobat el curs',
  'error.ASIGNATURA_NO_ENCONTRADA': 'No s’ha trobat l’assignatura',
  'error.ASIGNATURA_NO_ESTA_EN_HORARIO': 'No s’ha trobat l’assignatura en aquest horari',
  'error.ASIGNATURA_NO_ESTA_EN_TUS_HORARIOS': 'No s’ha trobat l’assignatura als teus horaris',
  'error.ASIGNATURA_NO_ES_DEL_CURSO': 'No s’ha trobat l’assignatura per al curs d’aquest horari',
  'error.ASIGNATURA_FUERA_DEL_HORARIO': 'Aquesta assignatura no és en aquest horari',
  'error.ASIGNATURA_YA_EN_HORARIO': 'Aquesta assignatura ja és a l’horari',
  'error.SOLO_BORRAR_ASIGNATURAS_PROPIAS': 'Només es poden esborrar les assignatures que has afegit tu',
  'error.FRANJA_NO_ENCONTRADA': 'No s’ha trobat la franja en aquest horari',
  'error.FRANJA_DE_OTRO_HORARIO': 'Una de les franges no pertany a aquest horari',
  'error.CLASE_EN_DESCANSO': 'En una franja de descans no es poden posar classes',
  'error.RECORDATORIO_NO_ENCONTRADO': 'No s’ha trobat el recordatori',
  'error.AVISO_NO_ENCONTRADO': 'No s’ha trobat l’avís',
  'error.DIA_NO_LECTIVO_NO_ENCONTRADO': 'No s’ha trobat el dia no lectiu',
  'error.FECHA_FIN_ANTERIOR': 'La data de fi no pot ser anterior a la d’inici',
  'error.CODIGO_VINCULO_NO_VALIDO': 'El codi no és vàlid o ha caducat',
  'error.VINCULO_CON_UNO_MISMO': 'No et pots vincular amb el teu propi compte',
  'error.YA_VINCULADOS': 'Ja esteu vinculats',
  'error.CODIGO_NO_GENERADO': 'No s’ha pogut generar un codi, torna-ho a provar',
  'error.VINCULO_NO_ENCONTRADO': 'No s’ha trobat el vincle',
  'error.PERSONA_NO_VINCULADA': 'Aquesta persona no està vinculada amb tu',
  'error.REVISION_NO_PENDIENTE': 'Aquesta tasca no està pendent de revisió',
  'error.SOLO_ADULTO_AUTORIZA': 'Només una persona adulta pot autoritzar el compte d’un menor',
  'error.GOOGLE_NO_CONFIGURADO': 'La sincronització amb Google Calendar no està configurada al servidor',
  'error.GOOGLE_NO_CONECTADO': 'Aquest compte no està connectat amb Google Calendar',
  'error.ENLACE_GOOGLE_NO_VALIDO': 'Enllaç de connexió amb Google caducat o no vàlid',
  'error.NO_AUTENTICADO': 'La teva sessió ha caducat. Torna a iniciar la sessió.',
  'error.SIN_PERMISO': 'No tens permís per fer això',
  'error.NO_ENCONTRADO': 'No s’ha trobat el que buscaves',
  'error.SIN_CONEXION': 'No s’ha pogut connectar amb el servidor. Comprova la connexió.',
  'error.ERROR_INTERNO': 'Hi ha hagut un error al servidor. Torna-ho a provar més tard.',
  'error.ERROR_DESCONOCIDO': 'Hi ha hagut un error inesperat',
  'error.IA_NO_DISPONIBLE': 'La IA no està disponible ara mateix',
  'error.PLAN_SIN_IA': 'L’ajuda de la IA està inclosa al pla Plus',
  'error.LIMITE_IA_ALCANZADO': 'Has arribat al límit d’usos de la IA d’aquest mes',
  'error.FOTO_NO_VALIDA': 'Puja una foto (JPG, PNG o WEBP) de menys de 5 MB',
  'error.IA_RESPUESTA_NO_VALIDA': 'La IA no ha donat una proposta vàlida, torna-ho a provar',
  'error.TAREA_SIN_FECHA_LIMITE': 'Posa una data límit a la tasca per poder planificar l’estudi',
  'error.PLAN_SIN_DIAS': 'No queden dies per estudiar abans de la data límit',
  'ia.titulo': 'Ajuda de la IA',
  'ia.dividir': 'Divideix en passos',
  'ia.plan': 'Pla d’estudi fins a la data',
  'ia.pensando': 'La IA està pensant… Pot trigar fins a un minut.',
  'ia.error': 'No s’ha pogut obtenir la proposta de la IA',
  'ia.revisaPasos': 'Revisa la proposta: pots canviar el text i desmarcar el que no vulguis.',
  'ia.revisaPlan': 'Cada sessió s’afegirà com una tasca amb la seva data i sortirà a l’Agenda. Pots canviar el text i desmarcar el que no vulguis.',
  'ia.incluir': 'Inclou «{titulo}»',
  'ia.editar': 'Text de la proposta',
  'ia.minutos': '{minutos} min',
  'ia.anadirPasos': '{cantidad, plural, one {Afegeix # subtasca} other {Afegeix # subtasques}}',
  'ia.anadirPlan': '{cantidad, plural, one {Afegeix # sessió} other {Afegeix # sessions}}',
  'ia.otraPropuesta': 'Una altra proposta',
  'ia.descartar': 'Descarta',
  'ia.anadidas': '{cantidad, plural, one {S’ha afegit # element.} other {S’han afegit # elements.}}',
  'ia.plus.titulo': 'L’ajuda de la IA és al pla Plus',
  'ia.plus.explicacion': 'Amb Plus, la IA divideix les teves tasques en passos, et prepara un pla d’estudi fins a la data de l’examen i redacta els teus recordatoris. Sempre et proposa i tu decideixes.',
  'ia.plus.proximamente': 'Aviat el podràs contractar des d’Ajustos.',
  'ia.usos': 'Aquest mes: {usados} de {limite} usos.',
  'fotos.horario.boton': 'Omple des d’una foto',
  'fotos.horario.ayuda': 'Fes una foto a l’horari de classe (o tria’n una de la galeria) i la IA el passarà a la graella. Abans de desar-lo el podràs revisar.',
  'fotos.horario.revisa': 'Revisa l’horari que ha llegit la IA. En aplicar-lo se substitueix la graella actual; després pots corregir qualsevol cel·la amb «Edita l’horari».',
  'fotos.horario.aplicar': 'Aplica a l’horari',
  'fotos.horario.aplicado': 'Horari actualitzat a partir de la foto.',
  'fotos.entregas.boton': 'Afegeix des d’una foto',
  'fotos.entregas.ayuda': 'Fes una foto al calendari d’exàmens, a l’agenda o a la circular de l’escola i la IA en traurà els exàmens, treballs i presentacions amb la seva data.',
  'fotos.entregas.revisa': 'Revisa el que ha llegit la IA: pots canviar el text, la data, el tipus i l’assignatura, i desmarcar el que no vulguis.',
  'fotos.entregas.anadir': '{cantidad, plural, one {Afegeix # lliurament} other {Afegeix # lliuraments}}',
  'fotos.entregas.anadidas': '{cantidad, plural, one {S’ha afegit # lliurament.} other {S’han afegit # lliuraments.}}',
  'fotos.entregas.incluir': 'Inclou «{titulo}»',
  'fotos.entregas.fecha': 'Data',
  'fotos.entregas.titulo': 'Títol',
  'fotos.entregas.tipo': 'Tipus',
  'fotos.entregas.asignatura': 'Assignatura',
  'fotos.elegir': 'Fes o tria una foto',
  'fotos.leyendo': 'S’està llegint la foto… Pot trigar uns segons.',
  'fotos.descartar': 'Descarta',
  'fotos.otraFoto': 'Prova amb una altra foto',
  'fotos.error': 'No s’ha pogut llegir la foto',
  'fotos.sinAsignatura': 'Sense assignatura',
  'fotos.soloPlus': 'Llegir l’horari o els exàmens des d’una foto està inclòs al pla Plus.',
  'ajustes.plan.titulo': 'El teu pla',
  'ajustes.plan.gratuito': 'Gratuït: totes les funcions d’organització, sense l’ajuda de la IA.',
  'ajustes.plan.pago': 'Plus: amb l’ajuda de la IA.',
  'ajustes.plan.familiar': 'Plus a través de la teva família: l’ajuda de la IA et ve pel pla del teu pare, mare o tutor.',
  'bienvenida.paso': 'Pas {paso} de {total}',
  'bienvenida.saltar': 'Omet',
  'bienvenida.siguiente': 'Següent',
  'bienvenida.perfil.titulo': 'Hola, {nombre}! Per a què faràs servir FocusFlow?',
  'bienvenida.perfil.descripcion': 'Marca tot el que encaixi amb tu: l’Inici s’adapta al que triïs. Ho pots canviar quan vulguis a Configuració.',
  'bienvenida.perfil.ESTUDIANTE': 'Deures, exàmens, treballs i el teu horari de classe.',
  'bienvenida.perfil.PROFESIONAL': 'Projectes, objectius i concentració amb Pomodoro.',
  'bienvenida.perfil.PADRE': 'Revisar les tasques dels teus fills i assignar-los tasques.',
  'bienvenida.escolar.titulo': 'Activem el mode escolar?',
  'bienvenida.escolar.si': 'Sí, activa’l',
  'bienvenida.escolar.no': 'Ara no',
  'bienvenida.horario.titulo': 'El teu horari de classe',
  'bienvenida.horario.descripcion': 'Digues-nos el teu curs i la teva comunitat: l’app et proposarà les assignatures oficials i el calendari escolar (vacances i festius). Després podràs omplir la graella amb les teves classes.',
  'bienvenida.horario.despues': 'Ho faré més tard',
  'bienvenida.listo.titulo': 'Tot a punt!',
  'bienvenida.listo.empezar': 'Comença',
  'bienvenida.listo.rellenarHorario': 'Omple el meu horari',
  'bienvenida.consejo.captura': 'Apunta qualsevol cosa al vol amb la barra «Què tens al cap?» de baix; ja ho organitzaràs després.',
  'bienvenida.consejo.buscar': 'Cerca a tot arreu amb Ctrl+K (o amb la lupa, al mòbil).',
  'bienvenida.consejo.familia': 'Per revisar les tasques del teu fill o filla, demana-li que generi un codi a Família i escriu-lo a la teva.',
  'bienvenida.consejo.pomodoro': 'Concentra’t amb el Pomodoro: 25 minuts de feina i un descans. A Estadístiques veuràs quant de temps dediques a cada assignatura.',
  'bienvenida.consejo.avisos': 'A Recordatoris pots crear alarmes per a entregues i exàmens, i a Configuració, activar els avisos al mòbil.',
  'error.CLASSROOM_NO_CONECTADO': 'Connecta Google Classroom per importar els teus deures',
  'error.CLASSROOM_API_DESACTIVADA': 'L’API de Google Classroom no està activada al projecte de Google Cloud',
  'error.CLASSROOM_SIN_PERMISO': 'Google no permet que FocusFlow llegeixi el teu Classroom (potser el teu centre ho té restringit)',
  'classroom.titulo': 'Google Classroom',
  'classroom.descripcion': 'Importa com a tasques escolars els treballs que tens pendents de lliurar a les teves classes, amb la data de lliurament i l’enllaç a Classroom. Si tornes a importar, no es dupliquen i s’actualitza la data si el professor la canvia.',
  'classroom.conectar': 'Connecta Google Classroom',
  'classroom.aviso': 'Només demana permís per llegir les teves classes i els teus treballs; mai no escriu a Classroom. Alguns centres no permeten connectar altres apps als comptes d’alumnes.',
  'classroom.importar': 'Importa els deures ara',
  'classroom.importando': 'Important…',
  'classroom.resumen': '{cursos, plural, one {# classe revisada} other {# classes revisades}}: {nuevas, plural, =0 {cap treball nou} one {# treball nou} other {# treballs nous}} i {actualizadas, plural, =0 {cap actualitzat} one {# actualitzat} other {# actualitzats}}.',
  'classroom.error': 'No s’han pogut importar els treballs de Classroom',
};
