export const ca = {
  'app.titulo': 'FocusFlow',
  'app.eslogan': 'Organitza els teus objectius, enfoca el teu temps.',
  'bienvenida.mensaje': 'Benvingut a FocusFlow!',
  'selector.idioma.etiqueta': 'Idioma',
  'auth.registro.titulo': 'Crear compte',
  'auth.registro.nombre': 'Nom',
  'auth.registro.correo': 'Correu electrònic',
  'auth.registro.contrasena': 'Contrasenya',
  'auth.registro.boton': 'Registrar-me',
  'auth.registro.enlaceLogin': 'Ja tens compte? Inicia sessió',
  'auth.login.titulo': 'Iniciar sessió',
  'auth.login.correo': 'Correu electrònic',
  'auth.login.contrasena': 'Contrasenya',
  'auth.login.boton': 'Entrar',
  'auth.login.enlaceRegistro': 'No tens compte? Registra\'t',
  'auth.cerrarSesion': 'Tancar sessió',
  'auth.bienvenidoUsuario': 'Hola, {nombre}',
  'inicio.irAObjetivos': 'Veure els meus objectius',
  'objetivos.titulo': 'Els meus objectius',
  'objetivos.nuevo.tituloPlaceholder': 'Títol de l\'objectiu',
  'objetivos.nuevo.descripcionPlaceholder': 'Descripció (opcional)',
  'objetivos.nuevo.boton': 'Crear objectiu',
  'objetivos.vacio': 'Encara no tens objectius. Crea el primer!',
  'objetivos.eliminar': 'Eliminar objectiu',
  'objetivos.progreso': '{completadas} de {total} tasques',
  'tareas.tituloPlaceholder': 'Nova tasca',
  'tareas.anadir': 'Afegir',
  'tareas.sueltas.titulo': 'Tasques soltes',
  'tareas.eliminar': 'Eliminar tasca',
  'tareas.marcarCompletada': 'Marcar "{titulo}" com a completada',
  'inicio.irAPomodoro': 'Temporitzador Pomodoro',
  'pomodoro.fase.trabajo': 'Treball',
  'pomodoro.fase.descansoCorto': 'Descans curt',
  'pomodoro.fase.descansoLargo': 'Descans llarg',
  'pomodoro.ciclo': 'Cicle {actual} de {total}',
  'pomodoro.iniciar': 'Iniciar',
  'pomodoro.pausar': 'Pausar',
  'pomodoro.reiniciar': 'Reiniciar',
  'inicio.irAKanban': 'Tauler Kanban',
  'kanban.titulo': 'Tauler Kanban',
  'kanban.columna.porHacer': 'Per fer',
  'kanban.columna.enProceso': 'En procés',
  'kanban.columna.hecha': 'Feta',
  'kanban.mover.anterior': 'Moure a la columna anterior',
  'kanban.mover.siguiente': 'Moure a la columna següent',
  'inicio.irAEisenhower': 'Matriu d\'Eisenhower',
  'eisenhower.titulo': 'Matriu d\'Eisenhower',
  'eisenhower.cuadrante.hacer': 'Fer ja',
  'eisenhower.cuadrante.planificar': 'Planificar',
  'eisenhower.cuadrante.delegar': 'Delegar',
  'eisenhower.cuadrante.eliminar': 'Eliminar',
  'eisenhower.marcar.urgente': 'Urgent',
  'eisenhower.marcar.importante': 'Important',
  'captura.placeholder': 'Què tens en ment?',
  'captura.boton': 'Capturar',
  'inicio.irAEstadisticas': 'Estadístiques',
  'estadisticas.titulo': 'Estadístiques',
  'estadisticas.progresoGlobal': 'Progrés global',
  'estadisticas.distribucion.titulo': 'Distribució de tasques',
  'estadisticas.objetivos.titulo': 'Progrés per objectiu',
  'estadisticas.pareto.titulo': 'Tasques d\'alt impacte (Pareto 80/20)',
  'estadisticas.pareto.leyendaAltoImpacto': 'Alt impacte',
  'estadisticas.pareto.descripcion':
    '{marcadas} de {total} tasques estan marcades com d\'alt impacte ({porcentaje}%).',
  'estadisticas.pareto.vacio':
    'Encara no has marcat cap tasca com d\'alt impacte. Marca-les amb ★ des del tauler Kanban.',
  'pareto.marcar': 'Marcar com d\'alt impacte',
  'tema.activarOscuro': 'Activar mode fosc',
  'tema.activarClaro': 'Activar mode clar',
};
