export const en = {
  'app.titulo': 'FocusFlow',
  'app.eslogan': 'Organize your goals, focus your time.',
  'bienvenida.mensaje': 'Welcome to FocusFlow!',
  'selector.idioma.etiqueta': 'Language',
  'auth.registro.titulo': 'Create account',
  'auth.registro.nombre': 'Name',
  'auth.registro.correo': 'Email',
  'auth.registro.contrasena': 'Password',
  'auth.registro.boton': 'Sign up',
  'auth.registro.enlaceLogin': 'Already have an account? Sign in',
  'auth.login.titulo': 'Sign in',
  'auth.login.correo': 'Email',
  'auth.login.contrasena': 'Password',
  'auth.login.boton': 'Sign in',
  'auth.login.enlaceRegistro': "Don't have an account? Sign up",
  'auth.cerrarSesion': 'Sign out',
  'auth.bienvenidoUsuario': 'Hi, {nombre}',
  'inicio.irAObjetivos': 'View my goals',
  'objetivos.titulo': 'My goals',
  'objetivos.nuevo.tituloPlaceholder': 'Goal title',
  'objetivos.nuevo.descripcionPlaceholder': 'Description (optional)',
  'objetivos.nuevo.boton': 'Create goal',
  'objetivos.vacio': "You don't have any goals yet. Create the first one!",
  'objetivos.eliminar': 'Delete goal',
  'objetivos.progreso': '{completadas} of {total} tasks',
  'tareas.tituloPlaceholder': 'New task',
  'tareas.anadir': 'Add',
  'tareas.sueltas.titulo': 'Standalone tasks',
  'tareas.eliminar': 'Delete task',
  'inicio.irAPomodoro': 'Pomodoro timer',
  'pomodoro.fase.trabajo': 'Work',
  'pomodoro.fase.descansoCorto': 'Short break',
  'pomodoro.fase.descansoLargo': 'Long break',
  'pomodoro.ciclo': 'Cycle {actual} of {total}',
  'pomodoro.iniciar': 'Start',
  'pomodoro.pausar': 'Pause',
  'pomodoro.reiniciar': 'Reset',
  'inicio.irAKanban': 'Kanban board',
  'kanban.titulo': 'Kanban board',
  'kanban.columna.porHacer': 'To do',
  'kanban.columna.enProceso': 'In progress',
  'kanban.columna.hecha': 'Done',
  'kanban.mover.anterior': 'Move to previous column',
  'kanban.mover.siguiente': 'Move to next column',
  'inicio.irAEisenhower': 'Eisenhower matrix',
  'eisenhower.titulo': 'Eisenhower matrix',
  'eisenhower.cuadrante.hacer': 'Do now',
  'eisenhower.cuadrante.planificar': 'Schedule',
  'eisenhower.cuadrante.delegar': 'Delegate',
  'eisenhower.cuadrante.eliminar': 'Delete',
  'eisenhower.marcar.urgente': 'Urgent',
  'eisenhower.marcar.importante': 'Important',
  'captura.placeholder': "What's on your mind?",
  'captura.boton': 'Capture',
  'inicio.irAEstadisticas': 'Statistics',
  'estadisticas.titulo': 'Statistics',
  'estadisticas.progresoGlobal': 'Overall progress',
  'estadisticas.distribucion.titulo': 'Task distribution',
  'estadisticas.objetivos.titulo': 'Progress by goal',
  'estadisticas.pareto.titulo': 'High-impact tasks (Pareto 80/20)',
  'estadisticas.pareto.leyendaAltoImpacto': 'High impact',
  'estadisticas.pareto.descripcion':
    '{marcadas} of {total} tasks are marked as high impact ({porcentaje}%).',
  'estadisticas.pareto.vacio':
    "You haven't marked any task as high impact yet. Mark them with ★ from the Kanban board.",
  'pareto.marcar': 'Mark as high impact',
};
