export const en = {
  'app.titulo': 'FocusFlow',
  'app.eslogan': 'Organize your goals, focus your time.',
  'bienvenida.mensaje': 'Welcome to FocusFlow!',
  'selector.idioma.etiqueta': 'Language',
  'auth.registro.titulo': 'Create account',
  'auth.registro.nombre': 'Name',
  'auth.registro.correo': 'Email',
  'auth.registro.contrasena': 'Password',
  'auth.registro.fechaNacimiento': 'Date of birth',
  'auth.registro.correoTutor': "Your parent or legal guardian's email",
  'auth.registro.correoTutorAyuda':
    'Since you are under 18, we need your guardian to confirm the use of this account.',
  'auth.registro.boton': 'Sign up',
  'auth.registro.enlaceLogin': 'Already have an account? Sign in',
  'auth.login.titulo': 'Sign in',
  'auth.login.correo': 'Email',
  'auth.login.contrasena': 'Password',
  'auth.login.boton': 'Sign in',
  'auth.login.enlaceRegistro': "Don't have an account? Sign up",
  'auth.cerrarSesion': 'Sign out',
  'auth.bienvenidoUsuario': 'Hi, {nombre}',
  'objetivos.titulo': 'My goals',
  'objetivos.nuevo.tituloPlaceholder': 'Goal title',
  'objetivos.nuevo.descripcionPlaceholder': 'Description (optional)',
  'objetivos.nuevo.boton': 'Create goal',
  'objetivos.vacio': "You don't have any goals yet. Create the first one!",
  'objetivos.eliminar': 'Delete goal',
  'objetivos.progreso': '{completadas} of {total} tasks',
  'fechaLimite.etiqueta': 'Due date (optional)',
  'inicio.proximos.titulo': 'Next 7 days',
  'inicio.proximos.vacio': 'No tasks with a due date in the next 7 days.',
  'tareas.tituloPlaceholder': 'New task',
  'tareas.anadir': 'Add',
  'tareas.sueltas.titulo': 'Standalone tasks',
  'tareas.eliminar': 'Delete task',
  'tareas.marcarCompletada': 'Mark "{titulo}" as done',
  'tarea.detalle.descripcion': 'Notes',
  'tarea.detalle.recurrencia': 'Repeat',
  'tarea.recurrencia.ninguna': "Doesn't repeat",
  'tarea.recurrencia.diaria': 'Every day',
  'tarea.recurrencia.semanal': 'Every week',
  'tarea.detalle.ambito': 'Scope',
  'ambito.selector': 'Scope',
  'ambito.todos': 'All',
  'ambito.personal': 'Personal',
  'ambito.escolar': 'School',
  'tarea.detalle.etiquetas': 'Tags',
  'tarea.detalle.nuevaEtiqueta': 'New tag',
  'tarea.detalle.quitarEtiqueta': 'Remove tag {nombre}',
  'tarea.detalle.subtareas': 'Subtasks ({completadas} of {total})',
  'tarea.detalle.nuevaSubtarea': 'New step',
  'tarea.detalle.tiempoEstimado': 'Estimated time (minutes)',
  'tarea.detalle.tiempoEstimadoPlaceholder': 'e.g. 30',
  'tarea.detalle.tiempoReal': 'Actual time: {minutos} min',
  'tarea.detalle.fechaLimite': 'Due date',
  'tarea.detalle.horaInicio': 'Start time',
  'tarea.detalle.duracion': 'Duration (minutes)',
  'pomodoro.fase.trabajo': 'Work',
  'pomodoro.fase.descansoCorto': 'Short break',
  'pomodoro.fase.descansoLargo': 'Long break',
  'pomodoro.ciclo': 'Cycle {actual} of {total}',
  'pomodoro.iniciar': 'Start',
  'pomodoro.pausar': 'Pause',
  'pomodoro.reiniciar': 'Reset',
  'pomodoro.tareaAsociada.etiqueta': 'Associated task (optional)',
  'pomodoro.tareaAsociada.ninguna': 'None',
  'pomodoro.historial.titulo': 'Recent history',
  'pomodoro.historial.vacio': "You haven't completed any session yet.",
  'pomodoro.historial.minutos': '{minutos} min',
  'kanban.titulo': 'Kanban board',
  'kanban.columna.porHacer': 'To do',
  'kanban.columna.enProceso': 'In progress',
  'kanban.columna.hecha': 'Done',
  'kanban.mover.anterior': 'Move to previous column',
  'kanban.mover.siguiente': 'Move to next column',
  'eisenhower.titulo': 'Eisenhower matrix',
  'eisenhower.cuadrante.hacer': 'Do now',
  'eisenhower.cuadrante.planificar': 'Schedule',
  'eisenhower.cuadrante.delegar': 'Delegate',
  'eisenhower.cuadrante.eliminar': 'Delete',
  'eisenhower.marcar.urgente': 'Urgent',
  'eisenhower.marcar.importante': 'Important',
  'eisenhower.autoUrgente': 'Urgent due date',
  'captura.placeholder': "What's on your mind?",
  'captura.boton': 'Capture',
  'estadisticas.titulo': 'Statistics',
  'estadisticas.progresoGlobal': 'Overall progress',
  'estadisticas.distribucion.titulo': 'Task distribution',
  'estadisticas.objetivos.titulo': 'Progress by goal',
  'estadisticas.pareto.titulo': 'High-impact tasks (Pareto 80/20)',
  'estadisticas.pareto.leyendaAltoImpacto': 'High impact',
  'estadisticas.pareto.descripcion':
    '{marcadas} of {total} tasks are marked as high impact ({porcentaje}%).',
  'estadisticas.pareto.vacio':
    "You haven't marked any task as high impact yet. Mark them with ★ from the Kanban board.",
  'pareto.marcar': 'Mark as high impact',
  'estadisticas.pomodoro.titulo': 'Pomodoro',
  'estadisticas.pomodoro.hoy': 'Completed today',
  'estadisticas.pomodoro.semana': 'Completed this week',
  'estadisticas.pomodoro.minutosSemana': 'Work minutes this week',
  'estadisticas.pomodoro.vacio': "You haven't completed any work session yet.",
  'estadisticas.racha': '{racha, plural, one {Streak: # day in a row} other {Streak: # days in a row}}',
  'estadisticas.racha.vacia': "You don't have an active streak yet. Start today!",
  'tema.activarOscuro': 'Turn on dark mode',
  'tema.activarClaro': 'Turn on light mode',
  'revision.titulo': 'Weekly review',
  'revision.eslogan': "A weekly look at what you've moved forward and what's fallen behind.",
  'revision.vencidas.titulo': 'Overdue tasks',
  'revision.vencidas.vacio': "You don't have any overdue tasks. Well done!",
  'revision.completadas.titulo': 'Completed this week',
  'revision.completadas.vacio': "You haven't completed any task this week.",
  'revision.objetivosSinTocar.titulo': 'Untouched goals',
  'revision.objetivosSinTocar.vacio': 'All your goals have recent activity.',
  'revision.objetivosSinTocar.diasInactivo':
    '{dias, plural, one {No changes for # day} other {No changes for # days}}',
  'revision.sueltas.titulo': 'Standalone tasks to organize',
  'revision.sueltas.vacio': "All organized! You don't have pending standalone tasks.",
  'revision.sueltas.organizar': 'Organize in Goals',
  'estadisticas.actividad.titulo': 'Daily activity',
  'estadisticas.actividad.tooltip': '{cantidad, plural, =0 {No pomodoros} one {# pomodoro} other {# pomodoros}}',
  'estadisticas.actividad.menos': 'Less',
  'estadisticas.actividad.mas': 'More',
  'estadisticas.tiempoComparado.titulo': 'Estimated vs. actual time',
  'estadisticas.tiempoComparado.vacio':
    "Set an estimated time on a task (from its detail view) and log Pomodoro sessions for it to see it compared here.",
  'estadisticas.tiempoComparado.estimado': 'Estimated: {minutos} min',
  'estadisticas.tiempoComparado.real': 'Actual: {minutos} min',
  'estadisticas.exportar.csv': 'Export CSV',
  'estadisticas.exportar.pdf': 'Print / PDF',
  'agenda.titulo': 'Agenda',
  'agenda.filtro.dia': 'Day',
  'agenda.filtro.semana': 'Week',
  'agenda.filtro.mes': 'Month',
  'agenda.anterior': 'Previous',
  'agenda.siguiente': 'Next',
  'agenda.hoy': 'Today',
  'agenda.sinHora': 'All day',
  'agenda.sinTareas': 'No tasks in this period.',
  'agenda.masTareas': '+{cantidad} more',
  'ajustes.titulo': 'Settings',
  'ajustes.google.titulo': 'Google Calendar',
  'ajustes.google.descripcion':
    'Sync your tasks with a due date and your completed Pomodoro sessions with your Google Calendar, in both directions.',
  'ajustes.google.conectar': 'Connect with Google',
  'ajustes.google.desconectar': 'Disconnect',
  'ajustes.google.conectado': 'Account connected',
  'ajustes.google.noConectado': 'Not connected',
  'ajustes.google.ultimaSincronizacion': 'Last synced: {fecha}',
  'ajustes.google.nunca': 'never',
  'ajustes.google.sincronizarAhora': 'Sync now',
  'ajustes.google.sincronizando': 'Syncing…',
  'ajustes.google.autoSyncInfo':
    'While this tab stays open and connected, sync will also repeat automatically every few minutes.',
  'ajustes.google.resumen':
    '{creados} created, {actualizados} updated, {eliminados} deleted, {importados} imported from Google.',
  'ajustes.google.conectadoOk': 'Google account connected successfully.',
  'ajustes.google.errorConexion': 'Could not complete the connection with Google.',
  'ajustes.google.noConfigurado':
    'Google Calendar sync is not configured on the server yet.',
  'ajustes.google.errores':
    '{cantidad, plural, one {# event could not be synced with Google Calendar.} other {# events could not be synced with Google Calendar.}}',
  'nav.principal': 'Main navigation',
  'nav.abrirMenu': 'Open menu',
  'nav.cerrarMenu': 'Close menu',
  'nav.seccion.planificar': 'Plan',
  'nav.seccion.concentrarse': 'Focus',
  'nav.seccion.revisar': 'Review',
  'nav.inicio': 'Home',
  'nav.objetivos': 'Goals',
  'nav.agenda': 'Agenda',
  'nav.kanban': 'Kanban',
  'nav.eisenhower': 'Eisenhower',
  'nav.pomodoro': 'Pomodoro',
  'nav.revision': 'Weekly review',
  'nav.estadisticas': 'Statistics',
  'nav.ajustes': 'Settings',
  'consentimiento.pendiente.titulo': 'Your account is waiting for confirmation',
  'consentimiento.pendiente.explicacion': "Because you're under 18, we've emailed your parent or legal guardian so they can confirm you may use FocusFlow. As soon as they confirm, you can get started.",
  'consentimiento.pendiente.comprobar': 'They have confirmed it',
  'consentimiento.pendiente.reenviar': 'Resend the email',
  'consentimiento.pendiente.reenviado': 'Email resent. Ask your guardian to check their inbox.',
  'consentimiento.pendiente.errorReenvio': "Couldn't resend the email",
  'consentimiento.confirmar.titulo': 'Consent confirmation',
  'consentimiento.confirmar.confirmando': 'Confirming…',
  'consentimiento.confirmar.exito': 'Thank you! The account is now confirmed and FocusFlow can be used normally.',
  'consentimiento.confirmar.error': "Couldn't confirm the account",
  'consentimiento.confirmar.sinToken': 'This link is not valid: the confirmation code is missing.',
  'nav.planificador': 'School planner',
  'tarea.detalle.tipoEscolar': 'Type',
  'tipoEscolar.ninguno': 'No type',
  'tipoEscolar.examen': 'Exam',
  'tipoEscolar.examen.plural': 'Exams',
  'tipoEscolar.trabajo': 'Assignment',
  'tipoEscolar.trabajo.plural': 'Assignments',
  'tipoEscolar.presentacion': 'Presentation',
  'tipoEscolar.presentacion.plural': 'Presentations',
  'planificador.titulo': 'School planner',
  'planificador.descripcion': 'Your upcoming exams, assignments and presentations, sorted by date.',
  'planificador.nueva.titulo': 'Add an exam or assignment',
  'planificador.nueva.tituloPlaceholder': 'e.g. Unit 3 exam',
  'planificador.nueva.boton': 'Add to planner',
  'planificador.filtro': 'Filter by type',
  'planificador.filtro.todos': 'All',
  'planificador.seccion.vencidas': 'Overdue ({cantidad})',
  'planificador.seccion.estaSemana': 'Next 7 days ({cantidad})',
  'planificador.seccion.masAdelante': 'Later ({cantidad})',
  'planificador.seccion.sinFecha': 'No date ({cantidad})',
  'planificador.seccion.vacia': 'Nothing here.',
  'planificador.vacio': 'You have no pending exams, assignments or presentations. Add the first one!',
  'planificador.marcarHecha': 'Mark “{titulo}” as done',
  'ajustes.modoEscolar.titulo': 'School mode',
  'ajustes.modoEscolar.descripcion':
    'Adds the scope selector (Personal/School) and the planner for exams, assignments and presentations, so you can keep school separate from everything else. Turning it off deletes nothing: you simply see all your tasks together again.',
  'ajustes.modoEscolar.activar': 'Turn on school mode',
  'nav.horario': 'Class timetable',
  'horario.titulo': 'Class timetable',
  'horario.cabecera': 'Class timetable',
  'horario.subtitulo': '{curso} · School year {periodo} · {comunidad}',
  'horario.curso': '{etapa}, year {numero}',
  'horario.etapa.PRIMARIA': 'Primary',
  'horario.etapa.ESO': 'Secondary (ESO)',
  'horario.etapa.BACHILLERATO': 'Bachillerato',
  'horario.columnaHora': 'Time',
  'horario.descanso': 'Break',
  'horario.celda': '{dia}, {hora}: {asignatura}',
  'horario.celdaVacia': 'empty',
  'horario.celda.sinAsignaturas': 'First add subjects to the timetable (“Subjects” panel, below).',
  'horario.celda.elegir': 'Subject',
  'horario.celda.aula': 'Room (optional)',
  'horario.celda.vaciar': 'Clear',
  'horario.guardar': 'Save',
  'horario.guardado': 'Saved.',
  'horario.editar': 'Edit',
  'horario.terminar': 'Done',
  'horario.editarAyuda': 'Tap a cell to set or change its subject.',
  'horario.franjas.titulo': 'Times and breaks',
  'horario.franjas.ayuda': 'Adjust the times to your school: one or two breaks, or a split day with lunch and afternoon classes.',
  'horario.franjas.inicio': 'Start of slot {numero}',
  'horario.franjas.fin': 'End of slot {numero}',
  'horario.franjas.tipo': 'Type of slot {numero}',
  'horario.franjas.etiqueta': 'Name of break {numero}',
  'horario.franjas.clase': 'Class',
  'horario.franjas.recreo': 'Break',
  'horario.franjas.subir': 'Move slot {numero} up',
  'horario.franjas.bajar': 'Move slot {numero} down',
  'horario.franjas.quitar': 'Remove slot {numero}',
  'horario.franjas.error': 'Each slot must start before it ends.',
  'horario.franjas.anadirClase': '+ Class',
  'horario.franjas.anadirDescanso': '+ Break',
  'horario.franjas.guardar': 'Save times',
  'horario.asignaturas.titulo': 'Subjects',
  'horario.asignaturas.vacio': 'You haven’t added any subjects yet.',
  'horario.asignaturas.color': 'Colour of {asignatura}',
  'horario.asignaturas.quitar': 'Remove {asignatura}',
  'horario.asignaturas.catalogo': 'Add from the curriculum…',
  'horario.asignaturas.anadir': 'Add',
  'horario.asignaturas.optativaPropia': 'Another subject or elective (e.g. Chess)',
  'horario.asignaturas.errorOptativa': 'Couldn’t add the subject',
  'horario.categoria.OBLIGATORIA': 'Compulsory',
  'horario.categoria.AUTONOMICA': 'Regional language',
  'horario.categoria.DE_OPCION': 'Options',
  'horario.categoria.OPTATIVA': 'Electives',
  'horario.categoria.PROPIA': 'Added by you',
  'horario.datos.tituloSeccion': 'Timetable details',
  'horario.datos.titulo': 'Class group',
  'horario.datos.tituloEjemplo': 'e.g. 3B',
  'horario.datos.periodo': 'School year',
  'horario.datos.curso': 'Year',
  'horario.datos.comunidad': 'Autonomous community',
  'horario.datos.elegir': 'Choose…',
  'horario.datos.activarNuevo': 'Use this timetable from now on',
  'horario.datos.plantillaAyuda': 'It starts with a 9:00–14:00 day and one break; you can change the times afterwards.',
  'horario.crear': 'Create timetable',
  'horario.crearPrimero': 'Create your class timetable',
  'horario.crearPrimeroAyuda': 'Choose your year and autonomous community to see the curriculum subjects, including your community’s own language.',
  'horario.otros': 'Other timetables',
  'horario.usarEste': 'Use this one',
  'horario.nuevo': 'New timetable',
  'horario.borrar': 'Delete this timetable',
  'horario.borrarConfirmar': 'Yes, delete it',
  'horario.cancelar': 'Cancel',
  'comunidad.ANDALUCIA': 'Andalusia',
  'comunidad.ARAGON': 'Aragon',
  'comunidad.ASTURIAS': 'Asturias',
  'comunidad.BALEARES': 'Balearic Islands',
  'comunidad.CANARIAS': 'Canary Islands',
  'comunidad.CANTABRIA': 'Cantabria',
  'comunidad.CASTILLA_LA_MANCHA': 'Castilla-La Mancha',
  'comunidad.CASTILLA_Y_LEON': 'Castile and León',
  'comunidad.CATALUNA': 'Catalonia',
  'comunidad.COMUNITAT_VALENCIANA': 'Valencian Community',
  'comunidad.EXTREMADURA': 'Extremadura',
  'comunidad.GALICIA': 'Galicia',
  'comunidad.MADRID': 'Madrid',
  'comunidad.MURCIA': 'Region of Murcia',
  'comunidad.NAVARRA': 'Navarre',
  'comunidad.PAIS_VASCO': 'Basque Country',
  'comunidad.LA_RIOJA': 'La Rioja',
  'comunidad.CEUTA': 'Ceuta',
  'comunidad.MELILLA': 'Melilla',
  'tarea.detalle.asignatura': 'Subject',
  'tarea.detalle.sinAsignatura': 'No subject',
  'planificador.sinHorario': 'Create your class timetable to choose the subject',
  'agenda.clase.hasta': 'until {hora}',
  'nav.recordatorios': 'Reminders',
  'nav.avisosSinLeer': '{cantidad, plural, one {# unread notice} other {# unread notices}}',
  'periodo.navidad': 'Christmas holidays',
  'periodo.semana-santa': 'Easter holidays',
  'periodo.verano': 'Summer holidays',
  'periodo.hispanidad': 'Spanish National Day',
  'periodo.inmaculada': 'Immaculate Conception Day',
  'aviso.revision.titulo': 'Weekly homework review',
  'aviso.revision.cuerpo': 'You have {pendientes, plural, one {# pending task} other {# pending tasks}}: {vencidas} overdue and {proximos} due in the next 7 days.',
  'aviso.entrega.titulo': 'Due in {horas} h: {titulo}',
  'aviso.entrega.cuerpo': '“{titulo}” is due {fecha}.',
  'aviso.vacaciones.titulo': '{nombre}: {dias, plural, =0 {starts today} one {starts tomorrow} other {starts in # days}}',
  'aviso.vacaciones.tituloDia': '{nombre}: {dias, plural, =0 {today} one {tomorrow} other {in # days}}',
  'aviso.vacaciones.cuerpo': 'No school from {inicio} to {fin}.',
  'aviso.vacaciones.cuerpoDia': 'No school on {inicio}.',
  'aviso.vacaciones.tareasAntes': '{cantidad, plural, one {You have # task due before then.} other {You have # tasks due before then.}}',
  'aviso.emergencia.titulo': 'Alarm! “{titulo}” has gone {dias, plural, one {# day} other {# days}} without review',
  'aviso.emergencia.cuerpo': 'Review it as soon as possible so it doesn’t slip.',
  'avisos.notificacion.varios': 'You have {cantidad} new notices in FocusFlow',
  'avisos.emergencia.titulo': 'Emergency mode',
  'avisos.emergencia.descripcion': '{cantidad, plural, one {# task has gone days without review.} other {# tasks have gone days without review.}}',
  'avisos.emergencia.diasSinTocar': '{dias, plural, one {# day without review} other {# days without review}}',
  'avisos.emergencia.revisada': 'I’ve reviewed it',
  'avisos.emergencia.irKanban': 'Go to Kanban',
  'avisos.emergencia.posponer': 'Remind me later',
  'recordatorios.titulo': 'Reminders and alarms',
  'recordatorios.comprobarAhora': 'Check now',
  'recordatorios.comprobando': 'Checking…',
  'recordatorios.resultadoComprobacion': '{cantidad, plural, =0 {No new notices.} one {# new notice.} other {# new notices.}}',
  'recordatorios.avisos.titulo': 'Notices',
  'recordatorios.avisos.leerTodos': 'Mark all as read',
  'recordatorios.avisos.vacio': 'You have no notices yet. Create an alarm below to get started.',
  'recordatorios.avisos.enviadoCorreo': 'sent by email',
  'recordatorios.avisos.marcarLeido': 'Mark as read',
  'recordatorios.navegador.titulo': 'Notifications in this browser',
  'recordatorios.navegador.descripcion': 'While FocusFlow is open (even in another tab), notices play a sound and appear as system notifications. When the app is closed, only the ones with email turned on reach you.',
  'recordatorios.navegador.permiso.default': 'Browser notifications are off: the notice will only sound inside the app.',
  'recordatorios.navegador.permiso.granted': 'Browser notifications are on.',
  'recordatorios.navegador.permiso.denied': 'You have blocked FocusFlow notifications. You can allow them in your browser’s site settings.',
  'recordatorios.navegador.permiso.no-disponible': 'This browser doesn’t support notifications.',
  'recordatorios.navegador.activar': 'Turn on notifications',
  'recordatorios.navegador.probarSonido': 'Test sound',
  'recordatorios.navegador.probarAlarma': 'Test alarm',
  'recordatorios.alarmas.titulo': 'Alarms',
  'recordatorios.alarmas.vacio': 'You don’t have any alarms yet.',
  'recordatorios.emergencia.titulo': 'Emergency mode',
  'recordatorios.emergencia.descripcion': 'If a pending task goes {dias, plural, one {# day} other {# days}} without you touching it, an audible alarm goes off (and an email, if you turn it on) so you review it straight away.',
  'recordatorios.emergencia.activar': 'Turn on emergency mode',
  'recordatorios.emergencia.dias': 'Untouched days before it goes off:',
  'recordatorios.porCorreo': 'Also notify me by email',
  'recordatorios.correoNoConfigurado': 'Email sending isn’t set up on the server: for now the notice will only appear in the app.',
  'recordatorios.ia.info': 'Weekly summaries and emergency alarms are written with local AI (Ollama) when it’s available; if it doesn’t respond, the standard text is used.',
  'recordatorios.ia.etiqueta': 'Written with AI',
  'recordatorios.tipo.REVISION_SEMANAL': 'Weekly homework review',
  'recordatorios.tipo.ENTREGA': 'Task deadline',
  'recordatorios.tipo.VACACIONES': 'School holidays and days off',
  'recordatorios.tipo.REVISION_SEMANAL.descripcion': 'Every {dia} at {hora}',
  'recordatorios.tipo.ENTREGA.descripcion': '{horas, plural, one {# hour} other {# hours}} before each deadline',
  'recordatorios.tipo.ENTREGA.descripcionEscolar': '{horas, plural, one {# hour} other {# hours}} before each deadline (school tasks only)',
  'recordatorios.tipo.VACACIONES.descripcion': '{dias, plural, =0 {On the day} one {# day before} other {# days before}} each period without school',
  'recordatorios.activo': 'Active',
  'recordatorios.eliminar': 'Delete alarm',
  'recordatorios.nueva.titulo': 'New alarm',
  'recordatorios.nueva.tipo': 'Alarm type',
  'recordatorios.nueva.dia': 'Day',
  'recordatorios.nueva.hora': 'Time',
  'recordatorios.nueva.horasAntes': 'Hours before the deadline:',
  'recordatorios.nueva.soloEscolar': 'School tasks only',
  'recordatorios.nueva.diasAntes': 'Days before:',
  'recordatorios.nueva.anadir': 'Add alarm',
  'recordatorios.calendario.titulo': '{curso} school calendar',
  'recordatorios.calendario.comunidad': '{comunidad}: classes run from {inicio} to {fin}.',
  'recordatorios.calendario.sinHorario': 'You don’t have an active class timetable, so your region is unknown: only your own days off are taken into account.',
  'recordatorios.calendario.rango': '{inicio} to {fin}',
  'recordatorios.calendario.propios': 'Your days off',
  'recordatorios.calendario.propiosVacio': 'Local holidays or school-specific days off that don’t appear above.',
  'recordatorios.calendario.eliminarPropio': 'Delete {nombre}',
  'recordatorios.calendario.nombre': 'Name',
  'recordatorios.calendario.desde': 'From',
  'recordatorios.calendario.hasta': 'To (optional)',
  'recordatorios.calendario.anadir': 'Add',
  'recordatorios.calendario.fuente': 'Official dates from each regional education department. You add local holidays yourself.',
  'ambito.eventual': 'Occasional',
  'kanban.columna.bajoControl': 'Under control',
  'kanban.columna.pospuesta': 'Postponed',
  'kanban.columna.archivada': 'Archived',
  'tarea.detalle.estado': 'Status',
  'tarea.detalle.revisor': 'Review',
  'tarea.detalle.sinRevisor': 'Nobody reviews it',
  'tarea.detalle.revisorAyuda': 'When you mark it as done, they will be asked to review it.',
  'revision.estado.PENDIENTE': 'Waiting for review.',
  'revision.estado.APROBADA': 'Review approved.',
  'revision.estado.DEVUELTA': 'Sent back to fix:',
  'revision.insignia.PENDIENTE': 'To review',
  'revision.insignia.APROBADA': 'Approved',
  'revision.insignia.DEVUELTA': 'Sent back',
  'revision.asignadaPor': 'Assigned by {nombre}',
  'aviso.revisionSolicitada.titulo': '{nombre} is waiting for your review',
  'aviso.revisionSolicitada.cuerpo': '{nombre} has finished “{titulo}” and asks you to review it.',
  'aviso.revisionAprobada.titulo': '{nombre} approved “{titulo}”',
  'aviso.revisionAprobada.cuerpo': 'All good.',
  'aviso.revisionDevuelta.titulo': '{nombre} sent back “{titulo}”',
  'aviso.revisionDevuelta.cuerpo': 'Review it and mark it as done again.',
  'nav.familia': 'Family',
  'familia.titulo': 'Family',
  'familia.descripcion': 'Link your account with your parent’s or guardian’s (or with your child’s) to ask for and give task reviews. Reviewers only see the tasks you ask them to review or that they assigned to you, never the rest of your account.',
  'familia.responsables.titulo': 'Who reviews your tasks',
  'familia.responsables.vacio': 'Nobody reviews your tasks yet.',
  'familia.desvincular': 'Unlink',
  'familia.codigo.explicacion': 'To have someone review your tasks, generate a code and give it to them in person: they will enter it in their FocusFlow account. It works once and expires in 48 hours.',
  'familia.codigo.etiqueta': 'Link code',
  'familia.codigo.caduca': 'Expires {fecha}',
  'familia.codigo.otro': 'Generate another code',
  'familia.codigo.generar': 'Generate code',
  'familia.vincular.titulo': 'Review someone else’s tasks',
  'familia.vincular.codigo': 'Code',
  'familia.vincular.boton': 'Link',
  'familia.vincular.ayuda': 'Enter the code your child gave you (they generate it on this same page, from their account).',
  'familia.supervisado.titulo': '{nombre}’s tasks',
  'familia.supervisado.pendientes': '{cantidad, plural, =0 {To review} other {To review (#)}}',
  'familia.supervisado.pendientesVacio': 'Nothing waiting for review.',
  'familia.supervisado.resto': 'Other tasks you review or assigned',
  'familia.revision.comentario': 'What needs fixing?',
  'familia.revision.enviarDevolucion': 'Send back with this comment',
  'familia.revision.cancelar': 'Cancel',
  'familia.revision.aprobar': 'Approve',
  'familia.revision.devolver': 'Send back',
  'familia.asignar.titulo': 'Assign a task',
  'familia.asignar.tarea': 'Task you want to assign',
  'familia.asignar.boton': 'Assign',
  'familia.asignar.ayuda': 'It will appear in their account, and when they finish it you will get a notice to review it.',
  'nav.notas': 'Notes & To-Do',
  'nav.etiquetas': 'Tags',
  'etiquetas.filtro': 'Filter by tag',
  'etiquetas.filtro.todas': 'All tags',
  'etiquetas.primerNivel': 'Top level',
  'etiquetas.titulo': 'Tags and categories',
  'etiquetas.descripcion': 'Organise your tags into categories up to {niveles} levels deep, for example Study › Maths › Calculus. Filtering by a tag also includes the tags under it.',
  'etiquetas.nueva': 'New tag',
  'etiquetas.nombre': 'Name',
  'etiquetas.dentroDe': 'Inside',
  'etiquetas.crear': 'Create',
  'etiquetas.tuyas': 'Your tags',
  'etiquetas.vacio': 'You have no tags yet. Create one above or type it in a task’s details.',
  'etiquetas.renombrar': 'Rename {nombre}',
  'etiquetas.mover': 'Move {nombre} inside',
  'etiquetas.eliminar': 'Delete {nombre}',
  'notas.titulo': 'Notes & To-Do',
  'notas.pestana.notas': 'Notes',
  'notas.pestana.todo': 'To-Do',
  'notas.sinVinculo': 'Not linked',
  'notas.objetivos': 'Goals',
  'notas.tareas': 'Tasks',
  'notas.filtrar': 'Show:',
  'notas.filtrar.todas': 'All',
  'notas.vacio': 'No notes here yet.',
  'notas.todo.vacio': 'No to-dos here yet.',
  'notas.nueva': 'New note',
  'notas.todo.nuevo': 'New to-do',
  'notas.placeholder': 'Write a note…',
  'notas.todo.placeholder': 'What needs doing?',
  'notas.asociarA': 'Link to',
  'notas.conCasilla': 'With checkbox',
  'notas.anadir': 'Add',
  'notas.marcar': 'Mark “{contenido}”',
  'notas.editar': 'Edit note',
  'notas.vinculo.tarea': 'Task: {titulo}',
  'notas.vinculo.objetivo': 'Goal: {titulo}',
  'notas.quitarCasilla': 'Remove checkbox',
  'notas.ponerCasilla': 'Add checkbox',
  'notas.eliminar': 'Delete',
  'ajustes.perfil.titulo': 'Profile',
  'ajustes.perfil.descripcion': 'Choose what you use FocusFlow for: Home adapts to the profiles you tick. You can tick several.',
  'ajustes.perfil.sugeridos': 'Right now the app is using the profiles it suggests based on what you use. Tick or untick to choose them yourself.',
  'perfil.ESTUDIANTE': 'Student',
  'perfil.PROFESIONAL': 'Professional',
  'perfil.PADRE': 'Parent',
  'inicio.perfiles.sugeridos': 'Home designed for: {perfiles} (suggested; <enlace>change it in Settings</enlace>).',
  'inicio.perfiles.elegidos': 'Home designed for: {perfiles} (<enlace>change</enlace>).',
  'inicio.verTodo': 'See all',
  'inicio.verAgenda': 'See agenda',
  'inicio.todos.titulo': 'Pending to-dos',
  'inicio.todos.vacio': 'You have no pending to-dos.',
  'inicio.clases.titulo': 'Today’s classes',
  'inicio.clases.vacio': 'No classes today.',
  'inicio.clases.sinModoEscolar': 'Turn on school mode in Settings to see your classes here.',
  'inicio.clases.sinHorario': 'Create your class timetable to see today’s classes here.',
  'inicio.entregas.titulo': 'Upcoming deadlines',
  'inicio.entregas.vacio': 'You have no pending school deadlines.',
  'inicio.vacaciones.titulo': 'Next holidays',
  'inicio.vacaciones.vacio': 'No holidays in sight (turn on school mode and create your timetable).',
  'inicio.prioridades.titulo': 'Priorities',
  'inicio.prioridades.vacio': 'Nothing urgent and important or high-impact pending.',
  'inicio.pomodoros.titulo': 'Today’s pomodoros',
  'inicio.pomodoros.empezar': 'Start one',
  'inicio.pomodoros.hoy': '{cantidad, plural, =0 {No pomodoros yet today.} one {pomodoro completed today} other {pomodoros completed today}}',
  'inicio.revisiones.titulo': 'Pending reviews',
  'inicio.revisiones.sinVinculo': 'You don’t supervise anyone yet. Link up from Family.',
  'inicio.revisiones.pendientes': '{cantidad, plural, =0 {nothing to review} other {# to review}}',
  'tarea.detalle.notas': '{cantidad, plural, =0 {Notes and to-dos} other {Notes and to-dos (#)}}',
  'tarea.detalle.abrirNotas': 'Open in Notes',
  'tarea.detalle.nuevoTodo': 'New to-do for this task',
  'objetivos.notas': '{cantidad, plural, =0 {📝 Add notes or to-dos} one {📝 # note or to-do} other {📝 # notes and to-dos}}',
};
