export const en = {
  'app.titulo': 'FocusFlow',
  'app.eslogan': 'Organize your goals, focus your time.',
  'bienvenida.mensaje': 'Welcome to FocusFlow!',
  'selector.idioma.etiqueta': 'Language',
  'auth.registro.titulo': 'Create account',
  'auth.registro.nombre': 'Name',
  'auth.registro.correo': 'Email',
  'auth.registro.contrasena': 'Password',
  'auth.registro.boton': 'Sign up',
  'auth.registro.enlaceLogin': 'Already have an account? Sign in',
  'auth.login.titulo': 'Sign in',
  'auth.login.correo': 'Email',
  'auth.login.contrasena': 'Password',
  'auth.login.boton': 'Sign in',
  'auth.login.enlaceRegistro': "Don't have an account? Sign up",
  'auth.cerrarSesion': 'Sign out',
  'auth.bienvenidoUsuario': 'Hi, {nombre}',
  'inicio.irAObjetivos': 'View my goals',
  'objetivos.titulo': 'My goals',
  'objetivos.nuevo.tituloPlaceholder': 'Goal title',
  'objetivos.nuevo.descripcionPlaceholder': 'Description (optional)',
  'objetivos.nuevo.boton': 'Create goal',
  'objetivos.vacio': "You don't have any goals yet. Create the first one!",
  'objetivos.eliminar': 'Delete goal',
  'objetivos.progreso': '{completadas} of {total} tasks',
  'fechaLimite.etiqueta': 'Due date (optional)',
  'inicio.proximos.titulo': 'Next 7 days',
  'inicio.proximos.vacio': 'No tasks with a due date in the next 7 days.',
  'tareas.tituloPlaceholder': 'New task',
  'tareas.anadir': 'Add',
  'tareas.sueltas.titulo': 'Standalone tasks',
  'tareas.eliminar': 'Delete task',
  'tareas.marcarCompletada': 'Mark "{titulo}" as done',
  'tarea.detalle.descripcion': 'Notes',
  'tarea.detalle.recurrencia': 'Repeat',
  'tarea.recurrencia.ninguna': "Doesn't repeat",
  'tarea.recurrencia.diaria': 'Every day',
  'tarea.recurrencia.semanal': 'Every week',
  'tarea.detalle.etiquetas': 'Tags',
  'tarea.detalle.nuevaEtiqueta': 'New tag',
  'tarea.detalle.quitarEtiqueta': 'Remove tag {nombre}',
  'tarea.detalle.subtareas': 'Subtasks ({completadas} of {total})',
  'tarea.detalle.nuevaSubtarea': 'New step',
  'tarea.detalle.tiempoEstimado': 'Estimated time (minutes)',
  'tarea.detalle.tiempoEstimadoPlaceholder': 'e.g. 30',
  'tarea.detalle.tiempoReal': 'Actual time: {minutos} min',
  'tarea.detalle.fechaLimite': 'Due date',
  'tarea.detalle.horaInicio': 'Start time',
  'tarea.detalle.duracion': 'Duration (minutes)',
  'inicio.irAPomodoro': 'Pomodoro timer',
  'pomodoro.fase.trabajo': 'Work',
  'pomodoro.fase.descansoCorto': 'Short break',
  'pomodoro.fase.descansoLargo': 'Long break',
  'pomodoro.ciclo': 'Cycle {actual} of {total}',
  'pomodoro.iniciar': 'Start',
  'pomodoro.pausar': 'Pause',
  'pomodoro.reiniciar': 'Reset',
  'pomodoro.tareaAsociada.etiqueta': 'Associated task (optional)',
  'pomodoro.tareaAsociada.ninguna': 'None',
  'pomodoro.historial.titulo': 'Recent history',
  'pomodoro.historial.vacio': "You haven't completed any session yet.",
  'pomodoro.historial.minutos': '{minutos} min',
  'inicio.irAKanban': 'Kanban board',
  'kanban.titulo': 'Kanban board',
  'kanban.columna.porHacer': 'To do',
  'kanban.columna.enProceso': 'In progress',
  'kanban.columna.hecha': 'Done',
  'kanban.mover.anterior': 'Move to previous column',
  'kanban.mover.siguiente': 'Move to next column',
  'inicio.irAEisenhower': 'Eisenhower matrix',
  'eisenhower.titulo': 'Eisenhower matrix',
  'eisenhower.cuadrante.hacer': 'Do now',
  'eisenhower.cuadrante.planificar': 'Schedule',
  'eisenhower.cuadrante.delegar': 'Delegate',
  'eisenhower.cuadrante.eliminar': 'Delete',
  'eisenhower.marcar.urgente': 'Urgent',
  'eisenhower.marcar.importante': 'Important',
  'eisenhower.autoUrgente': 'Urgent due date',
  'captura.placeholder': "What's on your mind?",
  'captura.boton': 'Capture',
  'inicio.irAEstadisticas': 'Statistics',
  'estadisticas.titulo': 'Statistics',
  'estadisticas.progresoGlobal': 'Overall progress',
  'estadisticas.distribucion.titulo': 'Task distribution',
  'estadisticas.objetivos.titulo': 'Progress by goal',
  'estadisticas.pareto.titulo': 'High-impact tasks (Pareto 80/20)',
  'estadisticas.pareto.leyendaAltoImpacto': 'High impact',
  'estadisticas.pareto.descripcion':
    '{marcadas} of {total} tasks are marked as high impact ({porcentaje}%).',
  'estadisticas.pareto.vacio':
    "You haven't marked any task as high impact yet. Mark them with ★ from the Kanban board.",
  'pareto.marcar': 'Mark as high impact',
  'estadisticas.pomodoro.titulo': 'Pomodoro',
  'estadisticas.pomodoro.hoy': 'Completed today',
  'estadisticas.pomodoro.semana': 'Completed this week',
  'estadisticas.pomodoro.minutosSemana': 'Work minutes this week',
  'estadisticas.pomodoro.vacio': "You haven't completed any work session yet.",
  'estadisticas.racha': '{racha, plural, one {Streak: # day in a row} other {Streak: # days in a row}}',
  'estadisticas.racha.vacia': "You don't have an active streak yet. Start today!",
  'tema.activarOscuro': 'Turn on dark mode',
  'tema.activarClaro': 'Turn on light mode',
  'inicio.irARevision': 'Weekly review',
  'revision.titulo': 'Weekly review',
  'revision.eslogan': "A weekly look at what you've moved forward and what's fallen behind.",
  'revision.vencidas.titulo': 'Overdue tasks',
  'revision.vencidas.vacio': "You don't have any overdue tasks. Well done!",
  'revision.completadas.titulo': 'Completed this week',
  'revision.completadas.vacio': "You haven't completed any task this week.",
  'revision.objetivosSinTocar.titulo': 'Untouched goals',
  'revision.objetivosSinTocar.vacio': 'All your goals have recent activity.',
  'revision.objetivosSinTocar.diasInactivo':
    '{dias, plural, one {No changes for # day} other {No changes for # days}}',
  'revision.sueltas.titulo': 'Standalone tasks to organize',
  'revision.sueltas.vacio': "All organized! You don't have pending standalone tasks.",
  'revision.sueltas.organizar': 'Organize in Goals',
  'estadisticas.actividad.titulo': 'Daily activity',
  'estadisticas.actividad.tooltip': '{cantidad, plural, =0 {No pomodoros} one {# pomodoro} other {# pomodoros}}',
  'estadisticas.actividad.menos': 'Less',
  'estadisticas.actividad.mas': 'More',
  'estadisticas.tiempoComparado.titulo': 'Estimated vs. actual time',
  'estadisticas.tiempoComparado.vacio':
    "Set an estimated time on a task (from its detail view) and log Pomodoro sessions for it to see it compared here.",
  'estadisticas.tiempoComparado.estimado': 'Estimated: {minutos} min',
  'estadisticas.tiempoComparado.real': 'Actual: {minutos} min',
  'estadisticas.exportar.csv': 'Export CSV',
  'estadisticas.exportar.pdf': 'Print / PDF',
  'inicio.irAAgenda': 'Agenda',
  'agenda.titulo': 'Agenda',
  'agenda.filtro.dia': 'Day',
  'agenda.filtro.semana': 'Week',
  'agenda.filtro.mes': 'Month',
  'agenda.anterior': 'Previous',
  'agenda.siguiente': 'Next',
  'agenda.hoy': 'Today',
  'agenda.sinHora': 'All day',
  'agenda.sinTareas': 'No tasks in this period.',
  'agenda.masTareas': '+{cantidad} more',
  'inicio.irAAjustes': 'Settings',
  'ajustes.titulo': 'Settings',
  'ajustes.google.titulo': 'Google Calendar',
  'ajustes.google.descripcion':
    'Sync your tasks with a due date and your completed Pomodoro sessions with your Google Calendar, in both directions.',
  'ajustes.google.conectar': 'Connect with Google',
  'ajustes.google.desconectar': 'Disconnect',
  'ajustes.google.conectado': 'Account connected',
  'ajustes.google.noConectado': 'Not connected',
  'ajustes.google.ultimaSincronizacion': 'Last synced: {fecha}',
  'ajustes.google.nunca': 'never',
  'ajustes.google.sincronizarAhora': 'Sync now',
  'ajustes.google.sincronizando': 'Syncing…',
  'ajustes.google.autoSyncInfo':
    'While this tab stays open and connected, sync will also repeat automatically every few minutes.',
  'ajustes.google.resumen':
    '{creados} created, {actualizados} updated, {eliminados} deleted, {importados} imported from Google.',
  'ajustes.google.conectadoOk': 'Google account connected successfully.',
  'ajustes.google.errorConexion': 'Could not complete the connection with Google.',
  'ajustes.google.noConfigurado':
    'Google Calendar sync is not configured on the server yet.',
  'ajustes.google.errores':
    '{cantidad, plural, one {# event could not be synced with Google Calendar.} other {# events could not be synced with Google Calendar.}}',
};
