export const es = {
  'app.titulo': 'FocusFlow',
  'app.eslogan': 'Organiza tus objetivos, enfoca tu tiempo.',
  'bienvenida.mensaje': '¡Bienvenido a FocusFlow!',
  'selector.idioma.etiqueta': 'Idioma',
  'auth.registro.titulo': 'Crear cuenta',
  'auth.registro.nombre': 'Nombre',
  'auth.registro.correo': 'Correo electrónico',
  'auth.registro.contrasena': 'Contraseña',
  'auth.registro.boton': 'Registrarme',
  'auth.registro.enlaceLogin': '¿Ya tienes cuenta? Inicia sesión',
  'auth.login.titulo': 'Iniciar sesión',
  'auth.login.correo': 'Correo electrónico',
  'auth.login.contrasena': 'Contraseña',
  'auth.login.boton': 'Entrar',
  'auth.login.enlaceRegistro': '¿No tienes cuenta? Regístrate',
  'auth.cerrarSesion': 'Cerrar sesión',
  'auth.bienvenidoUsuario': 'Hola, {nombre}',
  'inicio.irAObjetivos': 'Ver mis objetivos',
  'objetivos.titulo': 'Mis objetivos',
  'objetivos.nuevo.tituloPlaceholder': 'Título del objetivo',
  'objetivos.nuevo.descripcionPlaceholder': 'Descripción (opcional)',
  'objetivos.nuevo.boton': 'Crear objetivo',
  'objetivos.vacio': 'Todavía no tienes objetivos. ¡Crea el primero!',
  'objetivos.eliminar': 'Eliminar objetivo',
  'objetivos.progreso': '{completadas} de {total} tareas',
  'tareas.tituloPlaceholder': 'Nueva tarea',
  'tareas.anadir': 'Añadir',
  'tareas.sueltas.titulo': 'Tareas sueltas',
  'tareas.eliminar': 'Eliminar tarea',
  'tareas.marcarCompletada': 'Marcar "{titulo}" como completada',
  'inicio.irAPomodoro': 'Temporizador Pomodoro',
  'pomodoro.fase.trabajo': 'Trabajo',
  'pomodoro.fase.descansoCorto': 'Descanso corto',
  'pomodoro.fase.descansoLargo': 'Descanso largo',
  'pomodoro.ciclo': 'Ciclo {actual} de {total}',
  'pomodoro.iniciar': 'Iniciar',
  'pomodoro.pausar': 'Pausar',
  'pomodoro.reiniciar': 'Reiniciar',
  'inicio.irAKanban': 'Tablero Kanban',
  'kanban.titulo': 'Tablero Kanban',
  'kanban.columna.porHacer': 'Por hacer',
  'kanban.columna.enProceso': 'En proceso',
  'kanban.columna.hecha': 'Hecha',
  'kanban.mover.anterior': 'Mover a la columna anterior',
  'kanban.mover.siguiente': 'Mover a la columna siguiente',
  'inicio.irAEisenhower': 'Matriz de Eisenhower',
  'eisenhower.titulo': 'Matriz de Eisenhower',
  'eisenhower.cuadrante.hacer': 'Hacer ya',
  'eisenhower.cuadrante.planificar': 'Planificar',
  'eisenhower.cuadrante.delegar': 'Delegar',
  'eisenhower.cuadrante.eliminar': 'Eliminar',
  'eisenhower.marcar.urgente': 'Urgente',
  'eisenhower.marcar.importante': 'Importante',
  'captura.placeholder': '¿Qué tienes en mente?',
  'captura.boton': 'Capturar',
  'inicio.irAEstadisticas': 'Estadísticas',
  'estadisticas.titulo': 'Estadísticas',
  'estadisticas.progresoGlobal': 'Progreso global',
  'estadisticas.distribucion.titulo': 'Distribución de tareas',
  'estadisticas.objetivos.titulo': 'Progreso por objetivo',
  'estadisticas.pareto.titulo': 'Tareas de alto impacto (Pareto 80/20)',
  'estadisticas.pareto.leyendaAltoImpacto': 'Alto impacto',
  'estadisticas.pareto.descripcion':
    '{marcadas} de {total} tareas están marcadas como alto impacto ({porcentaje}%).',
  'estadisticas.pareto.vacio':
    'Aún no has marcado ninguna tarea como de alto impacto. Márcalas con ★ desde el tablero Kanban.',
  'pareto.marcar': 'Marcar como alto impacto',
  'tema.activarOscuro': 'Activar modo oscuro',
  'tema.activarClaro': 'Activar modo claro',
};
