export const es = {
  'app.titulo': 'FocusFlow',
  'app.eslogan': 'Organiza tus objetivos, enfoca tu tiempo.',
  'bienvenida.mensaje': '¡Bienvenido a FocusFlow!',
  'selector.idioma.etiqueta': 'Idioma',
  'auth.registro.titulo': 'Crear cuenta',
  'auth.registro.nombre': 'Nombre',
  'auth.registro.correo': 'Correo electrónico',
  'auth.registro.contrasena': 'Contraseña',
  'auth.registro.fechaNacimiento': 'Fecha de nacimiento',
  'auth.registro.correoTutor': 'Correo de tu padre, madre o tutor legal',
  'auth.registro.correoTutorAyuda':
    'Al ser menor de edad, necesitamos que tu tutor confirme el uso de esta cuenta.',
  'auth.registro.boton': 'Registrarme',
  'auth.registro.enlaceLogin': '¿Ya tienes cuenta? Inicia sesión',
  'auth.login.titulo': 'Iniciar sesión',
  'auth.login.correo': 'Correo electrónico',
  'auth.login.contrasena': 'Contraseña',
  'auth.login.boton': 'Entrar',
  'auth.login.enlaceRegistro': '¿No tienes cuenta? Regístrate',
  'auth.cerrarSesion': 'Cerrar sesión',
  'auth.bienvenidoUsuario': 'Hola, {nombre}',
  'objetivos.titulo': 'Mis objetivos',
  'objetivos.nuevo.tituloPlaceholder': 'Título del objetivo',
  'objetivos.nuevo.descripcionPlaceholder': 'Descripción (opcional)',
  'objetivos.nuevo.boton': 'Crear objetivo',
  'objetivos.vacio': 'Todavía no tienes objetivos. ¡Crea el primero!',
  'objetivos.eliminar': 'Eliminar objetivo',
  'objetivos.progreso': '{completadas} de {total} tareas',
  'fechaLimite.etiqueta': 'Fecha límite (opcional)',
  'inicio.proximos.titulo': 'Próximos 7 días',
  'inicio.proximos.vacio': 'No tienes tareas con fecha límite en los próximos 7 días.',
  'tareas.tituloPlaceholder': 'Nueva tarea',
  'tareas.anadir': 'Añadir',
  'tareas.sueltas.titulo': 'Tareas sueltas',
  'tareas.eliminar': 'Eliminar tarea',
  'tareas.marcarCompletada': 'Marcar "{titulo}" como completada',
  'tarea.detalle.descripcion': 'Notas',
  'tarea.detalle.recurrencia': 'Repetir',
  'tarea.recurrencia.ninguna': 'No se repite',
  'tarea.recurrencia.diaria': 'Cada día',
  'tarea.recurrencia.semanal': 'Cada semana',
  'tarea.detalle.ambito': 'Ámbito',
  'ambito.selector': 'Ámbito',
  'ambito.todos': 'Todo',
  'ambito.personal': 'Personal',
  'ambito.escolar': 'Escolar',
  'tarea.detalle.etiquetas': 'Etiquetas',
  'tarea.detalle.nuevaEtiqueta': 'Nueva etiqueta',
  'tarea.detalle.quitarEtiqueta': 'Quitar etiqueta {nombre}',
  'tarea.detalle.subtareas': 'Subtareas ({completadas} de {total})',
  'tarea.detalle.nuevaSubtarea': 'Nuevo paso',
  'tarea.detalle.tiempoEstimado': 'Tiempo estimado (minutos)',
  'tarea.detalle.tiempoEstimadoPlaceholder': 'p. ej. 30',
  'tarea.detalle.tiempoReal': 'Tiempo real: {minutos} min',
  'tarea.detalle.fechaLimite': 'Fecha límite',
  'tarea.detalle.horaInicio': 'Hora de inicio',
  'tarea.detalle.duracion': 'Duración (minutos)',
  'pomodoro.fase.trabajo': 'Trabajo',
  'pomodoro.fase.descansoCorto': 'Descanso corto',
  'pomodoro.fase.descansoLargo': 'Descanso largo',
  'pomodoro.ciclo': 'Ciclo {actual} de {total}',
  'pomodoro.iniciar': 'Iniciar',
  'pomodoro.pausar': 'Pausar',
  'pomodoro.reiniciar': 'Reiniciar',
  'pomodoro.tareaAsociada.etiqueta': 'Tarea asociada (opcional)',
  'pomodoro.tareaAsociada.ninguna': 'Ninguna',
  'pomodoro.historial.titulo': 'Historial reciente',
  'pomodoro.historial.vacio': 'Todavía no has completado ninguna sesión.',
  'pomodoro.historial.minutos': '{minutos} min',
  'kanban.titulo': 'Tablero Kanban',
  'kanban.columna.porHacer': 'Por hacer',
  'kanban.columna.enProceso': 'En progreso',
  'kanban.columna.hecha': 'Hecha',
  'kanban.mover.anterior': 'Mover a la columna anterior',
  'kanban.mover.siguiente': 'Mover a la columna siguiente',
  'eisenhower.titulo': 'Matriz de Eisenhower',
  'eisenhower.cuadrante.hacer': 'Hacer ya',
  'eisenhower.cuadrante.planificar': 'Planificar',
  'eisenhower.cuadrante.delegar': 'Delegar',
  'eisenhower.cuadrante.eliminar': 'Eliminar',
  'eisenhower.marcar.urgente': 'Urgente',
  'eisenhower.marcar.importante': 'Importante',
  'eisenhower.autoUrgente': 'Urgente por fecha',
  'captura.placeholder': '¿Qué tienes en mente?',
  'captura.boton': 'Capturar',
  'estadisticas.titulo': 'Estadísticas',
  'estadisticas.progresoGlobal': 'Progreso global',
  'estadisticas.distribucion.titulo': 'Distribución de tareas',
  'estadisticas.objetivos.titulo': 'Progreso por objetivo',
  'estadisticas.pareto.titulo': 'Tareas de alto impacto (Pareto 80/20)',
  'estadisticas.pareto.leyendaAltoImpacto': 'Alto impacto',
  'estadisticas.pareto.descripcion':
    '{marcadas} de {total} tareas están marcadas como alto impacto ({porcentaje}%).',
  'estadisticas.pareto.vacio':
    'Aún no has marcado ninguna tarea como de alto impacto. Márcalas con ★ desde el tablero Kanban.',
  'pareto.marcar': 'Marcar como alto impacto',
  'estadisticas.pomodoro.titulo': 'Pomodoro',
  'estadisticas.pomodoro.hoy': 'Completados hoy',
  'estadisticas.pomodoro.semana': 'Completados esta semana',
  'estadisticas.pomodoro.minutosSemana': 'Minutos de trabajo esta semana',
  'estadisticas.pomodoro.vacio': 'Todavía no has completado ninguna sesión de trabajo.',
  'estadisticas.racha': '{racha, plural, one {Racha: # día seguido} other {Racha: # días seguidos}}',
  'estadisticas.racha.vacia': 'Aún no tienes una racha activa. ¡Empieza hoy!',
  'tema.activarOscuro': 'Activar modo oscuro',
  'tema.activarClaro': 'Activar modo claro',
  'revision.titulo': 'Revisión semanal',
  'revision.eslogan': 'Un vistazo semanal a lo que has avanzado y a lo que se ha quedado atrás.',
  'revision.vencidas.titulo': 'Tareas vencidas',
  'revision.vencidas.vacio': 'No tienes tareas vencidas. ¡Bien hecho!',
  'revision.completadas.titulo': 'Completadas esta semana',
  'revision.completadas.vacio': 'No has completado ninguna tarea esta semana.',
  'revision.objetivosSinTocar.titulo': 'Objetivos sin tocar',
  'revision.objetivosSinTocar.vacio': 'Todos tus objetivos tienen movimiento reciente.',
  'revision.objetivosSinTocar.diasInactivo':
    '{dias, plural, one {Sin cambios desde hace # día} other {Sin cambios desde hace # días}}',
  'revision.sueltas.titulo': 'Tareas sueltas por organizar',
  'revision.sueltas.vacio': '¡Todo organizado! No tienes tareas sueltas pendientes.',
  'revision.sueltas.organizar': 'Organizar en Objetivos',
  'estadisticas.actividad.titulo': 'Actividad diaria',
  'estadisticas.actividad.tooltip': '{cantidad, plural, =0 {Sin pomodoros} one {# pomodoro} other {# pomodoros}}',
  'estadisticas.actividad.menos': 'Menos',
  'estadisticas.actividad.mas': 'Más',
  'estadisticas.tiempoComparado.titulo': 'Tiempo estimado vs. real',
  'estadisticas.tiempoComparado.vacio':
    'Pon un tiempo estimado en una tarea (desde su detalle) y regístrale sesiones de Pomodoro para verla comparada aquí.',
  'estadisticas.tiempoComparado.estimado': 'Estimado: {minutos} min',
  'estadisticas.tiempoComparado.real': 'Real: {minutos} min',
  'estadisticas.exportar.csv': 'Exportar CSV',
  'estadisticas.exportar.pdf': 'Imprimir / PDF',
  'agenda.titulo': 'Agenda',
  'agenda.filtro.dia': 'Día',
  'agenda.filtro.semana': 'Semana',
  'agenda.filtro.mes': 'Mes',
  'agenda.anterior': 'Anterior',
  'agenda.siguiente': 'Siguiente',
  'agenda.hoy': 'Hoy',
  'agenda.sinHora': 'Todo el día',
  'agenda.sinTareas': 'No hay tareas en este período.',
  'agenda.masTareas': '+{cantidad} más',
  'ajustes.titulo': 'Ajustes',
  'ajustes.google.titulo': 'Google Calendar',
  'ajustes.google.descripcion':
    'Sincroniza tus tareas con fecha límite y tus sesiones de Pomodoro completadas con tu Google Calendar, en ambas direcciones.',
  'ajustes.google.conectar': 'Conectar con Google',
  'ajustes.google.desconectar': 'Desconectar',
  'ajustes.google.conectado': 'Cuenta conectada',
  'ajustes.google.noConectado': 'No conectado',
  'ajustes.google.ultimaSincronizacion': 'Última sincronización: {fecha}',
  'ajustes.google.nunca': 'nunca',
  'ajustes.google.sincronizarAhora': 'Sincronizar ahora',
  'ajustes.google.sincronizando': 'Sincronizando…',
  'ajustes.google.autoSyncInfo':
    'Mientras esta pestaña esté abierta y conectada, la sincronización también se repetirá automáticamente cada pocos minutos.',
  'ajustes.google.resumen':
    '{creados} creados, {actualizados} actualizados, {eliminados} eliminados, {importados} importados desde Google.',
  'ajustes.google.conectadoOk': 'Cuenta de Google conectada correctamente.',
  'ajustes.google.errorConexion': 'No se pudo completar la conexión con Google.',
  'ajustes.google.noConfigurado':
    'La sincronización con Google Calendar aún no está configurada en el servidor.',
  'ajustes.google.errores':
    '{cantidad, plural, one {# evento no se pudo sincronizar con Google Calendar.} other {# eventos no se pudieron sincronizar con Google Calendar.}}',
  'nav.principal': 'Navegación principal',
  'nav.abrirMenu': 'Abrir menú',
  'nav.cerrarMenu': 'Cerrar menú',
  'nav.seccion.planificar': 'Planificar',
  'nav.seccion.concentrarse': 'Concentrarse',
  'nav.seccion.revisar': 'Revisar',
  'nav.inicio': 'Inicio',
  'nav.objetivos': 'Objetivos',
  'nav.agenda': 'Agenda',
  'nav.kanban': 'Kanban',
  'nav.eisenhower': 'Eisenhower',
  'nav.pomodoro': 'Pomodoro',
  'nav.revision': 'Revisión semanal',
  'nav.estadisticas': 'Estadísticas',
  'nav.ajustes': 'Ajustes',
  'consentimiento.pendiente.titulo': 'Tu cuenta está pendiente de confirmación',
  'consentimiento.pendiente.explicacion': 'Como eres menor de edad, hemos enviado un correo a tu padre, madre o tutor legal para que confirme que puedes usar FocusFlow. En cuanto lo confirme, podrás empezar.',
  'consentimiento.pendiente.comprobar': 'Ya lo ha confirmado',
  'consentimiento.pendiente.reenviar': 'Reenviar el correo',
  'consentimiento.pendiente.reenviado': 'Correo reenviado. Pide a tu tutor que revise su bandeja de entrada.',
  'consentimiento.pendiente.errorReenvio': 'No se pudo reenviar el correo',
  'consentimiento.confirmar.titulo': 'Confirmación de consentimiento',
  'consentimiento.confirmar.confirmando': 'Confirmando…',
  'consentimiento.confirmar.exito': '¡Gracias! La cuenta ya está confirmada y se puede usar FocusFlow con normalidad.',
  'consentimiento.confirmar.error': 'No se pudo confirmar la cuenta',
  'consentimiento.confirmar.sinToken': 'El enlace no es válido: falta el código de confirmación.',
  'nav.planificador': 'Planificador escolar',
  'tarea.detalle.tipoEscolar': 'Tipo',
  'tipoEscolar.ninguno': 'Sin tipo',
  'tipoEscolar.examen': 'Examen',
  'tipoEscolar.examen.plural': 'Exámenes',
  'tipoEscolar.trabajo': 'Trabajo',
  'tipoEscolar.trabajo.plural': 'Trabajos',
  'tipoEscolar.presentacion': 'Presentación',
  'tipoEscolar.presentacion.plural': 'Presentaciones',
  'planificador.titulo': 'Planificador escolar',
  'planificador.descripcion': 'Tus próximos exámenes, trabajos y presentaciones, ordenados por fecha.',
  'planificador.nueva.titulo': 'Añadir examen o entrega',
  'planificador.nueva.tituloPlaceholder': 'p. ej. Examen del tema 3',
  'planificador.nueva.boton': 'Añadir al planificador',
  'planificador.filtro': 'Filtrar por tipo',
  'planificador.filtro.todos': 'Todo',
  'planificador.seccion.vencidas': 'Vencidas ({cantidad})',
  'planificador.seccion.estaSemana': 'Próximos 7 días ({cantidad})',
  'planificador.seccion.masAdelante': 'Más adelante ({cantidad})',
  'planificador.seccion.sinFecha': 'Sin fecha ({cantidad})',
  'planificador.seccion.vacia': 'Nada por aquí.',
  'planificador.vacio': 'No tienes exámenes, trabajos ni presentaciones pendientes. ¡Añade el primero!',
  'planificador.marcarHecha': 'Marcar «{titulo}» como hecho',
  'ajustes.modoEscolar.titulo': 'Modo escolar',
  'ajustes.modoEscolar.descripcion':
    'Añade el selector de ámbito (Personal/Escolar) y el planificador de exámenes, trabajos y presentaciones, para separar la vida escolar del resto. Si lo desactivas no se borra nada: simplemente vuelves a ver todas tus tareas juntas.',
  'ajustes.modoEscolar.activar': 'Activar el modo escolar',
  'nav.horario': 'Horario de clase',
  'horario.titulo': 'Horario de clase',
  'horario.cabecera': 'Horario de clase',
  'horario.subtitulo': '{curso} · Curso {periodo} · {comunidad}',
  'horario.curso': '{numero}º de {etapa}',
  'horario.etapa.PRIMARIA': 'Primaria',
  'horario.etapa.ESO': 'ESO',
  'horario.etapa.BACHILLERATO': 'Bachillerato',
  'horario.columnaHora': 'Hora',
  'horario.descanso': 'Descanso',
  'horario.celda': '{dia}, {hora}: {asignatura}',
  'horario.celdaVacia': 'vacía',
  'horario.celda.sinAsignaturas': 'Primero añade asignaturas al horario (panel «Asignaturas», debajo).',
  'horario.celda.elegir': 'Asignatura',
  'horario.celda.aula': 'Aula (opcional)',
  'horario.celda.vaciar': 'Vaciar',
  'horario.guardar': 'Guardar',
  'horario.guardado': 'Guardado.',
  'horario.editar': 'Editar',
  'horario.terminar': 'Terminar',
  'horario.editarAyuda': 'Pulsa una casilla para poner o cambiar la asignatura.',
  'horario.franjas.titulo': 'Horas y descansos',
  'horario.franjas.ayuda': 'Ajusta las horas a tu centro: puedes tener uno o dos recreos, o jornada partida con la comida y clases por la tarde.',
  'horario.franjas.inicio': 'Inicio de la franja {numero}',
  'horario.franjas.fin': 'Fin de la franja {numero}',
  'horario.franjas.tipo': 'Tipo de la franja {numero}',
  'horario.franjas.etiqueta': 'Nombre del descanso {numero}',
  'horario.franjas.clase': 'Clase',
  'horario.franjas.recreo': 'Recreo',
  'horario.franjas.subir': 'Subir la franja {numero}',
  'horario.franjas.bajar': 'Bajar la franja {numero}',
  'horario.franjas.quitar': 'Quitar la franja {numero}',
  'horario.franjas.error': 'Cada franja tiene que empezar antes de terminar.',
  'horario.franjas.anadirClase': '+ Clase',
  'horario.franjas.anadirDescanso': '+ Descanso',
  'horario.franjas.guardar': 'Guardar horas',
  'horario.asignaturas.titulo': 'Asignaturas',
  'horario.asignaturas.vacio': 'Todavía no has añadido asignaturas.',
  'horario.asignaturas.color': 'Color de {asignatura}',
  'horario.asignaturas.quitar': 'Quitar {asignatura}',
  'horario.asignaturas.catalogo': 'Añadir del currículo…',
  'horario.asignaturas.anadir': 'Añadir',
  'horario.asignaturas.optativaPropia': 'Otra asignatura u optativa (p. ej. Ajedrez)',
  'horario.asignaturas.errorOptativa': 'No se pudo añadir la asignatura',
  'horario.categoria.OBLIGATORIA': 'Obligatorias',
  'horario.categoria.AUTONOMICA': 'Lengua de la comunidad',
  'horario.categoria.DE_OPCION': 'De opción',
  'horario.categoria.OPTATIVA': 'Optativas',
  'horario.categoria.PROPIA': 'Añadidas por ti',
  'horario.datos.tituloSeccion': 'Datos del horario',
  'horario.datos.titulo': 'Grupo',
  'horario.datos.tituloEjemplo': 'p. ej. 3º B',
  'horario.datos.periodo': 'Curso escolar',
  'horario.datos.curso': 'Curso',
  'horario.datos.comunidad': 'Comunidad autónoma',
  'horario.datos.elegir': 'Elige…',
  'horario.datos.activarNuevo': 'Usar este horario a partir de ahora',
  'horario.datos.plantillaAyuda': 'Empezará con una jornada de 9:00 a 14:00 y un recreo; luego puedes cambiar las horas.',
  'horario.crear': 'Crear horario',
  'horario.crearPrimero': 'Crea tu horario de clase',
  'horario.crearPrimeroAyuda': 'Elige tu curso y tu comunidad autónoma para ver las asignaturas del currículo, incluida la lengua propia de tu comunidad.',
  'horario.otros': 'Otros horarios',
  'horario.usarEste': 'Usar este',
  'horario.nuevo': 'Nuevo horario',
  'horario.borrar': 'Borrar este horario',
  'horario.borrarConfirmar': 'Sí, borrarlo',
  'horario.cancelar': 'Cancelar',
  'comunidad.ANDALUCIA': 'Andalucía',
  'comunidad.ARAGON': 'Aragón',
  'comunidad.ASTURIAS': 'Asturias',
  'comunidad.BALEARES': 'Illes Balears',
  'comunidad.CANARIAS': 'Canarias',
  'comunidad.CANTABRIA': 'Cantabria',
  'comunidad.CASTILLA_LA_MANCHA': 'Castilla-La Mancha',
  'comunidad.CASTILLA_Y_LEON': 'Castilla y León',
  'comunidad.CATALUNA': 'Cataluña',
  'comunidad.COMUNITAT_VALENCIANA': 'Comunitat Valenciana',
  'comunidad.EXTREMADURA': 'Extremadura',
  'comunidad.GALICIA': 'Galicia',
  'comunidad.MADRID': 'Madrid',
  'comunidad.MURCIA': 'Región de Murcia',
  'comunidad.NAVARRA': 'Navarra',
  'comunidad.PAIS_VASCO': 'País Vasco',
  'comunidad.LA_RIOJA': 'La Rioja',
  'comunidad.CEUTA': 'Ceuta',
  'comunidad.MELILLA': 'Melilla',
  'tarea.detalle.asignatura': 'Asignatura',
  'tarea.detalle.sinAsignatura': 'Sin asignatura',
  'planificador.sinHorario': 'Crea tu horario de clase para elegir la asignatura',
  'agenda.clase.hasta': 'hasta las {hora}',
  'nav.recordatorios': 'Recordatorios',
  'nav.avisosSinLeer': '{cantidad, plural, one {# aviso sin leer} other {# avisos sin leer}}',
  'periodo.navidad': 'Vacaciones de Navidad',
  'periodo.semana-santa': 'Vacaciones de Semana Santa',
  'periodo.verano': 'Vacaciones de verano',
  'periodo.hispanidad': 'Fiesta Nacional de España',
  'periodo.inmaculada': 'Día de la Inmaculada Concepción',
  'aviso.revision.titulo': 'Revisión semanal de deberes',
  'aviso.revision.cuerpo': 'Tienes {pendientes, plural, one {# tarea pendiente} other {# tareas pendientes}}: {vencidas, plural, one {# vencida} other {# vencidas}} y {proximos, plural, one {# vence} other {# vencen}} en los próximos 7 días.',
  'aviso.entrega.titulo': 'Entrega en {horas} h: {titulo}',
  'aviso.entrega.cuerpo': '«{titulo}» vence el {fecha}.',
  'aviso.vacaciones.titulo': '{nombre}: {dias, plural, =0 {empiezan hoy} one {empiezan mañana} other {empiezan en # días}}',
  'aviso.vacaciones.tituloDia': '{nombre}: {dias, plural, =0 {es hoy} one {es mañana} other {en # días}}',
  'aviso.vacaciones.cuerpo': 'Del {inicio} al {fin} no hay clase.',
  'aviso.vacaciones.cuerpoDia': 'El {inicio} no hay clase.',
  'aviso.vacaciones.tareasAntes': '{cantidad, plural, one {Tienes # tarea que vence antes.} other {Tienes # tareas que vencen antes.}}',
  'aviso.emergencia.titulo': '¡Alarma! «{titulo}» lleva {dias, plural, one {# día} other {# días}} sin revisar',
  'aviso.emergencia.cuerpo': 'Revísala cuanto antes para que no se te escape.',
  'avisos.notificacion.varios': 'Tienes {cantidad} avisos nuevos en FocusFlow',
  'avisos.emergencia.titulo': 'Modo emergencia',
  'avisos.emergencia.descripcion': '{cantidad, plural, one {Hay # tarea que lleva días sin revisar.} other {Hay # tareas que llevan días sin revisar.}}',
  'avisos.emergencia.diasSinTocar': '{dias, plural, one {# día sin revisar} other {# días sin revisar}}',
  'avisos.emergencia.revisada': 'Ya la he revisado',
  'avisos.emergencia.irKanban': 'Ir al Kanban',
  'avisos.emergencia.posponer': 'Recordármelo más tarde',
  'recordatorios.titulo': 'Recordatorios y alarmas',
  'recordatorios.comprobarAhora': 'Comprobar ahora',
  'recordatorios.comprobando': 'Comprobando…',
  'recordatorios.resultadoComprobacion': '{cantidad, plural, =0 {No hay avisos nuevos.} one {# aviso nuevo.} other {# avisos nuevos.}}',
  'recordatorios.avisos.titulo': 'Avisos',
  'recordatorios.avisos.leerTodos': 'Marcar todos como leídos',
  'recordatorios.avisos.vacio': 'Todavía no tienes avisos. Crea una alarma abajo para empezar.',
  'recordatorios.avisos.enviadoCorreo': 'enviado por correo',
  'recordatorios.avisos.marcarLeido': 'Marcar como leído',
  'recordatorios.navegador.titulo': 'Notificaciones en este navegador',
  'recordatorios.navegador.descripcion': 'Con FocusFlow abierto (aunque sea en otra pestaña), los avisos suenan y aparecen como notificación del sistema. Con la app cerrada, solo llegan los que tengan activado el correo.',
  'recordatorios.navegador.permiso.default': 'Las notificaciones del navegador están desactivadas: solo sonará el aviso dentro de la app.',
  'recordatorios.navegador.permiso.granted': 'Las notificaciones del navegador están activadas.',
  'recordatorios.navegador.permiso.denied': 'Has bloqueado las notificaciones de FocusFlow. Puedes permitirlas desde la configuración del sitio en tu navegador.',
  'recordatorios.navegador.permiso.no-disponible': 'Este navegador no admite notificaciones.',
  'recordatorios.navegador.activar': 'Activar notificaciones',
  'recordatorios.navegador.probarSonido': 'Probar sonido',
  'recordatorios.navegador.probarAlarma': 'Probar alarma',
  'recordatorios.alarmas.titulo': 'Alarmas',
  'recordatorios.alarmas.vacio': 'Aún no tienes ninguna alarma.',
  'recordatorios.emergencia.titulo': 'Modo emergencia',
  'recordatorios.emergencia.descripcion': 'Si una tarea pendiente pasa {dias, plural, one {# día} other {# días}} sin que la toques, salta una alarma sonora (y un correo, si lo activas) para que la revises de inmediato.',
  'recordatorios.emergencia.activar': 'Activar el modo emergencia',
  'recordatorios.emergencia.dias': 'Días sin tocar para que salte:',
  'recordatorios.porCorreo': 'Avisarme también por correo',
  'recordatorios.correoNoConfigurado': 'El envío de correo no está configurado en el servidor: de momento el aviso solo aparecerá en la app.',
  'recordatorios.ia.info': 'Los resúmenes semanales y las alarmas de emergencia se redactan con IA local (Ollama) cuando está disponible; si no responde, se usa el texto normal.',
  'recordatorios.ia.etiqueta': 'Redactado con IA',
  'recordatorios.tipo.REVISION_SEMANAL': 'Revisión semanal de deberes',
  'recordatorios.tipo.ENTREGA': 'Entrega de tarea',
  'recordatorios.tipo.VACACIONES': 'Vacaciones y festivos escolares',
  'recordatorios.tipo.REVISION_SEMANAL.descripcion': 'Cada {dia} a las {hora}',
  'recordatorios.tipo.ENTREGA.descripcion': '{horas, plural, one {# hora} other {# horas}} antes de cada fecha límite',
  'recordatorios.tipo.ENTREGA.descripcionEscolar': '{horas, plural, one {# hora} other {# horas}} antes de cada fecha límite (solo tareas escolares)',
  'recordatorios.tipo.VACACIONES.descripcion': '{dias, plural, =0 {El mismo día} one {# día antes} other {# días antes}} de cada periodo sin clase',
  'recordatorios.activo': 'Activa',
  'recordatorios.eliminar': 'Eliminar alarma',
  'recordatorios.nueva.titulo': 'Nueva alarma',
  'recordatorios.nueva.tipo': 'Tipo de alarma',
  'recordatorios.nueva.dia': 'Día',
  'recordatorios.nueva.hora': 'Hora',
  'recordatorios.nueva.horasAntes': 'Horas antes de la entrega:',
  'recordatorios.nueva.soloEscolar': 'Solo tareas escolares',
  'recordatorios.nueva.diasAntes': 'Días antes:',
  'recordatorios.nueva.anadir': 'Añadir alarma',
  'recordatorios.calendario.titulo': 'Calendario escolar {curso}',
  'recordatorios.calendario.comunidad': '{comunidad}: las clases van del {inicio} al {fin}.',
  'recordatorios.calendario.sinHorario': 'No tienes un horario de clase activo, así que no se conoce tu comunidad: solo se tienen en cuenta tus días no lectivos propios.',
  'recordatorios.calendario.rango': 'del {inicio} al {fin}',
  'recordatorios.calendario.propios': 'Tus días no lectivos',
  'recordatorios.calendario.propiosVacio': 'Fiestas locales o días de libre disposición de tu centro que no aparecen arriba.',
  'recordatorios.calendario.eliminarPropio': 'Eliminar {nombre}',
  'recordatorios.calendario.nombre': 'Nombre',
  'recordatorios.calendario.desde': 'Desde',
  'recordatorios.calendario.hasta': 'Hasta (opcional)',
  'recordatorios.calendario.anadir': 'Añadir',
  'recordatorios.calendario.fuente': 'Fechas oficiales de cada consejería de educación. Las fiestas locales las añades tú.',
  'ambito.eventual': 'Eventual',
  'kanban.columna.bajoControl': 'Bajo control',
  'kanban.columna.pospuesta': 'Pospuesta',
  'kanban.columna.archivada': 'Archivada',
  'tarea.detalle.estado': 'Estado',
  'tarea.detalle.revisor': 'Revisión',
  'tarea.detalle.sinRevisor': 'Nadie la revisa',
  'tarea.detalle.revisorAyuda': 'Cuando la marques como hecha, se le pedirá que la revise.',
  'revision.estado.PENDIENTE': 'Esperando la revisión.',
  'revision.estado.APROBADA': 'Revisión aprobada.',
  'revision.estado.DEVUELTA': 'Devuelta para corregir:',
  'revision.insignia.PENDIENTE': 'Por revisar',
  'revision.insignia.APROBADA': 'Aprobada',
  'revision.insignia.DEVUELTA': 'Devuelta',
  'revision.asignadaPor': 'Asignada por {nombre}',
  'aviso.revisionSolicitada.titulo': '{nombre} espera tu revisión',
  'aviso.revisionSolicitada.cuerpo': '{nombre} ha terminado «{titulo}» y te pide que la revises.',
  'aviso.revisionAprobada.titulo': '{nombre} ha aprobado «{titulo}»',
  'aviso.revisionAprobada.cuerpo': 'Todo está bien.',
  'aviso.revisionDevuelta.titulo': '{nombre} te ha devuelto «{titulo}»',
  'aviso.revisionDevuelta.cuerpo': 'Revísala y vuelve a marcarla como hecha.',
  'nav.familia': 'Familia',
  'familia.titulo': 'Familia',
  'familia.descripcion': 'Vincula tu cuenta con la de tu padre, madre o tutor (o con la de tu hijo o hija) para pedir y hacer revisiones de tareas. Quien revisa solo ve las tareas que le pides revisar o que te ha asignado, nunca el resto de tu cuenta.',
  'familia.responsables.titulo': 'Quién revisa tus tareas',
  'familia.responsables.vacio': 'Todavía nadie revisa tus tareas.',
  'familia.desvincular': 'Desvincular',
  'familia.codigo.explicacion': 'Para que alguien revise tus tareas, genera un código y dáselo en persona: tendrá que introducirlo en su cuenta de FocusFlow. Solo sirve una vez y caduca en 48 horas.',
  'familia.codigo.etiqueta': 'Código de vínculo',
  'familia.codigo.caduca': 'Caduca el {fecha}',
  'familia.codigo.otro': 'Generar otro código',
  'familia.codigo.generar': 'Generar código',
  'familia.vincular.titulo': 'Revisar las tareas de otra persona',
  'familia.vincular.codigo': 'Código',
  'familia.vincular.boton': 'Vincular',
  'familia.vincular.ayuda': 'Introduce el código que te ha dado tu hijo o hija (lo genera en esta misma página, desde su cuenta).',
  'familia.supervisado.titulo': 'Tareas de {nombre}',
  'familia.supervisado.pendientes': '{cantidad, plural, =0 {Por revisar} other {Por revisar (#)}}',
  'familia.supervisado.pendientesVacio': 'No hay nada pendiente de revisar.',
  'familia.supervisado.resto': 'Otras tareas que revisas o has asignado',
  'familia.revision.comentario': '¿Qué hay que corregir?',
  'familia.revision.enviarDevolucion': 'Devolver con este comentario',
  'familia.revision.cancelar': 'Cancelar',
  'familia.revision.aprobar': 'Aprobar',
  'familia.revision.devolver': 'Devolver',
  'familia.asignar.titulo': 'Asignar una tarea',
  'familia.asignar.tarea': 'Tarea que quieres asignar',
  'familia.asignar.boton': 'Asignar',
  'familia.asignar.ayuda': 'Aparecerá en su cuenta, y cuando la termine te llegará un aviso para revisarla.',
  'nav.notas': 'Notas y To-Do',
  'nav.etiquetas': 'Etiquetas',
  'etiquetas.filtro': 'Filtrar por etiqueta',
  'etiquetas.filtro.todas': 'Todas las etiquetas',
  'etiquetas.primerNivel': 'Primer nivel',
  'etiquetas.titulo': 'Etiquetas y categorías',
  'etiquetas.descripcion': 'Organiza tus etiquetas en categorías de hasta {niveles} niveles, por ejemplo Estudio › Matemáticas › Cálculo. Al filtrar por una etiqueta se incluyen también las que cuelgan de ella.',
  'etiquetas.nueva': 'Nueva etiqueta',
  'etiquetas.nombre': 'Nombre',
  'etiquetas.dentroDe': 'Dentro de',
  'etiquetas.crear': 'Crear',
  'etiquetas.tuyas': 'Tus etiquetas',
  'etiquetas.vacio': 'Todavía no tienes etiquetas. Crea una arriba o escríbela en el detalle de una tarea.',
  'etiquetas.renombrar': 'Renombrar {nombre}',
  'etiquetas.mover': 'Mover {nombre} dentro de',
  'etiquetas.eliminar': 'Eliminar {nombre}',
  'notas.titulo': 'Notas y To-Do',
  'notas.pestana.notas': 'Notas',
  'notas.pestana.todo': 'To-Do',
  'notas.sinVinculo': 'Sin asociar',
  'notas.objetivos': 'Objetivos',
  'notas.tareas': 'Tareas',
  'notas.filtrar': 'Mostrar:',
  'notas.filtrar.todas': 'Todas',
  'notas.vacio': 'No hay notas aquí todavía.',
  'notas.todo.vacio': 'No hay to-dos aquí todavía.',
  'notas.nueva': 'Nueva nota',
  'notas.todo.nuevo': 'Nuevo to-do',
  'notas.placeholder': 'Escribe una nota…',
  'notas.todo.placeholder': '¿Qué hay que hacer?',
  'notas.asociarA': 'Asociar a',
  'notas.conCasilla': 'Con casilla',
  'notas.anadir': 'Añadir',
  'notas.marcar': 'Marcar «{contenido}»',
  'notas.editar': 'Editar la nota',
  'notas.vinculo.tarea': 'Tarea: {titulo}',
  'notas.vinculo.objetivo': 'Objetivo: {titulo}',
  'notas.quitarCasilla': 'Quitar la casilla',
  'notas.ponerCasilla': 'Añadir casilla',
  'notas.eliminar': 'Eliminar',
  'ajustes.perfil.titulo': 'Perfil',
  'ajustes.perfil.descripcion': 'Elige para qué usas FocusFlow: el Inicio se adapta a los perfiles marcados. Puedes marcar varios.',
  'ajustes.perfil.sugeridos': 'Ahora mismo se usan los perfiles que sugiere la app según lo que utilizas. Marca o desmarca para elegirlos tú.',
  'perfil.ESTUDIANTE': 'Estudiante',
  'perfil.PROFESIONAL': 'Profesional',
  'perfil.PADRE': 'Padre o madre',
  'inicio.perfiles.sugeridos': 'Inicio pensado para: {perfiles} (sugerido; <enlace>cámbialo en Ajustes</enlace>).',
  'inicio.perfiles.elegidos': 'Inicio pensado para: {perfiles} (<enlace>cambiar</enlace>).',
  'inicio.verTodo': 'Ver todo',
  'inicio.verAgenda': 'Ver la agenda',
  'inicio.todos.titulo': 'To-Do pendientes',
  'inicio.todos.vacio': 'No tienes to-dos pendientes.',
  'inicio.clases.titulo': 'Clases de hoy',
  'inicio.clases.vacio': 'Hoy no hay clase.',
  'inicio.clases.sinModoEscolar': 'Activa el modo escolar en Ajustes para ver aquí tus clases.',
  'inicio.clases.sinHorario': 'Crea tu horario de clase para ver aquí las clases de hoy.',
  'inicio.entregas.titulo': 'Próximas entregas',
  'inicio.entregas.vacio': 'No tienes entregas escolares pendientes.',
  'inicio.vacaciones.titulo': 'Próximas vacaciones',
  'inicio.vacaciones.vacio': 'No hay vacaciones a la vista (activa el modo escolar y crea tu horario).',
  'inicio.prioridades.titulo': 'Prioridades',
  'inicio.prioridades.vacio': 'Nada urgente e importante ni de alto impacto pendiente.',
  'inicio.pomodoros.titulo': 'Pomodoros de hoy',
  'inicio.pomodoros.empezar': 'Empezar uno',
  'inicio.pomodoros.hoy': '{cantidad, plural, =0 {Todavía ningún pomodoro hoy.} one {pomodoro completado hoy} other {pomodoros completados hoy}}',
  'inicio.revisiones.titulo': 'Revisiones pendientes',
  'inicio.revisiones.sinVinculo': 'Todavía no supervisas a nadie. Vincúlate desde Familia.',
  'inicio.revisiones.pendientes': '{cantidad, plural, =0 {nada por revisar} one {# por revisar} other {# por revisar}}',
  'tarea.detalle.notas': '{cantidad, plural, =0 {Notas y to-dos} other {Notas y to-dos (#)}}',
  'tarea.detalle.abrirNotas': 'Abrir en Notas',
  'tarea.detalle.nuevoTodo': 'Nuevo to-do para esta tarea',
  'objetivos.notas': '{cantidad, plural, =0 {📝 Añadir notas o to-dos} one {📝 # nota o to-do} other {📝 # notas y to-dos}}',
};
