export const eu = {
  'app.titulo': 'FocusFlow',
  'app.eslogan': 'Antolatu zure helburuak, fokuratu zure denbora.',
  'bienvenida.mensaje': 'Ongi etorri FocusFlow-ra!',
  'selector.idioma.etiqueta': 'Hizkuntza',
  'auth.registro.titulo': 'Kontua sortu',
  'auth.registro.nombre': 'Izena',
  'auth.registro.correo': 'Helbide elektronikoa',
  'auth.registro.contrasena': 'Pasahitza',
  'auth.registro.boton': 'Erregistratu',
  'auth.registro.enlaceLogin': 'Bazara erabiltzailea? Hasi saioa',
  'auth.login.titulo': 'Hasi saioa',
  'auth.login.correo': 'Helbide elektronikoa',
  'auth.login.contrasena': 'Pasahitza',
  'auth.login.boton': 'Sartu',
  'auth.login.enlaceRegistro': 'Ez zara erabiltzailea? Erregistratu',
  'auth.cerrarSesion': 'Saioa itxi',
  'auth.bienvenidoUsuario': 'Kaixo, {nombre}',
  'inicio.irAObjetivos': 'Nire helburuak ikusi',
  'objetivos.titulo': 'Nire helburuak',
  'objetivos.nuevo.tituloPlaceholder': 'Helburuaren izenburua',
  'objetivos.nuevo.descripcionPlaceholder': 'Deskribapena (aukerakoa)',
  'objetivos.nuevo.boton': 'Helburua sortu',
  'objetivos.vacio': 'Oraindik ez duzu helbururik. Sortu lehena!',
  'objetivos.eliminar': 'Helburua ezabatu',
  'objetivos.progreso': '{total}etik {completadas} zeregin',
  'tareas.tituloPlaceholder': 'Zeregin berria',
  'tareas.anadir': 'Gehitu',
  'tareas.sueltas.titulo': 'Zeregin solteak',
  'tareas.eliminar': 'Zeregina ezabatu',
  'tareas.marcarCompletada': '"{titulo}" eginda dagoela markatu',
  'inicio.irAPomodoro': 'Pomodoro tenporizadorea',
  'pomodoro.fase.trabajo': 'Lana',
  'pomodoro.fase.descansoCorto': 'Atseden laburra',
  'pomodoro.fase.descansoLargo': 'Atseden luzea',
  'pomodoro.ciclo': '{total}etik {actual}. zikloa',
  'pomodoro.iniciar': 'Hasi',
  'pomodoro.pausar': 'Pausatu',
  'pomodoro.reiniciar': 'Berrabiarazi',
  'pomodoro.tareaAsociada.etiqueta': 'Lotutako zeregina (aukerakoa)',
  'pomodoro.tareaAsociada.ninguna': 'Bat ere ez',
  'pomodoro.historial.titulo': 'Azken historia',
  'pomodoro.historial.vacio': 'Oraindik ez duzu saiorik osatu.',
  'pomodoro.historial.minutos': '{minutos} min',
  'inicio.irAKanban': 'Kanban taula',
  'kanban.titulo': 'Kanban taula',
  'kanban.columna.porHacer': 'Egiteko',
  'kanban.columna.enProceso': 'Egiten',
  'kanban.columna.hecha': 'Eginda',
  'kanban.mover.anterior': 'Aurreko zutabera eraman',
  'kanban.mover.siguiente': 'Hurrengo zutabera eraman',
  'inicio.irAEisenhower': 'Eisenhower matrizea',
  'eisenhower.titulo': 'Eisenhower matrizea',
  'eisenhower.cuadrante.hacer': 'Egin orain',
  'eisenhower.cuadrante.planificar': 'Planifikatu',
  'eisenhower.cuadrante.delegar': 'Delegatu',
  'eisenhower.cuadrante.eliminar': 'Ezabatu',
  'eisenhower.marcar.urgente': 'Presazkoa',
  'eisenhower.marcar.importante': 'Garrantzitsua',
  'captura.placeholder': 'Zer duzu buruan?',
  'captura.boton': 'Harrapatu',
  'inicio.irAEstadisticas': 'Estatistikak',
  'estadisticas.titulo': 'Estatistikak',
  'estadisticas.progresoGlobal': 'Aurrerapen orokorra',
  'estadisticas.distribucion.titulo': 'Zereginen banaketa',
  'estadisticas.objetivos.titulo': 'Helburuen araberako aurrerapena',
  'estadisticas.pareto.titulo': 'Eragin handiko zereginak (Pareto 80/20)',
  'estadisticas.pareto.leyendaAltoImpacto': 'Eragin handikoa',
  'estadisticas.pareto.descripcion':
    '{total} zereginetik {marcadas} eragin handikoak dira (%{porcentaje}).',
  'estadisticas.pareto.vacio':
    'Oraindik ez duzu eragin handiko zereginik markatu. Markatu ★ erabiliz Kanban taulatik.',
  'pareto.marcar': 'Eragin handikoa den markatu',
  'estadisticas.pomodoro.titulo': 'Pomodoro',
  'estadisticas.pomodoro.hoy': 'Gaur osatutakoak',
  'estadisticas.pomodoro.semana': 'Aste honetan osatutakoak',
  'estadisticas.pomodoro.minutosSemana': 'Aste honetako lan-minutuak',
  'estadisticas.pomodoro.vacio': 'Oraindik ez duzu lan-saiorik osatu.',
  'tema.activarOscuro': 'Modu iluna aktibatu',
  'tema.activarClaro': 'Modu argia aktibatu',
};
