export const eu = {
  'app.titulo': 'FocusFlow',
  'app.eslogan': 'Antolatu zure helburuak, fokuratu zure denbora.',
  'bienvenida.mensaje': 'Ongi etorri FocusFlow-ra!',
  'selector.idioma.etiqueta': 'Hizkuntza',
  'auth.registro.titulo': 'Kontua sortu',
  'auth.registro.nombre': 'Izena',
  'auth.registro.correo': 'Helbide elektronikoa',
  'auth.registro.contrasena': 'Pasahitza',
  'auth.registro.fechaNacimiento': 'Jaiotze-data',
  'auth.registro.correoTutor': 'Zure aita, ama edo legezko tutorearen posta elektronikoa',
  'auth.registro.correoTutorAyuda':
    'Adin txikikoa zarenez, zure tutoreak kontu honen erabilera baieztatu behar du.',
  'auth.registro.boton': 'Erregistratu',
  'auth.registro.enlaceLogin': 'Bazara erabiltzailea? Hasi saioa',
  'auth.login.titulo': 'Hasi saioa',
  'auth.login.correo': 'Helbide elektronikoa',
  'auth.login.contrasena': 'Pasahitza',
  'auth.login.boton': 'Sartu',
  'auth.login.enlaceRegistro': 'Ez zara erabiltzailea? Erregistratu',
  'auth.cerrarSesion': 'Saioa itxi',
  'auth.bienvenidoUsuario': 'Kaixo, {nombre}',
  'objetivos.titulo': 'Nire helburuak',
  'objetivos.nuevo.tituloPlaceholder': 'Helburuaren izenburua',
  'objetivos.nuevo.descripcionPlaceholder': 'Deskribapena (aukerakoa)',
  'objetivos.nuevo.boton': 'Helburua sortu',
  'objetivos.vacio': 'Oraindik ez duzu helbururik. Sortu lehena!',
  'objetivos.eliminar': 'Helburua ezabatu',
  'objetivos.progreso': '{total}etik {completadas} zeregin',
  'fechaLimite.etiqueta': 'Muga-data (aukerakoa)',
  'inicio.proximos.titulo': 'Hurrengo 7 egunak',
  'inicio.proximos.vacio': 'Ez duzu hurrengo 7 egunetan muga-data duen zereginik.',
  'tareas.tituloPlaceholder': 'Zeregin berria',
  'tareas.anadir': 'Gehitu',
  'tareas.sueltas.titulo': 'Zeregin solteak',
  'tareas.eliminar': 'Zeregina ezabatu',
  'tareas.marcarCompletada': '"{titulo}" eginda dagoela markatu',
  'tarea.detalle.descripcion': 'Oharrak',
  'tarea.detalle.recurrencia': 'Errepikatu',
  'tarea.recurrencia.ninguna': 'Ez da errepikatzen',
  'tarea.recurrencia.diaria': 'Egunero',
  'tarea.recurrencia.semanal': 'Astero',
  'tarea.detalle.ambito': 'Eremua',
  'ambito.selector': 'Eremua',
  'ambito.todos': 'Dena',
  'ambito.personal': 'Pertsonala',
  'ambito.escolar': 'Eskolakoa',
  'tarea.detalle.etiquetas': 'Etiketak',
  'tarea.detalle.nuevaEtiqueta': 'Etiketa berria',
  'tarea.detalle.quitarEtiqueta': '{nombre} etiketa kendu',
  'tarea.detalle.subtareas': 'Azpizereginak ({total}etik {completadas})',
  'tarea.detalle.nuevaSubtarea': 'Urrats berria',
  'tarea.detalle.tiempoEstimado': 'Aurreikusitako denbora (minutuak)',
  'tarea.detalle.tiempoEstimadoPlaceholder': 'adib. 30',
  'tarea.detalle.tiempoReal': 'Benetako denbora: {minutos} min',
  'tarea.detalle.fechaLimite': 'Muga-data',
  'tarea.detalle.horaInicio': 'Hasiera-ordua',
  'tarea.detalle.duracion': 'Iraupena (minutuak)',
  'pomodoro.fase.trabajo': 'Lana',
  'pomodoro.fase.descansoCorto': 'Atseden laburra',
  'pomodoro.fase.descansoLargo': 'Atseden luzea',
  'pomodoro.ciclo': '{total}etik {actual}. zikloa',
  'pomodoro.iniciar': 'Hasi',
  'pomodoro.pausar': 'Pausatu',
  'pomodoro.reiniciar': 'Berrabiarazi',
  'pomodoro.tareaAsociada.etiqueta': 'Lotutako zeregina (aukerakoa)',
  'pomodoro.tareaAsociada.ninguna': 'Bat ere ez',
  'pomodoro.historial.titulo': 'Azken historia',
  'pomodoro.historial.vacio': 'Oraindik ez duzu saiorik osatu.',
  'pomodoro.historial.minutos': '{minutos} min',
  'kanban.titulo': 'Kanban taula',
  'kanban.columna.porHacer': 'Egiteko',
  'kanban.columna.enProceso': 'Egiten',
  'kanban.columna.hecha': 'Eginda',
  'kanban.mover.anterior': 'Aurreko zutabera eraman',
  'kanban.mover.siguiente': 'Hurrengo zutabera eraman',
  'eisenhower.titulo': 'Eisenhower matrizea',
  'eisenhower.cuadrante.hacer': 'Egin orain',
  'eisenhower.cuadrante.planificar': 'Planifikatu',
  'eisenhower.cuadrante.delegar': 'Delegatu',
  'eisenhower.cuadrante.eliminar': 'Ezabatu',
  'eisenhower.marcar.urgente': 'Presazkoa',
  'eisenhower.marcar.importante': 'Garrantzitsua',
  'eisenhower.autoUrgente': 'Data dela eta presazkoa',
  'captura.placeholder': 'Zer duzu buruan?',
  'captura.boton': 'Harrapatu',
  'estadisticas.titulo': 'Estatistikak',
  'estadisticas.progresoGlobal': 'Aurrerapen orokorra',
  'estadisticas.distribucion.titulo': 'Zereginen banaketa',
  'estadisticas.objetivos.titulo': 'Helburuen araberako aurrerapena',
  'estadisticas.pareto.titulo': 'Eragin handiko zereginak (Pareto 80/20)',
  'estadisticas.pareto.leyendaAltoImpacto': 'Eragin handikoa',
  'estadisticas.pareto.descripcion':
    '{total} zereginetik {marcadas} eragin handikoak dira (%{porcentaje}).',
  'estadisticas.pareto.vacio':
    'Oraindik ez duzu eragin handiko zereginik markatu. Markatu ★ erabiliz Kanban taulatik.',
  'pareto.marcar': 'Eragin handikoa den markatu',
  'estadisticas.pomodoro.titulo': 'Pomodoro',
  'estadisticas.pomodoro.hoy': 'Gaur osatutakoak',
  'estadisticas.pomodoro.semana': 'Aste honetan osatutakoak',
  'estadisticas.pomodoro.minutosSemana': 'Aste honetako lan-minutuak',
  'estadisticas.pomodoro.vacio': 'Oraindik ez duzu lan-saiorik osatu.',
  'estadisticas.racha': '{racha, plural, one {Segida: egun # jarraian} other {Segida: # egun jarraian}}',
  'estadisticas.racha.vacia': 'Oraindik ez duzu segidarik. Hasi gaur!',
  'tema.activarOscuro': 'Modu iluna aktibatu',
  'tema.activarClaro': 'Modu argia aktibatu',
  'revision.titulo': 'Asteroko berrikuspena',
  'revision.eslogan': 'Aste honetan aurreratu duzunaren eta atzean geratu denaren begirada bat.',
  'revision.vencidas.titulo': 'Epea igarota duten zereginak',
  'revision.vencidas.vacio': 'Ez duzu epea igarota duen zereginik. Ondo egina!',
  'revision.completadas.titulo': 'Aste honetan eginda',
  'revision.completadas.vacio': 'Ez duzu zereginik osatu aste honetan.',
  'revision.objetivosSinTocar.titulo': 'Ukitu gabeko helburuak',
  'revision.objetivosSinTocar.vacio': 'Zure helburu guztiek dute mugimendu berriena.',
  'revision.objetivosSinTocar.diasInactivo':
    '{dias, plural, one {Aldaketarik gabe duela egun # } other {Aldaketarik gabe duela # egun}}',
  'revision.sueltas.titulo': 'Antolatzeko dauden zeregin solteak',
  'revision.sueltas.vacio': 'Dena antolatuta! Ez duzu zeregin solte zain daudenik.',
  'revision.sueltas.organizar': 'Antolatu Helburuetan',
  'estadisticas.actividad.titulo': 'Eguneroko jarduera',
  'estadisticas.actividad.tooltip': '{cantidad, plural, =0 {Pomodororik ez} one {Pomodoro #} other {# pomodoro}}',
  'estadisticas.actividad.menos': 'Gutxiago',
  'estadisticas.actividad.mas': 'Gehiago',
  'estadisticas.tiempoComparado.titulo': 'Aurreikusitako denbora vs. benetakoa',
  'estadisticas.tiempoComparado.vacio':
    'Jarri aurreikusitako denbora zeregin bati (bere xehetasunetik) eta erregistratu Pomodoro saioak hemen konparatuta ikusteko.',
  'estadisticas.tiempoComparado.estimado': 'Aurreikusita: {minutos} min',
  'estadisticas.tiempoComparado.real': 'Benetakoa: {minutos} min',
  'estadisticas.exportar.csv': 'CSV esportatu',
  'estadisticas.exportar.pdf': 'Inprimatu / PDF',
  'agenda.titulo': 'Agenda',
  'agenda.filtro.dia': 'Eguna',
  'agenda.filtro.semana': 'Astea',
  'agenda.filtro.mes': 'Hilabetea',
  'agenda.anterior': 'Aurrekoa',
  'agenda.siguiente': 'Hurrengoa',
  'agenda.hoy': 'Gaur',
  'agenda.sinHora': 'Egun osoa',
  'agenda.sinTareas': 'Ez dago zereginik epe honetan.',
  'agenda.masTareas': '+{cantidad} gehiago',
  'ajustes.titulo': 'Ezarpenak',
  'ajustes.google.titulo': 'Google Calendar',
  'ajustes.google.descripcion':
    'Sinkronizatu muga-data duten zure zereginak eta osatutako Pomodoro saioak zure Google Calendarrekin, bi noranzkoetan.',
  'ajustes.google.conectar': 'Google-rekin konektatu',
  'ajustes.google.desconectar': 'Deskonektatu',
  'ajustes.google.conectado': 'Kontua konektatuta',
  'ajustes.google.noConectado': 'Konektatu gabe',
  'ajustes.google.ultimaSincronizacion': 'Azken sinkronizazioa: {fecha}',
  'ajustes.google.nunca': 'inoiz ez',
  'ajustes.google.sincronizarAhora': 'Sinkronizatu orain',
  'ajustes.google.sincronizando': 'Sinkronizatzen…',
  'ajustes.google.autoSyncInfo':
    'Fitxa hau irekita eta konektatuta dagoen bitartean, sinkronizazioa automatikoki errepikatuko da gutxi batzuetan behin ere.',
  'ajustes.google.resumen':
    '{creados} sortuta, {actualizados} eguneratuta, {eliminados} ezabatuta, {importados} Google-tik inportatuta.',
  'ajustes.google.conectadoOk': 'Google kontua ongi konektatu da.',
  'ajustes.google.errorConexion': 'Ezin izan da Google-rekin konexioa osatu.',
  'ajustes.google.noConfigurado':
    'Google Calendar-ekiko sinkronizazioa oraindik ez dago konfiguratuta zerbitzarian.',
  'ajustes.google.errores':
    '{cantidad, plural, one {Gertaera bat ezin izan da Google Calendar-ekin sinkronizatu.} other {# gertaera ezin izan dira Google Calendar-ekin sinkronizatu.}}',
  'nav.principal': 'Nabigazio nagusia',
  'nav.abrirMenu': 'Ireki menua',
  'nav.cerrarMenu': 'Itxi menua',
  'nav.seccion.planificar': 'Planifikatu',
  'nav.seccion.concentrarse': 'Kontzentratu',
  'nav.seccion.revisar': 'Berrikusi',
  'nav.inicio': 'Hasiera',
  'nav.objetivos': 'Helburuak',
  'nav.agenda': 'Agenda',
  'nav.kanban': 'Kanban',
  'nav.eisenhower': 'Eisenhower',
  'nav.pomodoro': 'Pomodoro',
  'nav.revision': 'Asteko berrikuspena',
  'nav.estadisticas': 'Estatistikak',
  'nav.ajustes': 'Ezarpenak',
  'consentimiento.pendiente.titulo': 'Zure kontua berresteko zain dago',
  'consentimiento.pendiente.explicacion': 'Adingabea zarenez, mezu bat bidali diogu zure aita, ama edo legezko tutoreari, FocusFlow erabil dezakezula berresteko. Berresten duenean, hasi ahal izango zara.',
  'consentimiento.pendiente.comprobar': 'Dagoeneko berretsi du',
  'consentimiento.pendiente.reenviar': 'Birbidali mezua',
  'consentimiento.pendiente.reenviado': 'Mezua birbidali da. Eskatu zure tutoreari sarrerako ontzia begiratzeko.',
  'consentimiento.pendiente.errorReenvio': 'Ezin izan da mezua birbidali',
  'consentimiento.confirmar.titulo': 'Baimenaren berrespena',
  'consentimiento.confirmar.confirmando': 'Berresten…',
  'consentimiento.confirmar.exito': 'Eskerrik asko! Kontua berretsita dago eta FocusFlow ohi bezala erabil daiteke.',
  'consentimiento.confirmar.error': 'Ezin izan da kontua berretsi',
  'consentimiento.confirmar.sinToken': 'Esteka ez da baliozkoa: berresteko kodea falta da.',
};
