export const gl = {
  'app.titulo': 'FocusFlow',
  'app.eslogan': 'Organiza os teus obxectivos, enfoca o teu tempo.',
  'bienvenida.mensaje': 'Benvido a FocusFlow!',
  'selector.idioma.etiqueta': 'Idioma',
  'auth.registro.titulo': 'Crear conta',
  'auth.registro.nombre': 'Nome',
  'auth.registro.correo': 'Correo electrónico',
  'auth.registro.contrasena': 'Contrasinal',
  'auth.registro.fechaNacimiento': 'Data de nacemento',
  'auth.registro.correoTutor': 'Correo do pai, nai ou titor legal',
  'auth.registro.correoTutorAyuda':
    'Ao seres menor de idade, necesitamos que o teu titor confirme o uso desta conta.',
  'auth.registro.boton': 'Rexistrarme',
  'auth.registro.enlaceLogin': 'Xa tes conta? Inicia sesión',
  'auth.login.titulo': 'Iniciar sesión',
  'auth.login.correo': 'Correo electrónico',
  'auth.login.contrasena': 'Contrasinal',
  'auth.login.boton': 'Entrar',
  'auth.login.enlaceRegistro': 'Non tes conta? Rexístrate',
  'auth.cerrarSesion': 'Pechar sesión',
  'auth.bienvenidoUsuario': 'Ola, {nombre}',
  'objetivos.titulo': 'Os meus obxectivos',
  'objetivos.nuevo.tituloPlaceholder': 'Título do obxectivo',
  'objetivos.nuevo.descripcionPlaceholder': 'Descrición (opcional)',
  'objetivos.nuevo.boton': 'Crear obxectivo',
  'objetivos.vacio': 'Aínda non tes obxectivos. Crea o primeiro!',
  'objetivos.eliminar': 'Eliminar obxectivo',
  'objetivos.progreso': '{completadas} de {total} tarefas',
  'fechaLimite.etiqueta': 'Data límite (opcional)',
  'inicio.proximos.titulo': 'Vindeiros 7 días',
  'inicio.proximos.vacio': 'Non tes tarefas con data límite nos vindeiros 7 días.',
  'tareas.tituloPlaceholder': 'Nova tarefa',
  'tareas.anadir': 'Engadir',
  'tareas.sueltas.titulo': 'Tarefas soltas',
  'tareas.eliminar': 'Eliminar tarefa',
  'tareas.marcarCompletada': 'Marcar "{titulo}" como completada',
  'tarea.detalle.descripcion': 'Notas',
  'tarea.detalle.recurrencia': 'Repetir',
  'tarea.recurrencia.ninguna': 'Non se repite',
  'tarea.recurrencia.diaria': 'Cada día',
  'tarea.recurrencia.semanal': 'Cada semana',
  'tarea.detalle.ambito': 'Ámbito',
  'ambito.selector': 'Ámbito',
  'ambito.todos': 'Todo',
  'ambito.personal': 'Persoal',
  'ambito.escolar': 'Escolar',
  'tarea.detalle.etiquetas': 'Etiquetas',
  'tarea.detalle.nuevaEtiqueta': 'Nova etiqueta',
  'tarea.detalle.quitarEtiqueta': 'Quitar a etiqueta {nombre}',
  'tarea.detalle.subtareas': 'Subtarefas ({completadas} de {total})',
  'tarea.detalle.nuevaSubtarea': 'Novo paso',
  'tarea.detalle.tiempoEstimado': 'Tempo estimado (minutos)',
  'tarea.detalle.tiempoEstimadoPlaceholder': 'p. ex. 30',
  'tarea.detalle.tiempoReal': 'Tempo real: {minutos} min',
  'tarea.detalle.fechaLimite': 'Data límite',
  'tarea.detalle.horaInicio': 'Hora de inicio',
  'tarea.detalle.duracion': 'Duración (minutos)',
  'pomodoro.fase.trabajo': 'Traballo',
  'pomodoro.fase.descansoCorto': 'Descanso curto',
  'pomodoro.fase.descansoLargo': 'Descanso longo',
  'pomodoro.ciclo': 'Ciclo {actual} de {total}',
  'pomodoro.iniciar': 'Iniciar',
  'pomodoro.pausar': 'Pausar',
  'pomodoro.reiniciar': 'Reiniciar',
  'pomodoro.tareaAsociada.etiqueta': 'Tarefa asociada (opcional)',
  'pomodoro.tareaAsociada.ninguna': 'Ningunha',
  'pomodoro.historial.titulo': 'Historial recente',
  'pomodoro.historial.vacio': 'Aínda non completaches ningunha sesión.',
  'pomodoro.historial.minutos': '{minutos} min',
  'kanban.titulo': 'Taboleiro Kanban',
  'kanban.columna.porHacer': 'Por facer',
  'kanban.columna.enProceso': 'En proceso',
  'kanban.columna.hecha': 'Feita',
  'kanban.mover.anterior': 'Mover á columna anterior',
  'kanban.mover.siguiente': 'Mover á columna seguinte',
  'eisenhower.titulo': 'Matriz de Eisenhower',
  'eisenhower.cuadrante.hacer': 'Facer xa',
  'eisenhower.cuadrante.planificar': 'Planificar',
  'eisenhower.cuadrante.delegar': 'Delegar',
  'eisenhower.cuadrante.eliminar': 'Eliminar',
  'eisenhower.marcar.urgente': 'Urxente',
  'eisenhower.marcar.importante': 'Importante',
  'eisenhower.autoUrgente': 'Urxente pola data',
  'captura.placeholder': 'Que tes na mente?',
  'captura.boton': 'Capturar',
  'estadisticas.titulo': 'Estatísticas',
  'estadisticas.progresoGlobal': 'Progreso global',
  'estadisticas.distribucion.titulo': 'Distribución de tarefas',
  'estadisticas.objetivos.titulo': 'Progreso por obxectivo',
  'estadisticas.pareto.titulo': 'Tarefas de alto impacto (Pareto 80/20)',
  'estadisticas.pareto.leyendaAltoImpacto': 'Alto impacto',
  'estadisticas.pareto.descripcion':
    '{marcadas} de {total} tarefas están marcadas coma de alto impacto ({porcentaje}%).',
  'estadisticas.pareto.vacio':
    'Aínda non marcaches ningunha tarefa como de alto impacto. Márcaas con ★ desde o taboleiro Kanban.',
  'pareto.marcar': 'Marcar como alto impacto',
  'estadisticas.pomodoro.titulo': 'Pomodoro',
  'estadisticas.pomodoro.hoy': 'Completados hoxe',
  'estadisticas.pomodoro.semana': 'Completados esta semana',
  'estadisticas.pomodoro.minutosSemana': 'Minutos de traballo esta semana',
  'estadisticas.pomodoro.vacio': 'Aínda non completaches ningunha sesión de traballo.',
  'estadisticas.racha': '{racha, plural, one {Racha: # día seguido} other {Racha: # días seguidos}}',
  'estadisticas.racha.vacia': 'Aínda non tes unha racha activa. Comeza hoxe!',
  'tema.activarOscuro': 'Activar modo escuro',
  'tema.activarClaro': 'Activar modo claro',
  'revision.titulo': 'Revisión semanal',
  'revision.eslogan': 'Unha ollada semanal ao que avanzaches e ao que quedou atrás.',
  'revision.vencidas.titulo': 'Tarefas vencidas',
  'revision.vencidas.vacio': 'Non tes tarefas vencidas. Ben feito!',
  'revision.completadas.titulo': 'Completadas esta semana',
  'revision.completadas.vacio': 'Non completaches ningunha tarefa esta semana.',
  'revision.objetivosSinTocar.titulo': 'Obxectivos sen tocar',
  'revision.objetivosSinTocar.vacio': 'Todos os teus obxectivos teñen movemento recente.',
  'revision.objetivosSinTocar.diasInactivo':
    '{dias, plural, one {Sen cambios desde hai # día} other {Sen cambios desde hai # días}}',
  'revision.sueltas.titulo': 'Tarefas soltas por organizar',
  'revision.sueltas.vacio': 'Todo organizado! Non tes tarefas soltas pendentes.',
  'revision.sueltas.organizar': 'Organizar en Obxectivos',
  'estadisticas.actividad.titulo': 'Actividade diaria',
  'estadisticas.actividad.tooltip': '{cantidad, plural, =0 {Sen pomodoros} one {# pomodoro} other {# pomodoros}}',
  'estadisticas.actividad.menos': 'Menos',
  'estadisticas.actividad.mas': 'Máis',
  'estadisticas.tiempoComparado.titulo': 'Tempo estimado vs. real',
  'estadisticas.tiempoComparado.vacio':
    'Pon un tempo estimado nunha tarefa (desde o seu detalle) e rexístralle sesións de Pomodoro para vela comparada aquí.',
  'estadisticas.tiempoComparado.estimado': 'Estimado: {minutos} min',
  'estadisticas.tiempoComparado.real': 'Real: {minutos} min',
  'estadisticas.exportar.csv': 'Exportar CSV',
  'estadisticas.exportar.pdf': 'Imprimir / PDF',
  'agenda.titulo': 'Axenda',
  'agenda.filtro.dia': 'Día',
  'agenda.filtro.semana': 'Semana',
  'agenda.filtro.mes': 'Mes',
  'agenda.anterior': 'Anterior',
  'agenda.siguiente': 'Seguinte',
  'agenda.hoy': 'Hoxe',
  'agenda.sinHora': 'Todo o día',
  'agenda.sinTareas': 'Non hai tarefas neste período.',
  'agenda.masTareas': '+{cantidad} máis',
  'ajustes.titulo': 'Axustes',
  'ajustes.google.titulo': 'Google (Calendar e Classroom)',
  'ajustes.google.descripcion':
    'Sincroniza as túas tarefas con data límite e as túas sesións de Pomodoro completadas co teu Google Calendar, nos dous sentidos.',
  'ajustes.google.conectar': 'Conectar con Google',
  'ajustes.google.desconectar': 'Desconectar',
  'ajustes.google.conectado': 'Conta conectada',
  'ajustes.google.noConectado': 'Non conectado',
  'ajustes.google.ultimaSincronizacion': 'Última sincronización: {fecha}',
  'ajustes.google.nunca': 'nunca',
  'ajustes.google.sincronizarAhora': 'Sincronizar agora',
  'ajustes.google.sincronizando': 'Sincronizando…',
  'ajustes.google.autoSyncInfo':
    'Mentres esta pestana estea aberta e conectada, a sincronización tamén se repetirá automaticamente cada poucos minutos.',
  'ajustes.google.resumen':
    '{creados} creados, {actualizados} actualizados, {eliminados} eliminados, {importados} importados desde Google.',
  'ajustes.google.conectadoOk': 'Conta de Google conectada correctamente.',
  'ajustes.google.errorConexion': 'Non se puido completar a conexión con Google.',
  'ajustes.google.noConfigurado':
    'A sincronización con Google Calendar aínda non está configurada no servidor.',
  'ajustes.google.errores':
    '{cantidad, plural, one {# evento non se puido sincronizar con Google Calendar.} other {# eventos non se puideron sincronizar con Google Calendar.}}',
  'nav.principal': 'Navegación principal',
  'nav.abrirMenu': 'Abrir o menú',
  'nav.cerrarMenu': 'Pechar o menú',
  'nav.seccion.planificar': 'Planificar',
  'nav.seccion.concentrarse': 'Concentrarse',
  'nav.seccion.revisar': 'Revisar',
  'nav.inicio': 'Inicio',
  'nav.objetivos': 'Obxectivos',
  'nav.agenda': 'Axenda',
  'nav.kanban': 'Kanban',
  'nav.eisenhower': 'Eisenhower',
  'nav.pomodoro': 'Pomodoro',
  'nav.revision': 'Revisión semanal',
  'nav.estadisticas': 'Estatísticas',
  'nav.ajustes': 'Axustes',
  'consentimiento.pendiente.titulo': 'A túa conta está pendente de confirmación',
  'consentimiento.pendiente.explicacion': 'Como es menor de idade, enviamos un correo ao teu pai, nai ou titor legal para que confirme que podes usar FocusFlow. En canto o confirme, poderás comezar.',
  'consentimiento.pendiente.comprobar': 'Xa o confirmou',
  'consentimiento.pendiente.reenviar': 'Reenviar o correo',
  'consentimiento.pendiente.reenviado': 'Correo reenviado. Pídelle ao teu titor que revise a caixa de entrada.',
  'consentimiento.pendiente.errorReenvio': 'Non se puido reenviar o correo',
  'consentimiento.pendiente.viaFamilia': 'O teu pai, nai ou titor ten conta en FocusFlow? Xera un código e dállo en persoa: cando o introduza na súa páxina Familia, a túa conta quedará confirmada ao momento. Só serve unha vez e caduca en 48 horas.',
  'consentimiento.pendiente.generarCodigo': 'Xerar código',
  'consentimiento.pendiente.errorCodigo': 'Non se puido xerar o código',
  'consentimiento.confirmar.titulo': 'Confirmación do consentimento',
  'consentimiento.confirmar.confirmando': 'Confirmando…',
  'consentimiento.confirmar.exito': 'Grazas! A conta xa está confirmada e pódese usar FocusFlow con normalidade.',
  'consentimiento.confirmar.error': 'Non se puido confirmar a conta',
  'consentimiento.confirmar.sinToken': 'A ligazón non é válida: falta o código de confirmación.',
  'verificacion.aviso.texto': 'Confirma o teu correo: enviámosche unha ligazón a {correo}.',
  'verificacion.aviso.reenviar': 'Reenviar o correo',
  'verificacion.aviso.reenviado': 'Correo reenviado. Se non o ves, mira tamén no spam.',
  'verificacion.aviso.comprobar': 'Xa o confirmei',
  'verificacion.aviso.errorReenvio': 'Non se puido reenviar o correo',
  'verificacion.pagina.titulo': 'Verificación do correo',
  'verificacion.pagina.verificando': 'Verificando…',
  'verificacion.pagina.exito': 'Listo! O teu correo xa está verificado.',
  'verificacion.pagina.error': 'Non se puido verificar o correo',
  'verificacion.pagina.sinToken': 'A ligazón non é válida: falta o código de verificación.',
  'nav.planificador': 'Planificador escolar',
  'tarea.detalle.tipoEscolar': 'Tipo',
  'tipoEscolar.ninguno': 'Sen tipo',
  'tipoEscolar.examen': 'Exame',
  'tipoEscolar.examen.plural': 'Exames',
  'tipoEscolar.trabajo': 'Traballo',
  'tipoEscolar.trabajo.plural': 'Traballos',
  'tipoEscolar.presentacion': 'Presentación',
  'tipoEscolar.presentacion.plural': 'Presentacións',
  'tipoEscolar.deberes': 'Deberes',
  'tipoEscolar.deberes.plural': 'Deberes',
  'planificador.titulo': 'Planificador escolar',
  'planificador.descripcion': 'Os teus próximos exames, traballos e presentacións, ordenados por data.',
  'planificador.nueva.titulo': 'Engadir exame ou entrega',
  'planificador.nueva.tituloPlaceholder': 'p. ex. Exame do tema 3',
  'planificador.nueva.boton': 'Engadir ao planificador',
  'planificador.filtro': 'Filtrar por tipo',
  'planificador.filtro.todos': 'Todo',
  'planificador.seccion.vencidas': 'Vencidas ({cantidad})',
  'planificador.seccion.estaSemana': 'Próximos 7 días ({cantidad})',
  'planificador.seccion.masAdelante': 'Máis adiante ({cantidad})',
  'planificador.seccion.sinFecha': 'Sen data ({cantidad})',
  'planificador.seccion.vacia': 'Nada por aquí.',
  'planificador.vacio': 'Non tes exames, traballos nin presentacións pendentes. Engade o primeiro!',
  'planificador.marcarHecha': 'Marcar «{titulo}» como feito',
  'ajustes.modoEscolar.titulo': 'Modo escolar',
  'ajustes.modoEscolar.descripcion':
    'Engade o selector de ámbito (Persoal/Escolar) e o planificador de exames, traballos e presentacións, para separar a vida escolar do resto. Se o desactivas non se borra nada: simplemente volves ver todas as tarefas xuntas.',
  'ajustes.modoEscolar.activar': 'Activar o modo escolar',
  'nav.horario': 'Horario de clase',
  'horario.titulo': 'Horario de clase',
  'horario.cabecera': 'Horario de clase',
  'horario.subtitulo': '{curso} · Curso {periodo} · {comunidad}',
  'horario.curso': '{numero}º de {etapa}',
  'horario.etapa.PRIMARIA': 'Primaria',
  'horario.etapa.ESO': 'ESO',
  'horario.etapa.BACHILLERATO': 'Bacharelato',
  'horario.columnaHora': 'Hora',
  'horario.descanso': 'Descanso',
  'horario.celda': '{dia}, {hora}: {asignatura}',
  'horario.celdaVacia': 'baleira',
  'horario.celda.sinAsignaturas': 'Primeiro engade materias ao horario (panel «Materias», debaixo).',
  'horario.celda.elegir': 'Materia',
  'horario.celda.aula': 'Aula (opcional)',
  'horario.celda.vaciar': 'Baleirar',
  'horario.guardar': 'Gardar',
  'horario.guardado': 'Gardado.',
  'horario.editar': 'Editar',
  'horario.terminar': 'Rematar',
  'horario.editarAyuda': 'Preme unha casa para pór ou cambiar a materia.',
  'horario.franjas.titulo': 'Horas e descansos',
  'horario.franjas.ayuda': 'Axusta as horas ao teu centro: podes ter un ou dous recreos, ou xornada partida co xantar e clases pola tarde.',
  'horario.franjas.inicio': 'Inicio da franxa {numero}',
  'horario.franjas.fin': 'Fin da franxa {numero}',
  'horario.franjas.tipo': 'Tipo da franxa {numero}',
  'horario.franjas.etiqueta': 'Nome do descanso {numero}',
  'horario.franjas.clase': 'Clase',
  'horario.franjas.recreo': 'Recreo',
  'horario.franjas.subir': 'Subir a franxa {numero}',
  'horario.franjas.bajar': 'Baixar a franxa {numero}',
  'horario.franjas.quitar': 'Quitar a franxa {numero}',
  'horario.franjas.error': 'Cada franxa ten que comezar antes de rematar.',
  'horario.franjas.anadirClase': '+ Clase',
  'horario.franjas.anadirDescanso': '+ Descanso',
  'horario.franjas.guardar': 'Gardar horas',
  'horario.asignaturas.titulo': 'Materias',
  'horario.asignaturas.vacio': 'Aínda non engadiches materias.',
  'horario.asignaturas.color': 'Cor de {asignatura}',
  'horario.asignaturas.quitar': 'Quitar {asignatura}',
  'horario.asignaturas.catalogo': 'Engadir do currículo…',
  'horario.asignaturas.anadir': 'Engadir',
  'horario.asignaturas.optativaPropia': 'Outra materia ou optativa (p. ex. Xadrez)',
  'horario.asignaturas.errorOptativa': 'Non se puido engadir a materia',
  'horario.categoria.OBLIGATORIA': 'Obrigatorias',
  'horario.categoria.AUTONOMICA': 'Lingua da comunidade',
  'horario.categoria.DE_OPCION': 'De opción',
  'horario.categoria.OPTATIVA': 'Optativas',
  'horario.categoria.PROPIA': 'Engadidas por ti',
  'horario.datos.tituloSeccion': 'Datos do horario',
  'horario.datos.titulo': 'Grupo',
  'horario.datos.tituloEjemplo': 'p. ex. 3º B',
  'horario.datos.periodo': 'Curso escolar',
  'horario.datos.curso': 'Curso',
  'horario.datos.comunidad': 'Comunidade autónoma',
  'horario.datos.elegir': 'Escolle…',
  'horario.datos.activarNuevo': 'Usar este horario a partir de agora',
  'horario.datos.plantillaAyuda': 'Comezará cunha xornada de 9:00 a 14:00 e un recreo; despois podes cambiar as horas.',
  'horario.crear': 'Crear horario',
  'horario.crearPrimero': 'Crea o teu horario de clase',
  'horario.crearPrimeroAyuda': 'Escolle o teu curso e a túa comunidade autónoma para ver as materias do currículo, incluída a lingua propia da túa comunidade.',
  'horario.otros': 'Outros horarios',
  'horario.usarEste': 'Usar este',
  'horario.nuevo': 'Novo horario',
  'horario.borrar': 'Borrar este horario',
  'horario.borrarConfirmar': 'Si, borralo',
  'horario.cancelar': 'Cancelar',
  'comunidad.ANDALUCIA': 'Andalucía',
  'comunidad.ARAGON': 'Aragón',
  'comunidad.ASTURIAS': 'Asturias',
  'comunidad.BALEARES': 'Illes Balears',
  'comunidad.CANARIAS': 'Canarias',
  'comunidad.CANTABRIA': 'Cantabria',
  'comunidad.CASTILLA_LA_MANCHA': 'Castela-A Mancha',
  'comunidad.CASTILLA_Y_LEON': 'Castela e León',
  'comunidad.CATALUNA': 'Cataluña',
  'comunidad.COMUNITAT_VALENCIANA': 'Comunidade Valenciana',
  'comunidad.EXTREMADURA': 'Estremadura',
  'comunidad.GALICIA': 'Galicia',
  'comunidad.MADRID': 'Madrid',
  'comunidad.MURCIA': 'Rexión de Murcia',
  'comunidad.NAVARRA': 'Navarra',
  'comunidad.PAIS_VASCO': 'País Vasco',
  'comunidad.LA_RIOJA': 'A Rioxa',
  'comunidad.CEUTA': 'Ceuta',
  'comunidad.MELILLA': 'Melilla',
  'tarea.detalle.asignatura': 'Materia',
  'tarea.detalle.sinAsignatura': 'Sen materia',
  'planificador.sinHorario': 'Crea o teu horario de clase para escoller a materia',
  'agenda.clase.hasta': 'ata as {hora}',
  'nav.recordatorios': 'Recordatorios',
  'nav.avisosSinLeer': '{cantidad, plural, one {# aviso sen ler} other {# avisos sen ler}}',
  'periodo.navidad': 'Vacacións de Nadal',
  'periodo.semana-santa': 'Vacacións de Semana Santa',
  'periodo.verano': 'Vacacións de verán',
  'periodo.hispanidad': 'Festa Nacional de España',
  'periodo.inmaculada': 'Día da Inmaculada Concepción',
  'aviso.revision.titulo': 'Revisión semanal de deberes',
  'aviso.revision.cuerpo': 'Tes {pendientes, plural, one {# tarefa pendente} other {# tarefas pendentes}}: {vencidas, plural, one {# vencida} other {# vencidas}} e {proximos, plural, one {# vence} other {# vencen}} nos próximos 7 días.',
  'aviso.entrega.titulo': 'Entrega en {horas} h: {titulo}',
  'aviso.entrega.cuerpo': '«{titulo}» vence o {fecha}.',
  'aviso.vacaciones.titulo': '{nombre}: {dias, plural, =0 {comezan hoxe} one {comezan mañá} other {comezan en # días}}',
  'aviso.vacaciones.tituloDia': '{nombre}: {dias, plural, =0 {é hoxe} one {é mañá} other {en # días}}',
  'aviso.vacaciones.cuerpo': 'Do {inicio} ao {fin} non hai clase.',
  'aviso.vacaciones.cuerpoDia': 'O {inicio} non hai clase.',
  'aviso.vacaciones.tareasAntes': '{cantidad, plural, one {Tes # tarefa que vence antes.} other {Tes # tarefas que vencen antes.}}',
  'aviso.emergencia.titulo': 'Alarma! «{titulo}» leva {dias, plural, one {# día} other {# días}} sen revisar',
  'aviso.emergencia.cuerpo': 'Revísaa canto antes para que non se che escape.',
  'avisos.notificacion.varios': 'Tes {cantidad} avisos novos en FocusFlow',
  'avisos.emergencia.titulo': 'Modo emerxencia',
  'avisos.emergencia.descripcion': '{cantidad, plural, one {Hai # tarefa que leva días sen revisar.} other {Hai # tarefas que levan días sen revisar.}}',
  'avisos.emergencia.diasSinTocar': '{dias, plural, one {# día sen revisar} other {# días sen revisar}}',
  'avisos.emergencia.revisada': 'Xa a revisei',
  'avisos.emergencia.irKanban': 'Ir ao Kanban',
  'avisos.emergencia.posponer': 'Lembrarmo máis tarde',
  'recordatorios.titulo': 'Recordatorios e alarmas',
  'recordatorios.comprobarAhora': 'Comprobar agora',
  'recordatorios.comprobando': 'Comprobando…',
  'recordatorios.resultadoComprobacion': '{cantidad, plural, =0 {Non hai avisos novos.} one {# aviso novo.} other {# avisos novos.}}',
  'recordatorios.avisos.titulo': 'Avisos',
  'recordatorios.avisos.leerTodos': 'Marcar todos como lidos',
  'recordatorios.avisos.vacio': 'Aínda non tes avisos. Crea unha alarma aquí abaixo para comezar.',
  'recordatorios.avisos.enviadoCorreo': 'enviado por correo',
  'recordatorios.avisos.marcarLeido': 'Marcar como lido',
  'recordatorios.navegador.titulo': 'Notificacións neste navegador',
  'recordatorios.navegador.descripcion': 'Con FocusFlow aberto (aínda que sexa noutra lapela), os avisos soan e aparecen como notificación do sistema. Coa aplicación pechada, só chegan os que teñan activado o correo.',
  'recordatorios.navegador.permiso.default': 'As notificacións do navegador están desactivadas: só soará o aviso dentro da aplicación.',
  'recordatorios.navegador.permiso.granted': 'As notificacións do navegador están activadas.',
  'recordatorios.navegador.permiso.denied': 'Bloqueaches as notificacións de FocusFlow. Podes permitilas desde a configuración do sitio no navegador.',
  'recordatorios.navegador.permiso.no-disponible': 'Este navegador non admite notificacións.',
  'recordatorios.navegador.activar': 'Activar as notificacións',
  'recordatorios.navegador.probarSonido': 'Probar o son',
  'recordatorios.navegador.probarAlarma': 'Probar a alarma',
  'recordatorios.alarmas.titulo': 'Alarmas',
  'recordatorios.alarmas.vacio': 'Aínda non tes ningunha alarma.',
  'recordatorios.emergencia.titulo': 'Modo emerxencia',
  'recordatorios.emergencia.descripcion': 'Se unha tarefa pendente pasa {dias, plural, one {# día} other {# días}} sen que a toques, salta unha alarma sonora (e un correo, se o activas) para que a revises de inmediato.',
  'recordatorios.emergencia.activar': 'Activar o modo emerxencia',
  'recordatorios.emergencia.dias': 'Días sen tocar para que salte:',
  'recordatorios.porCorreo': 'Avisarme tamén por correo',
  'recordatorios.correoNoConfigurado': 'O envío de correo non está configurado no servidor: de momento o aviso só aparecerá na aplicación.',
  'recordatorios.ia.info': 'Os resumos semanais e as alarmas de emerxencia redáctanse con IA local (Ollama) cando está dispoñible; se non responde, úsase o texto normal.',
  'recordatorios.ia.etiqueta': 'Redactado con IA',
  'recordatorios.tipo.REVISION_SEMANAL': 'Revisión semanal de deberes',
  'recordatorios.tipo.ENTREGA': 'Entrega de tarefa',
  'recordatorios.tipo.VACACIONES': 'Vacacións e festivos escolares',
  'recordatorios.tipo.REVISION_SEMANAL.descripcion': 'Cada {dia} ás {hora}',
  'recordatorios.tipo.ENTREGA.descripcion': '{horas, plural, one {# hora} other {# horas}} antes de cada data límite',
  'recordatorios.tipo.ENTREGA.descripcionEscolar': '{horas, plural, one {# hora} other {# horas}} antes de cada data límite (só tarefas escolares)',
  'recordatorios.tipo.VACACIONES.descripcion': '{dias, plural, =0 {O mesmo día} one {# día antes} other {# días antes}} de cada período sen clase',
  'recordatorios.activo': 'Activa',
  'recordatorios.eliminar': 'Eliminar a alarma',
  'recordatorios.nueva.titulo': 'Nova alarma',
  'recordatorios.nueva.tipo': 'Tipo de alarma',
  'recordatorios.nueva.dia': 'Día',
  'recordatorios.nueva.hora': 'Hora',
  'recordatorios.nueva.horasAntes': 'Horas antes da entrega:',
  'recordatorios.nueva.soloEscolar': 'Só tarefas escolares',
  'recordatorios.nueva.diasAntes': 'Días antes:',
  'recordatorios.nueva.anadir': 'Engadir a alarma',
  'recordatorios.calendario.titulo': 'Calendario escolar {curso}',
  'recordatorios.calendario.comunidad': '{comunidad}: as clases van do {inicio} ao {fin}.',
  'recordatorios.calendario.sinHorario': 'Non tes un horario de clase activo, así que non se coñece a túa comunidade: só se teñen en conta os teus días non lectivos propios.',
  'recordatorios.calendario.rango': 'do {inicio} ao {fin}',
  'recordatorios.calendario.propios': 'Os teus días non lectivos',
  'recordatorios.calendario.propiosVacio': 'Festas locais ou días de libre disposición do teu centro que non aparecen arriba.',
  'recordatorios.calendario.eliminarPropio': 'Eliminar {nombre}',
  'recordatorios.calendario.nombre': 'Nome',
  'recordatorios.calendario.desde': 'Desde',
  'recordatorios.calendario.hasta': 'Ata (opcional)',
  'recordatorios.calendario.anadir': 'Engadir',
  'recordatorios.calendario.fuente': 'Datas oficiais de cada consellería de educación. As festas locais engádelas ti.',
  'ambito.eventual': 'Eventual',
  'kanban.columna.bajoControl': 'Baixo control',
  'kanban.columna.pospuesta': 'Aprazada',
  'kanban.columna.archivada': 'Arquivada',
  'tarea.detalle.estado': 'Estado',
  'tarea.detalle.revisor': 'Revisión',
  'tarea.detalle.sinRevisor': 'Ninguén a revisa',
  'tarea.detalle.revisorAyuda': 'Cando a marques como feita, pedirase que a revise.',
  'revision.estado.PENDIENTE': 'Agardando a revisión.',
  'revision.estado.APROBADA': 'Revisión aprobada.',
  'revision.estado.DEVUELTA': 'Devolta para corrixir:',
  'revision.insignia.PENDIENTE': 'Por revisar',
  'revision.insignia.APROBADA': 'Aprobada',
  'revision.insignia.DEVUELTA': 'Devolta',
  'revision.asignadaPor': 'Asignada por {nombre}',
  'aviso.revisionSolicitada.titulo': '{nombre} agarda a túa revisión',
  'aviso.revisionSolicitada.cuerpo': '{nombre} rematou «{titulo}» e pídeche que a revises.',
  'aviso.revisionAprobada.titulo': '{nombre} aprobou «{titulo}»',
  'aviso.revisionAprobada.cuerpo': 'Todo está ben.',
  'aviso.revisionDevuelta.titulo': '{nombre} devolveuche «{titulo}»',
  'aviso.revisionDevuelta.cuerpo': 'Revísaa e volve marcala como feita.',
  'nav.familia': 'Familia',
  'familia.titulo': 'Familia',
  'familia.descripcion': 'Vincula a túa conta coa do teu pai, nai ou titor (ou coa do teu fillo ou filla) para pedir e facer revisións de tarefas. Quen revisa só ve as tarefas que lle pides revisar ou que che asignou, nunca o resto da túa conta.',
  'familia.responsables.titulo': 'Quen revisa as túas tarefas',
  'familia.responsables.vacio': 'Aínda ninguén revisa as túas tarefas.',
  'familia.desvincular': 'Desvincular',
  'familia.codigo.explicacion': 'Para que alguén revise as túas tarefas, xera un código e dállo en persoa: terá que introducilo na súa conta de FocusFlow. Só serve unha vez e caduca en 48 horas.',
  'familia.codigo.etiqueta': 'Código de vínculo',
  'familia.codigo.caduca': 'Caduca o {fecha}',
  'familia.codigo.otro': 'Xerar outro código',
  'familia.codigo.generar': 'Xerar código',
  'familia.vincular.titulo': 'Revisar as tarefas doutra persoa',
  'familia.vincular.codigo': 'Código',
  'familia.vincular.boton': 'Vincular',
  'familia.vincular.ayuda': 'Introduce o código que che deu o teu fillo ou filla (xérao nesta mesma páxina, desde a súa conta).',
  'familia.vincular.consentimientoConcedido': 'Confirmaches a conta de {nombre}: xa pode usar FocusFlow.',
  'familia.supervisado.titulo': 'Tarefas de {nombre}',
  'familia.supervisado.pendientes': '{cantidad, plural, =0 {Por revisar} other {Por revisar (#)}}',
  'familia.supervisado.pendientesVacio': 'Non hai nada pendente de revisar.',
  'familia.supervisado.resto': 'Outras tarefas que revisas ou asignaches',
  'familia.revision.comentario': 'Que hai que corrixir?',
  'familia.revision.enviarDevolucion': 'Devolver con este comentario',
  'familia.revision.cancelar': 'Cancelar',
  'familia.revision.aprobar': 'Aprobar',
  'familia.revision.devolver': 'Devolver',
  'familia.asignar.titulo': 'Asignar unha tarefa',
  'familia.asignar.tarea': 'Tarefa que queres asignar',
  'familia.asignar.boton': 'Asignar',
  'familia.asignar.ayuda': 'Aparecerá na súa conta, e cando a remate chegarache un aviso para revisala.',
  'nav.notas': 'Notas e To-Do',
  'nav.etiquetas': 'Etiquetas',
  'etiquetas.filtro': 'Filtrar por etiqueta',
  'etiquetas.filtro.todas': 'Todas as etiquetas',
  'etiquetas.primerNivel': 'Primeiro nivel',
  'etiquetas.titulo': 'Etiquetas e categorías',
  'etiquetas.descripcion': 'Organiza as túas etiquetas en categorías de ata {niveles} niveis, por exemplo Estudo › Matemáticas › Cálculo. Ao filtrar por unha etiqueta inclúense tamén as que colgan dela.',
  'etiquetas.nueva': 'Nova etiqueta',
  'etiquetas.nombre': 'Nome',
  'etiquetas.dentroDe': 'Dentro de',
  'etiquetas.crear': 'Crear',
  'etiquetas.tuyas': 'As túas etiquetas',
  'etiquetas.vacio': 'Aínda non tes etiquetas. Crea unha arriba ou escríbea no detalle dunha tarefa.',
  'etiquetas.renombrar': 'Renomear {nombre}',
  'etiquetas.mover': 'Mover {nombre} dentro de',
  'etiquetas.eliminar': 'Eliminar {nombre}',
  'notas.titulo': 'Notas e To-Do',
  'notas.pestana.notas': 'Notas',
  'notas.pestana.todo': 'To-Do',
  'notas.sinVinculo': 'Sen asociar',
  'notas.objetivos': 'Obxectivos',
  'notas.tareas': 'Tarefas',
  'notas.filtrar': 'Amosar:',
  'notas.filtrar.todas': 'Todas',
  'notas.vacio': 'Aínda non hai notas aquí.',
  'notas.todo.vacio': 'Aínda non hai to-dos aquí.',
  'notas.nueva': 'Nova nota',
  'notas.todo.nuevo': 'Novo to-do',
  'notas.placeholder': 'Escribe unha nota…',
  'notas.todo.placeholder': 'Que hai que facer?',
  'notas.asociarA': 'Asociar a',
  'notas.conCasilla': 'Con caixa',
  'notas.anadir': 'Engadir',
  'notas.marcar': 'Marcar «{contenido}»',
  'notas.editar': 'Editar a nota',
  'notas.vinculo.tarea': 'Tarefa: {titulo}',
  'notas.vinculo.objetivo': 'Obxectivo: {titulo}',
  'notas.quitarCasilla': 'Quitar a caixa',
  'notas.ponerCasilla': 'Engadir caixa',
  'notas.eliminar': 'Eliminar',
  'ajustes.perfil.titulo': 'Perfil',
  'ajustes.perfil.descripcion': 'Escolle para que usas FocusFlow: o Inicio adáptase aos perfís marcados. Podes marcar varios.',
  'ajustes.perfil.sugeridos': 'Agora mesmo úsanse os perfís que suxire a aplicación segundo o que utilizas. Marca ou desmarca para escollelos ti.',
  'perfil.ESTUDIANTE': 'Estudante',
  'perfil.PROFESIONAL': 'Profesional',
  'perfil.PADRE': 'Pai ou nai',
  'inicio.perfiles.sugeridos': 'Inicio pensado para: {perfiles} (suxerido; <enlace>cámbiao en Axustes</enlace>).',
  'inicio.perfiles.elegidos': 'Inicio pensado para: {perfiles} (<enlace>cambiar</enlace>).',
  'inicio.verTodo': 'Ver todo',
  'inicio.verAgenda': 'Ver a axenda',
  'inicio.todos.titulo': 'To-Do pendentes',
  'inicio.todos.vacio': 'Non tes to-dos pendentes.',
  'inicio.clases.titulo': 'Clases de hoxe',
  'inicio.clases.vacio': 'Hoxe non hai clase.',
  'inicio.clases.sinModoEscolar': 'Activa o modo escolar en Axustes para ver aquí as túas clases.',
  'inicio.clases.sinHorario': 'Crea o teu horario de clase para ver aquí as clases de hoxe.',
  'inicio.entregas.titulo': 'Próximas entregas',
  'inicio.entregas.vacio': 'Non tes entregas escolares pendentes.',
  'inicio.vacaciones.titulo': 'Próximas vacacións',
  'inicio.vacaciones.vacio': 'Non hai vacacións á vista (activa o modo escolar e crea o teu horario).',
  'inicio.prioridades.titulo': 'Prioridades',
  'inicio.prioridades.vacio': 'Nada urxente e importante nin de alto impacto pendente.',
  'inicio.pomodoros.titulo': 'Pomodoros de hoxe',
  'inicio.pomodoros.empezar': 'Comezar un',
  'inicio.pomodoros.hoy': '{cantidad, plural, =0 {Aínda ningún pomodoro hoxe.} one {pomodoro completado hoxe} other {pomodoros completados hoxe}}',
  'inicio.revisiones.titulo': 'Revisións pendentes',
  'inicio.revisiones.sinVinculo': 'Aínda non supervisas a ninguén. Vincúlate desde Familia.',
  'inicio.revisiones.pendientes': '{cantidad, plural, =0 {nada por revisar} one {# por revisar} other {# por revisar}}',
  'tarea.detalle.notas': '{cantidad, plural, =0 {Notas e to-dos} other {Notas e to-dos (#)}}',
  'tarea.detalle.abrirNotas': 'Abrir en Notas',
  'tarea.detalle.nuevoTodo': 'Novo to-do para esta tarefa',
  'objetivos.notas': '{cantidad, plural, =0 {📝 Engadir notas ou to-dos} one {📝 # nota ou to-do} other {📝 # notas e to-dos}}',
  'busqueda.abrir': 'Buscar',
  'busqueda.titulo': 'Buscar en FocusFlow',
  'busqueda.placeholder': 'Tarefas, subtarefas, obxectivos, notas, etiquetas…',
  'busqueda.minimo': 'Escribe polo menos 2 letras. Non importan os acentos nin as maiúsculas.',
  'busqueda.sinResultados': 'Non hai nada que coincida con «{consulta}».',
  'busqueda.grupo.tareas': 'Tarefas',
  'busqueda.grupo.objetivos': 'Obxectivos',
  'busqueda.grupo.notas': 'Notas e To-Do',
  'busqueda.grupo.etiquetas': 'Etiquetas',
  'busqueda.enSubtarea': 'Na subtarefa: {titulo}',
  'busqueda.tipo.nota': 'Nota',
  'busqueda.tipo.todo': 'To-Do',
  'busqueda.verEtiqueta': 'Ver as súas tarefas no Kanban',
  'estadisticas.porCategoria.tituloEtiqueta': 'Tempo de concentración por etiqueta',
  'estadisticas.porCategoria.tituloAsignatura': 'Tempo de concentración por materia',
  'estadisticas.porCategoria.agrupar': 'Agrupar por',
  'estadisticas.porCategoria.etiquetas': 'Etiquetas',
  'estadisticas.porCategoria.asignaturas': 'Materias',
  'estadisticas.porCategoria.periodo': 'Período',
  'estadisticas.porCategoria.semana': '7 días',
  'estadisticas.porCategoria.mes': '30 días',
  'estadisticas.porCategoria.siempre': 'Sempre',
  'estadisticas.porCategoria.vacio': 'Aínda non hai pomodoros de traballo neste período.',
  'estadisticas.porCategoria.total': 'Total de concentración: {duracion}.',
  'estadisticas.porCategoria.horasMinutos': '{horas} h {minutos} min',
  'estadisticas.porCategoria.minutos': '{minutos} min',
  'estadisticas.porCategoria.sinEtiqueta': 'Tarefas sen etiqueta',
  'estadisticas.porCategoria.sinAsignatura': 'Tarefas sen materia',
  'estadisticas.porCategoria.sinTarea': 'Pomodoros sen tarefa',
  'estadisticas.porCategoria.notaVariasEtiquetas': 'Unha tarefa con varias etiquetas suma o seu tempo en todas elas.',
  'ajustes.push.titulo': 'Avisos neste dispositivo',
  'ajustes.push.descripcion': 'Recibe os recordatorios, as alarmas e as revisións como notificación do móbil ou do ordenador, aínda que FocusFlow estea pechado. Actívase en cada dispositivo por separado.',
  'ajustes.push.activar': 'Activar avisos neste dispositivo',
  'ajustes.push.desactivar': 'Desactivar',
  'ajustes.push.probar': 'Enviar aviso de proba',
  'ajustes.push.pruebaEnviada': 'Aviso de proba enviado: debería aparecer nuns segundos.',
  'ajustes.push.activo': 'Activados neste dispositivo.',
  'ajustes.push.noSoportado': 'Este navegador non permite avisos coa app pechada. No iPhone ou iPad, primeiro engade FocusFlow á pantalla de inicio (Compartir → Engadir á pantalla de inicio) e ábreo desde alí.',
  'ajustes.push.noConfigurado': 'O servidor aínda non ten configurados os avisos coa app pechada.',
  'ajustes.push.bloqueado': 'As notificacións de FocusFlow están bloqueadas neste navegador. Permíteas desde o cadeado xunto ao enderezo e volve entrar en Axustes.',
  'ajustes.push.error': 'Non se puideron cambiar os avisos deste dispositivo',
  'ajustes.push.instalar': 'Consello: instala FocusFlow como unha app máis desde o menú do navegador (Instalar aplicación ou Engadir á pantalla de inicio).',
  'error.CORREO_O_CONTRASENA_INCORRECTOS': 'Correo ou contrasinal incorrectos',
  'error.USUARIO_YA_EXISTE': 'Xa existe un usuario con ese correo',
  'error.USUARIO_NO_ENCONTRADO': 'Non se atopou o usuario',
  'error.CORREO_NO_VALIDO': 'O correo electrónico non é válido',
  'error.CONTRASENA_CORTA': 'O contrasinal debe ter polo menos 8 caracteres',
  'error.CONTRASENA_DEBIL': 'O contrasinal debe incluír maiúsculas, minúsculas e números',
  'error.FECHA_NACIMIENTO_NO_VALIDA': 'A data de nacemento non é válida',
  'error.FALTA_CORREO_TUTOR': 'Precísase o correo dun titor legal para menores de 18 anos',
  'error.CONSENTIMIENTO_PENDIENTE': 'Conta pendente de confirmación dun titor legal',
  'error.ENLACE_CONFIRMACION_NO_VALIDO': 'Ligazón de confirmación caducada ou non válida',
  'error.SIN_CORREO_TUTOR': 'Esta conta non ten un correo de titor rexistrado',
  'error.ESPERA_REENVIO_CORREO': 'Agarda uns minutos antes de volver pedir o correo',
  'error.ENLACE_VERIFICACION_NO_VALIDO': 'Ligazón de verificación caducada ou non válida',
  'error.CORREO_NO_CONFIGURADO': 'O envío de correo non está configurado no servidor',
  'error.TAREA_NO_ENCONTRADA': 'Non se atopou a tarefa',
  'error.SUBTAREA_NO_ENCONTRADA': 'Non se atopou a subtarefa',
  'error.OBJETIVO_NO_ENCONTRADO': 'Non se atopou o obxectivo',
  'error.NOTA_NO_ENCONTRADA': 'Non se atopou a nota',
  'error.TODO_SIEMPRE_CON_CASILLA': 'Un to-do sempre ten caixa',
  'error.ETIQUETA_NO_ENCONTRADA': 'Non se atopou a etiqueta',
  'error.ETIQUETA_YA_EXISTE': 'Xa tes unha etiqueta con ese nome',
  'error.ETIQUETA_DENTRO_DE_SI_MISMA': 'Unha etiqueta non pode ir dentro de si mesma',
  'error.HORARIO_NO_ENCONTRADO': 'Non se atopou o horario',
  'error.CURSO_NO_ENCONTRADO': 'Non se atopou o curso',
  'error.ASIGNATURA_NO_ENCONTRADA': 'Non se atopou a materia',
  'error.ASIGNATURA_NO_ESTA_EN_HORARIO': 'Non se atopou a materia neste horario',
  'error.ASIGNATURA_NO_ESTA_EN_TUS_HORARIOS': 'Non se atopou a materia nos teus horarios',
  'error.ASIGNATURA_NO_ES_DEL_CURSO': 'Non se atopou a materia para o curso deste horario',
  'error.ASIGNATURA_FUERA_DEL_HORARIO': 'Esa materia non está neste horario',
  'error.ASIGNATURA_YA_EN_HORARIO': 'Esa materia xa está no horario',
  'error.SOLO_BORRAR_ASIGNATURAS_PROPIAS': 'Só se poden borrar as materias engadidas por ti',
  'error.FRANJA_NO_ENCONTRADA': 'Non se atopou a franxa neste horario',
  'error.FRANJA_DE_OTRO_HORARIO': 'Unha das franxas non pertence a este horario',
  'error.CLASE_EN_DESCANSO': 'Nunha franxa de descanso non se poden poñer clases',
  'error.RECORDATORIO_NO_ENCONTRADO': 'Non se atopou o recordatorio',
  'error.AVISO_NO_ENCONTRADO': 'Non se atopou o aviso',
  'error.DIA_NO_LECTIVO_NO_ENCONTRADO': 'Non se atopou o día non lectivo',
  'error.FECHA_FIN_ANTERIOR': 'A data de fin non pode ser anterior á de inicio',
  'error.CODIGO_VINCULO_NO_VALIDO': 'O código non é válido ou caducou',
  'error.VINCULO_CON_UNO_MISMO': 'Non podes vincularte coa túa propia conta',
  'error.YA_VINCULADOS': 'Xa estades vinculados',
  'error.CODIGO_NO_GENERADO': 'Non se puido xerar un código, téntao de novo',
  'error.VINCULO_NO_ENCONTRADO': 'Non se atopou o vínculo',
  'error.PERSONA_NO_VINCULADA': 'Esa persoa non está vinculada contigo',
  'error.REVISION_NO_PENDIENTE': 'Esta tarefa non está pendente de revisión',
  'error.SOLO_ADULTO_AUTORIZA': 'Só unha persoa adulta pode autorizar a conta dun menor',
  'error.GOOGLE_NO_CONFIGURADO': 'A sincronización con Google Calendar non está configurada no servidor',
  'error.GOOGLE_NO_CONECTADO': 'Esta conta non está conectada con Google Calendar',
  'error.ENLACE_GOOGLE_NO_VALIDO': 'Ligazón de conexión con Google caducada ou non válida',
  'error.NO_AUTENTICADO': 'A túa sesión caducou. Volve iniciar sesión.',
  'error.SIN_PERMISO': 'Non tes permiso para facer isto',
  'error.NO_ENCONTRADO': 'Non se atopou o que buscabas',
  'error.SIN_CONEXION': 'Non se puido conectar co servidor. Comproba a túa conexión.',
  'error.ERROR_INTERNO': 'Produciuse un erro no servidor. Téntao de novo máis tarde.',
  'error.ERROR_DESCONOCIDO': 'Produciuse un erro inesperado',
  'error.IA_NO_DISPONIBLE': 'A IA non está dispoñible agora mesmo',
  'error.PLAN_SIN_IA': 'A axuda da IA está incluída no plan Plus',
  'error.LIMITE_IA_ALCANZADO': 'Chegaches ao límite de usos da IA deste mes',
  'error.FOTO_NO_VALIDA': 'Sube unha foto (JPG, PNG ou WEBP) de menos de 5 MB',
  'error.IA_RESPUESTA_NO_VALIDA': 'A IA non deu unha proposta válida, téntao de novo',
  'error.TAREA_SIN_FECHA_LIMITE': 'Ponlle unha data límite á tarefa para poder planificar o estudo',
  'error.PLAN_SIN_DIAS': 'Non quedan días para estudar antes da data límite',
  'ia.titulo': 'Axuda da IA',
  'ia.dividir': 'Dividir en pasos',
  'ia.plan': 'Plan de estudo ata a data',
  'ia.pensando': 'A IA está pensando… Pode tardar ata un minuto.',
  'ia.error': 'Non se puido obter a proposta da IA',
  'ia.revisaPasos': 'Revisa a proposta: podes cambiar o texto e desmarcar o que non queiras.',
  'ia.revisaPlan': 'Cada sesión engadirase como unha tarefa coa súa data e sairá na Axenda. Podes cambiar o texto e desmarcar o que non queiras.',
  'ia.incluir': 'Incluír «{titulo}»',
  'ia.editar': 'Texto da proposta',
  'ia.minutos': '{minutos} min',
  'ia.anadirPasos': '{cantidad, plural, one {Engadir # subtarefa} other {Engadir # subtarefas}}',
  'ia.anadirPlan': '{cantidad, plural, one {Engadir # sesión} other {Engadir # sesións}}',
  'ia.otraPropuesta': 'Outra proposta',
  'ia.descartar': 'Descartar',
  'ia.anadidas': '{cantidad, plural, one {Engadiuse # elemento.} other {Engadíronse # elementos.}}',
  'ia.plus.titulo': 'A axuda da IA está no plan Plus',
  'ia.plus.explicacion': 'Con Plus, a IA divide as túas tarefas en pasos, prepárache un plan de estudo ata a data do exame e redacta os teus recordatorios. Sempre che propón e ti decides.',
  'ia.plus.proximamente': 'Moi pronto poderás contratalo desde Axustes.',
  'ia.usos': 'Este mes: {usados} de {limite} usos.',
  'fotos.horario.boton': 'Encher desde unha foto',
  'fotos.horario.ayuda': 'Fai unha foto ao horario de clase (ou escolle unha da galería) e a IA pasarao á grella. Antes de gardalo poderás revisalo.',
  'fotos.horario.revisa': 'Revisa o horario que leu a IA. Ao aplicalo substitúese a grella actual; despois podes corrixir calquera cela con «Editar horario».',
  'fotos.horario.aplicar': 'Aplicar ao horario',
  'fotos.horario.aplicado': 'Horario actualizado a partir da foto.',
  'fotos.entregas.boton': 'Engadir desde unha foto',
  'fotos.entregas.ayuda': 'Fai unha foto ao calendario de exames, á axenda ou á circular do colexio e a IA sacará os exames, traballos e presentacións coa súa data.',
  'fotos.entregas.revisa': 'Revisa o que leu a IA: podes cambiar o texto, a data, o tipo e a materia, e desmarcar o que non queiras.',
  'fotos.entregas.anadir': '{cantidad, plural, one {Engadir # entrega} other {Engadir # entregas}}',
  'fotos.entregas.anadidas': '{cantidad, plural, one {Engadiuse # entrega.} other {Engadíronse # entregas.}}',
  'fotos.entregas.incluir': 'Incluír «{titulo}»',
  'fotos.entregas.fecha': 'Data',
  'fotos.entregas.titulo': 'Título',
  'fotos.entregas.tipo': 'Tipo',
  'fotos.entregas.asignatura': 'Materia',
  'fotos.elegir': 'Facer ou escoller unha foto',
  'fotos.leyendo': 'Lendo a foto… Pode tardar uns segundos.',
  'fotos.descartar': 'Descartar',
  'fotos.otraFoto': 'Probar con outra foto',
  'fotos.error': 'Non se puido ler a foto',
  'fotos.sinAsignatura': 'Sen materia',
  'fotos.soloPlus': 'Ler o horario ou os exames desde unha foto está incluído no plan Plus.',
  'planificador.pestana.deberes': 'Deberes',
  'planificador.pestana.entregas': 'Exames e traballos',
  'deberes.nuevo.titulo': 'Apuntar deberes',
  'deberes.nuevo.que': 'Que hai que facer',
  'deberes.nuevo.ejemplo': 'Páxina 34, exercicios 1 a 5',
  'deberes.nuevo.asignatura': 'Materia',
  'deberes.nuevo.fecha': 'Para o',
  'deberes.nuevo.ayuda': 'A data ponse soa: a próxima clase desa materia segundo o horario (sen contar festivos). Podes cambiala.',
  'deberes.nuevo.boton': 'Apuntar',
  'deberes.sinHorario': 'Crea o horario de clase para que a data se poña soa.',
  'deberes.seccion.atrasados': 'Atrasados',
  'deberes.seccion.hoy': 'Para hoxe',
  'deberes.seccion.manana': 'Para mañá',
  'deberes.seccion.masAdelante': 'Máis adiante',
  'deberes.vacio': 'Non hai deberes pendentes. Moi ben!',
  'fotos.deberes.boton': 'Engadir desde unha foto da axenda',
  'fotos.deberes.ayuda': 'Fai unha foto á páxina da axenda e a IA sacará os deberes de cada materia. Se a axenda non di para cando son, ponse a próxima clase.',
  'fotos.deberes.revisa': 'Revisa os deberes: podes cambiar o texto, a materia e a data, e desmarcar o que non queiras.',
  'fotos.deberes.anadir': '{cantidad, plural, one {Engadir # deber} other {Engadir # deberes}}',
  'fotos.deberes.anadidos': '{cantidad, plural, one {Engadiuse # deber.} other {Engadíronse # deberes.}}',
  'ajustes.plan.titulo': 'O teu plan',
  'ajustes.plan.gratuito': 'Gratuíto: todas as funcións de organización, sen a axuda da IA.',
  'ajustes.plan.pago': 'Plus: coa axuda da IA.',
  'ajustes.plan.familiar': 'Plus a través da túa familia: a axuda da IA chégache polo plan do teu pai, nai ou titor.',
  'bienvenida.paso': 'Paso {paso} de {total}',
  'bienvenida.saltar': 'Omitir',
  'bienvenida.siguiente': 'Seguinte',
  'bienvenida.perfil.titulo': 'Ola, {nombre}! Para que vas usar FocusFlow?',
  'bienvenida.perfil.descripcion': 'Marca todo o que encaixe contigo: o Inicio adáptase ao que escollas. Podes cambialo cando queiras en Axustes.',
  'bienvenida.perfil.ESTUDIANTE': 'Deberes, exames, traballos e o teu horario de clase.',
  'bienvenida.perfil.PROFESIONAL': 'Proxectos, obxectivos e concentración con Pomodoro.',
  'bienvenida.perfil.PADRE': 'Revisar as tarefas dos teus fillos e asignarlles tarefas.',
  'bienvenida.escolar.titulo': 'Activamos o modo escolar?',
  'bienvenida.escolar.si': 'Si, activalo',
  'bienvenida.escolar.no': 'Agora non',
  'bienvenida.horario.titulo': 'O teu horario de clase',
  'bienvenida.horario.descripcion': 'Dinos o teu curso e a túa comunidade: a app proporache as materias oficiais e o calendario escolar (vacacións e festivos). Despois poderás encher a grade coas túas clases.',
  'bienvenida.horario.despues': 'Fareino máis tarde',
  'bienvenida.listo.titulo': 'Todo listo!',
  'bienvenida.listo.empezar': 'Comezar',
  'bienvenida.listo.rellenarHorario': 'Encher o meu horario',
  'bienvenida.consejo.captura': 'Apunta calquera cousa ao voo coa barra «Que tes na cabeza?» de abaixo; xa a organizarás despois.',
  'bienvenida.consejo.buscar': 'Busca en todo con Ctrl+K (ou coa lupa, no móbil).',
  'bienvenida.consejo.familia': 'Para revisar as tarefas do teu fillo ou filla, pídelle que xere un código en Familia e escríbeo na túa.',
  'bienvenida.consejo.pomodoro': 'Concéntrate co Pomodoro: 25 minutos de traballo e un descanso. En Estatísticas verás canto tempo dedicas a cada materia.',
  'bienvenida.consejo.avisos': 'En Recordatorios podes crear alarmas para entregas e exames, e en Axustes, activar os avisos no móbil.',
  'error.CLASSROOM_NO_CONECTADO': 'Conecta Google Classroom para importar os teus deberes',
  'error.CLASSROOM_API_DESACTIVADA': 'A API de Google Classroom non está activada no proxecto de Google Cloud',
  'error.CLASSROOM_SIN_PERMISO': 'Google non permite que FocusFlow lea o teu Classroom (pode que o teu centro o teña restrinxido)',
  'classroom.titulo': 'Google Classroom',
  'classroom.descripcion': 'Importa como tarefas escolares os traballos que tes pendentes de entregar nas túas clases, coa data de entrega e a ligazón a Classroom. Se volves importar, non se duplican e actualízase a data se o profesor a cambia.',
  'classroom.conectar': 'Conectar Google Classroom',
  'classroom.conectarTodo': 'Conectar Google e Classroom',
  'classroom.aviso': 'Só pide permiso para ler as túas clases e os teus traballos; nunca escribe en Classroom. Algúns centros non permiten conectar outras apps ás contas do alumnado.',
  'classroom.importar': 'Importar deberes agora',
  'classroom.importando': 'Importando…',
  'classroom.resumen': '{cursos, plural, one {# clase revisada} other {# clases revisadas}}: {nuevas, plural, =0 {ningún traballo novo} one {# traballo novo} other {# traballos novos}} e {actualizadas, plural, =0 {ningún actualizado} one {# actualizado} other {# actualizados}}.',
  'classroom.error': 'Non se puideron importar os traballos de Classroom',
};
