export const gl = {
  'app.titulo': 'FocusFlow',
  'app.eslogan': 'Organiza os teus obxectivos, enfoca o teu tempo.',
  'bienvenida.mensaje': 'Benvido a FocusFlow!',
  'selector.idioma.etiqueta': 'Idioma',
  'auth.registro.titulo': 'Crear conta',
  'auth.registro.nombre': 'Nome',
  'auth.registro.correo': 'Correo electrónico',
  'auth.registro.contrasena': 'Contrasinal',
  'auth.registro.fechaNacimiento': 'Data de nacemento',
  'auth.registro.correoTutor': 'Correo do pai, nai ou titor legal',
  'auth.registro.correoTutorAyuda':
    'Ao seres menor de idade, necesitamos que o teu titor confirme o uso desta conta.',
  'auth.registro.boton': 'Rexistrarme',
  'auth.registro.enlaceLogin': 'Xa tes conta? Inicia sesión',
  'auth.login.titulo': 'Iniciar sesión',
  'auth.login.correo': 'Correo electrónico',
  'auth.login.contrasena': 'Contrasinal',
  'auth.login.boton': 'Entrar',
  'auth.login.enlaceRegistro': 'Non tes conta? Rexístrate',
  'auth.cerrarSesion': 'Pechar sesión',
  'auth.bienvenidoUsuario': 'Ola, {nombre}',
  'objetivos.titulo': 'Os meus obxectivos',
  'objetivos.nuevo.tituloPlaceholder': 'Título do obxectivo',
  'objetivos.nuevo.descripcionPlaceholder': 'Descrición (opcional)',
  'objetivos.nuevo.boton': 'Crear obxectivo',
  'objetivos.vacio': 'Aínda non tes obxectivos. Crea o primeiro!',
  'objetivos.eliminar': 'Eliminar obxectivo',
  'objetivos.progreso': '{completadas} de {total} tarefas',
  'fechaLimite.etiqueta': 'Data límite (opcional)',
  'inicio.proximos.titulo': 'Vindeiros 7 días',
  'inicio.proximos.vacio': 'Non tes tarefas con data límite nos vindeiros 7 días.',
  'tareas.tituloPlaceholder': 'Nova tarefa',
  'tareas.anadir': 'Engadir',
  'tareas.sueltas.titulo': 'Tarefas soltas',
  'tareas.eliminar': 'Eliminar tarefa',
  'tareas.marcarCompletada': 'Marcar "{titulo}" como completada',
  'tarea.detalle.descripcion': 'Notas',
  'tarea.detalle.recurrencia': 'Repetir',
  'tarea.recurrencia.ninguna': 'Non se repite',
  'tarea.recurrencia.diaria': 'Cada día',
  'tarea.recurrencia.semanal': 'Cada semana',
  'tarea.detalle.ambito': 'Ámbito',
  'ambito.selector': 'Ámbito',
  'ambito.todos': 'Todo',
  'ambito.personal': 'Persoal',
  'ambito.escolar': 'Escolar',
  'tarea.detalle.etiquetas': 'Etiquetas',
  'tarea.detalle.nuevaEtiqueta': 'Nova etiqueta',
  'tarea.detalle.quitarEtiqueta': 'Quitar a etiqueta {nombre}',
  'tarea.detalle.subtareas': 'Subtarefas ({completadas} de {total})',
  'tarea.detalle.nuevaSubtarea': 'Novo paso',
  'tarea.detalle.tiempoEstimado': 'Tempo estimado (minutos)',
  'tarea.detalle.tiempoEstimadoPlaceholder': 'p. ex. 30',
  'tarea.detalle.tiempoReal': 'Tempo real: {minutos} min',
  'tarea.detalle.fechaLimite': 'Data límite',
  'tarea.detalle.horaInicio': 'Hora de inicio',
  'tarea.detalle.duracion': 'Duración (minutos)',
  'pomodoro.fase.trabajo': 'Traballo',
  'pomodoro.fase.descansoCorto': 'Descanso curto',
  'pomodoro.fase.descansoLargo': 'Descanso longo',
  'pomodoro.ciclo': 'Ciclo {actual} de {total}',
  'pomodoro.iniciar': 'Iniciar',
  'pomodoro.pausar': 'Pausar',
  'pomodoro.reiniciar': 'Reiniciar',
  'pomodoro.tareaAsociada.etiqueta': 'Tarefa asociada (opcional)',
  'pomodoro.tareaAsociada.ninguna': 'Ningunha',
  'pomodoro.historial.titulo': 'Historial recente',
  'pomodoro.historial.vacio': 'Aínda non completaches ningunha sesión.',
  'pomodoro.historial.minutos': '{minutos} min',
  'kanban.titulo': 'Taboleiro Kanban',
  'kanban.columna.porHacer': 'Por facer',
  'kanban.columna.enProceso': 'En proceso',
  'kanban.columna.hecha': 'Feita',
  'kanban.mover.anterior': 'Mover á columna anterior',
  'kanban.mover.siguiente': 'Mover á columna seguinte',
  'eisenhower.titulo': 'Matriz de Eisenhower',
  'eisenhower.cuadrante.hacer': 'Facer xa',
  'eisenhower.cuadrante.planificar': 'Planificar',
  'eisenhower.cuadrante.delegar': 'Delegar',
  'eisenhower.cuadrante.eliminar': 'Eliminar',
  'eisenhower.marcar.urgente': 'Urxente',
  'eisenhower.marcar.importante': 'Importante',
  'eisenhower.autoUrgente': 'Urxente pola data',
  'captura.placeholder': 'Que tes na mente?',
  'captura.boton': 'Capturar',
  'estadisticas.titulo': 'Estatísticas',
  'estadisticas.progresoGlobal': 'Progreso global',
  'estadisticas.distribucion.titulo': 'Distribución de tarefas',
  'estadisticas.objetivos.titulo': 'Progreso por obxectivo',
  'estadisticas.pareto.titulo': 'Tarefas de alto impacto (Pareto 80/20)',
  'estadisticas.pareto.leyendaAltoImpacto': 'Alto impacto',
  'estadisticas.pareto.descripcion':
    '{marcadas} de {total} tarefas están marcadas coma de alto impacto ({porcentaje}%).',
  'estadisticas.pareto.vacio':
    'Aínda non marcaches ningunha tarefa como de alto impacto. Márcaas con ★ desde o taboleiro Kanban.',
  'pareto.marcar': 'Marcar como alto impacto',
  'estadisticas.pomodoro.titulo': 'Pomodoro',
  'estadisticas.pomodoro.hoy': 'Completados hoxe',
  'estadisticas.pomodoro.semana': 'Completados esta semana',
  'estadisticas.pomodoro.minutosSemana': 'Minutos de traballo esta semana',
  'estadisticas.pomodoro.vacio': 'Aínda non completaches ningunha sesión de traballo.',
  'estadisticas.racha': '{racha, plural, one {Racha: # día seguido} other {Racha: # días seguidos}}',
  'estadisticas.racha.vacia': 'Aínda non tes unha racha activa. Comeza hoxe!',
  'tema.activarOscuro': 'Activar modo escuro',
  'tema.activarClaro': 'Activar modo claro',
  'revision.titulo': 'Revisión semanal',
  'revision.eslogan': 'Unha ollada semanal ao que avanzaches e ao que quedou atrás.',
  'revision.vencidas.titulo': 'Tarefas vencidas',
  'revision.vencidas.vacio': 'Non tes tarefas vencidas. Ben feito!',
  'revision.completadas.titulo': 'Completadas esta semana',
  'revision.completadas.vacio': 'Non completaches ningunha tarefa esta semana.',
  'revision.objetivosSinTocar.titulo': 'Obxectivos sen tocar',
  'revision.objetivosSinTocar.vacio': 'Todos os teus obxectivos teñen movemento recente.',
  'revision.objetivosSinTocar.diasInactivo':
    '{dias, plural, one {Sen cambios desde hai # día} other {Sen cambios desde hai # días}}',
  'revision.sueltas.titulo': 'Tarefas soltas por organizar',
  'revision.sueltas.vacio': 'Todo organizado! Non tes tarefas soltas pendentes.',
  'revision.sueltas.organizar': 'Organizar en Obxectivos',
  'estadisticas.actividad.titulo': 'Actividade diaria',
  'estadisticas.actividad.tooltip': '{cantidad, plural, =0 {Sen pomodoros} one {# pomodoro} other {# pomodoros}}',
  'estadisticas.actividad.menos': 'Menos',
  'estadisticas.actividad.mas': 'Máis',
  'estadisticas.tiempoComparado.titulo': 'Tempo estimado vs. real',
  'estadisticas.tiempoComparado.vacio':
    'Pon un tempo estimado nunha tarefa (desde o seu detalle) e rexístralle sesións de Pomodoro para vela comparada aquí.',
  'estadisticas.tiempoComparado.estimado': 'Estimado: {minutos} min',
  'estadisticas.tiempoComparado.real': 'Real: {minutos} min',
  'estadisticas.exportar.csv': 'Exportar CSV',
  'estadisticas.exportar.pdf': 'Imprimir / PDF',
  'agenda.titulo': 'Axenda',
  'agenda.filtro.dia': 'Día',
  'agenda.filtro.semana': 'Semana',
  'agenda.filtro.mes': 'Mes',
  'agenda.anterior': 'Anterior',
  'agenda.siguiente': 'Seguinte',
  'agenda.hoy': 'Hoxe',
  'agenda.sinHora': 'Todo o día',
  'agenda.sinTareas': 'Non hai tarefas neste período.',
  'agenda.masTareas': '+{cantidad} máis',
  'ajustes.titulo': 'Axustes',
  'ajustes.google.titulo': 'Google Calendar',
  'ajustes.google.descripcion':
    'Sincroniza as túas tarefas con data límite e as túas sesións de Pomodoro completadas co teu Google Calendar, nos dous sentidos.',
  'ajustes.google.conectar': 'Conectar con Google',
  'ajustes.google.desconectar': 'Desconectar',
  'ajustes.google.conectado': 'Conta conectada',
  'ajustes.google.noConectado': 'Non conectado',
  'ajustes.google.ultimaSincronizacion': 'Última sincronización: {fecha}',
  'ajustes.google.nunca': 'nunca',
  'ajustes.google.sincronizarAhora': 'Sincronizar agora',
  'ajustes.google.sincronizando': 'Sincronizando…',
  'ajustes.google.autoSyncInfo':
    'Mentres esta pestana estea aberta e conectada, a sincronización tamén se repetirá automaticamente cada poucos minutos.',
  'ajustes.google.resumen':
    '{creados} creados, {actualizados} actualizados, {eliminados} eliminados, {importados} importados desde Google.',
  'ajustes.google.conectadoOk': 'Conta de Google conectada correctamente.',
  'ajustes.google.errorConexion': 'Non se puido completar a conexión con Google.',
  'ajustes.google.noConfigurado':
    'A sincronización con Google Calendar aínda non está configurada no servidor.',
  'ajustes.google.errores':
    '{cantidad, plural, one {# evento non se puido sincronizar con Google Calendar.} other {# eventos non se puideron sincronizar con Google Calendar.}}',
  'nav.principal': 'Navegación principal',
  'nav.abrirMenu': 'Abrir o menú',
  'nav.cerrarMenu': 'Pechar o menú',
  'nav.seccion.planificar': 'Planificar',
  'nav.seccion.concentrarse': 'Concentrarse',
  'nav.seccion.revisar': 'Revisar',
  'nav.inicio': 'Inicio',
  'nav.objetivos': 'Obxectivos',
  'nav.agenda': 'Axenda',
  'nav.kanban': 'Kanban',
  'nav.eisenhower': 'Eisenhower',
  'nav.pomodoro': 'Pomodoro',
  'nav.revision': 'Revisión semanal',
  'nav.estadisticas': 'Estatísticas',
  'nav.ajustes': 'Axustes',
  'consentimiento.pendiente.titulo': 'A túa conta está pendente de confirmación',
  'consentimiento.pendiente.explicacion': 'Como es menor de idade, enviamos un correo ao teu pai, nai ou titor legal para que confirme que podes usar FocusFlow. En canto o confirme, poderás comezar.',
  'consentimiento.pendiente.comprobar': 'Xa o confirmou',
  'consentimiento.pendiente.reenviar': 'Reenviar o correo',
  'consentimiento.pendiente.reenviado': 'Correo reenviado. Pídelle ao teu titor que revise a caixa de entrada.',
  'consentimiento.pendiente.errorReenvio': 'Non se puido reenviar o correo',
  'consentimiento.confirmar.titulo': 'Confirmación do consentimento',
  'consentimiento.confirmar.confirmando': 'Confirmando…',
  'consentimiento.confirmar.exito': 'Grazas! A conta xa está confirmada e pódese usar FocusFlow con normalidade.',
  'consentimiento.confirmar.error': 'Non se puido confirmar a conta',
  'consentimiento.confirmar.sinToken': 'A ligazón non é válida: falta o código de confirmación.',
  'nav.planificador': 'Planificador escolar',
  'tarea.detalle.tipoEscolar': 'Tipo',
  'tipoEscolar.ninguno': 'Sen tipo',
  'tipoEscolar.examen': 'Exame',
  'tipoEscolar.examen.plural': 'Exames',
  'tipoEscolar.trabajo': 'Traballo',
  'tipoEscolar.trabajo.plural': 'Traballos',
  'tipoEscolar.presentacion': 'Presentación',
  'tipoEscolar.presentacion.plural': 'Presentacións',
  'planificador.titulo': 'Planificador escolar',
  'planificador.descripcion': 'Os teus próximos exames, traballos e presentacións, ordenados por data.',
  'planificador.nueva.titulo': 'Engadir exame ou entrega',
  'planificador.nueva.tituloPlaceholder': 'p. ex. Exame do tema 3',
  'planificador.nueva.asignatura': 'Materia (opcional)',
  'planificador.nueva.boton': 'Engadir ao planificador',
  'planificador.filtro': 'Filtrar por tipo',
  'planificador.filtro.todos': 'Todo',
  'planificador.seccion.vencidas': 'Vencidas ({cantidad})',
  'planificador.seccion.estaSemana': 'Próximos 7 días ({cantidad})',
  'planificador.seccion.masAdelante': 'Máis adiante ({cantidad})',
  'planificador.seccion.sinFecha': 'Sen data ({cantidad})',
  'planificador.seccion.vacia': 'Nada por aquí.',
  'planificador.vacio': 'Non tes exames, traballos nin presentacións pendentes. Engade o primeiro!',
  'planificador.marcarHecha': 'Marcar «{titulo}» como feito',
};
