export const gl = {
  'app.titulo': 'FocusFlow',
  'app.eslogan': 'Organiza os teus obxectivos, enfoca o teu tempo.',
  'bienvenida.mensaje': 'Benvido a FocusFlow!',
  'selector.idioma.etiqueta': 'Idioma',
  'auth.registro.titulo': 'Crear conta',
  'auth.registro.nombre': 'Nome',
  'auth.registro.correo': 'Correo electrónico',
  'auth.registro.contrasena': 'Contrasinal',
  'auth.registro.boton': 'Rexistrarme',
  'auth.registro.enlaceLogin': 'Xa tes conta? Inicia sesión',
  'auth.login.titulo': 'Iniciar sesión',
  'auth.login.correo': 'Correo electrónico',
  'auth.login.contrasena': 'Contrasinal',
  'auth.login.boton': 'Entrar',
  'auth.login.enlaceRegistro': 'Non tes conta? Rexístrate',
  'auth.cerrarSesion': 'Pechar sesión',
  'auth.bienvenidoUsuario': 'Ola, {nombre}',
  'inicio.irAObjetivos': 'Ver os meus obxectivos',
  'objetivos.titulo': 'Os meus obxectivos',
  'objetivos.nuevo.tituloPlaceholder': 'Título do obxectivo',
  'objetivos.nuevo.descripcionPlaceholder': 'Descrición (opcional)',
  'objetivos.nuevo.boton': 'Crear obxectivo',
  'objetivos.vacio': 'Aínda non tes obxectivos. Crea o primeiro!',
  'objetivos.eliminar': 'Eliminar obxectivo',
  'objetivos.progreso': '{completadas} de {total} tarefas',
  'tareas.tituloPlaceholder': 'Nova tarefa',
  'tareas.anadir': 'Engadir',
  'tareas.sueltas.titulo': 'Tarefas soltas',
  'tareas.eliminar': 'Eliminar tarefa',
  'tareas.marcarCompletada': 'Marcar "{titulo}" como completada',
  'inicio.irAPomodoro': 'Temporizador Pomodoro',
  'pomodoro.fase.trabajo': 'Traballo',
  'pomodoro.fase.descansoCorto': 'Descanso curto',
  'pomodoro.fase.descansoLargo': 'Descanso longo',
  'pomodoro.ciclo': 'Ciclo {actual} de {total}',
  'pomodoro.iniciar': 'Iniciar',
  'pomodoro.pausar': 'Pausar',
  'pomodoro.reiniciar': 'Reiniciar',
  'pomodoro.tareaAsociada.etiqueta': 'Tarefa asociada (opcional)',
  'pomodoro.tareaAsociada.ninguna': 'Ningunha',
  'pomodoro.historial.titulo': 'Historial recente',
  'pomodoro.historial.vacio': 'Aínda non completaches ningunha sesión.',
  'pomodoro.historial.minutos': '{minutos} min',
  'inicio.irAKanban': 'Taboleiro Kanban',
  'kanban.titulo': 'Taboleiro Kanban',
  'kanban.columna.porHacer': 'Por facer',
  'kanban.columna.enProceso': 'En proceso',
  'kanban.columna.hecha': 'Feita',
  'kanban.mover.anterior': 'Mover á columna anterior',
  'kanban.mover.siguiente': 'Mover á columna seguinte',
  'inicio.irAEisenhower': 'Matriz de Eisenhower',
  'eisenhower.titulo': 'Matriz de Eisenhower',
  'eisenhower.cuadrante.hacer': 'Facer xa',
  'eisenhower.cuadrante.planificar': 'Planificar',
  'eisenhower.cuadrante.delegar': 'Delegar',
  'eisenhower.cuadrante.eliminar': 'Eliminar',
  'eisenhower.marcar.urgente': 'Urxente',
  'eisenhower.marcar.importante': 'Importante',
  'captura.placeholder': 'Que tes na mente?',
  'captura.boton': 'Capturar',
  'inicio.irAEstadisticas': 'Estatísticas',
  'estadisticas.titulo': 'Estatísticas',
  'estadisticas.progresoGlobal': 'Progreso global',
  'estadisticas.distribucion.titulo': 'Distribución de tarefas',
  'estadisticas.objetivos.titulo': 'Progreso por obxectivo',
  'estadisticas.pareto.titulo': 'Tarefas de alto impacto (Pareto 80/20)',
  'estadisticas.pareto.leyendaAltoImpacto': 'Alto impacto',
  'estadisticas.pareto.descripcion':
    '{marcadas} de {total} tarefas están marcadas coma de alto impacto ({porcentaje}%).',
  'estadisticas.pareto.vacio':
    'Aínda non marcaches ningunha tarefa como de alto impacto. Márcaas con ★ desde o taboleiro Kanban.',
  'pareto.marcar': 'Marcar como alto impacto',
  'estadisticas.pomodoro.titulo': 'Pomodoro',
  'estadisticas.pomodoro.hoy': 'Completados hoxe',
  'estadisticas.pomodoro.semana': 'Completados esta semana',
  'estadisticas.pomodoro.minutosSemana': 'Minutos de traballo esta semana',
  'estadisticas.pomodoro.vacio': 'Aínda non completaches ningunha sesión de traballo.',
  'tema.activarOscuro': 'Activar modo escuro',
  'tema.activarClaro': 'Activar modo claro',
};
