export const va = {
  'app.titulo': 'FocusFlow',
  'app.eslogan': 'Organitza els teus objectius, enfoca el teu temps.',
  'bienvenida.mensaje': 'Benvingut a FocusFlow!',
  'selector.idioma.etiqueta': 'Idioma',
  'auth.registro.titulo': 'Crear compte',
  'auth.registro.nombre': 'Nom',
  'auth.registro.correo': 'Correu electrònic',
  'auth.registro.contrasena': 'Contrasenya',
  'auth.registro.fechaNacimiento': 'Data de naixement',
  'auth.registro.correoTutor': 'Correu del pare, la mare o el tutor legal',
  'auth.registro.correoTutorAyuda':
    'En ser menor d\'edat, necessitem que el teu tutor confirme l\'ús d\'este compte.',
  'auth.registro.boton': 'Registrar-me',
  'auth.registro.enlaceLogin': 'Ja tens compte? Inicia sessió',
  'auth.login.titulo': 'Iniciar sessió',
  'auth.login.correo': 'Correu electrònic',
  'auth.login.contrasena': 'Contrasenya',
  'auth.login.boton': 'Entrar',
  'auth.login.enlaceRegistro': 'No tens compte? Registra\'t',
  'auth.cerrarSesion': 'Tancar sessió',
  'auth.bienvenidoUsuario': 'Hola, {nombre}',
  'objetivos.titulo': 'Els meus objectius',
  'objetivos.nuevo.tituloPlaceholder': 'Títol de l\'objectiu',
  'objetivos.nuevo.descripcionPlaceholder': 'Descripció (opcional)',
  'objetivos.nuevo.boton': 'Crear objectiu',
  'objetivos.vacio': 'Encara no tens objectius. Crea el primer!',
  'objetivos.eliminar': 'Eliminar objectiu',
  'objetivos.progreso': '{completadas} de {total} tasques',
  'fechaLimite.etiqueta': 'Data límit (opcional)',
  'inicio.proximos.titulo': 'Pròxims 7 dies',
  'inicio.proximos.vacio': 'No tens tasques amb data límit en els pròxims 7 dies.',
  'tareas.tituloPlaceholder': 'Nova tasca',
  'tareas.anadir': 'Afegir',
  'tareas.sueltas.titulo': 'Tasques soltes',
  'tareas.eliminar': 'Eliminar tasca',
  'tareas.marcarCompletada': 'Marcar "{titulo}" com a completada',
  'tarea.detalle.descripcion': 'Notes',
  'tarea.detalle.recurrencia': 'Repetir',
  'tarea.recurrencia.ninguna': 'No es repeteix',
  'tarea.recurrencia.diaria': 'Cada dia',
  'tarea.recurrencia.semanal': 'Cada setmana',
  'tarea.detalle.ambito': 'Àmbit',
  'ambito.selector': 'Àmbit',
  'ambito.todos': 'Tot',
  'ambito.personal': 'Personal',
  'ambito.escolar': 'Escolar',
  'tarea.detalle.etiquetas': 'Etiquetes',
  'tarea.detalle.nuevaEtiqueta': 'Nova etiqueta',
  'tarea.detalle.quitarEtiqueta': 'Llevar l\'etiqueta {nombre}',
  'tarea.detalle.subtareas': 'Subtasques ({completadas} de {total})',
  'tarea.detalle.nuevaSubtarea': 'Nou pas',
  'tarea.detalle.tiempoEstimado': 'Temps estimat (minuts)',
  'tarea.detalle.tiempoEstimadoPlaceholder': 'p. ex. 30',
  'tarea.detalle.tiempoReal': 'Temps real: {minutos} min',
  'tarea.detalle.fechaLimite': 'Data límit',
  'tarea.detalle.horaInicio': "Hora d'inici",
  'tarea.detalle.duracion': 'Duració (minuts)',
  'pomodoro.fase.trabajo': 'Treball',
  'pomodoro.fase.descansoCorto': 'Descans curt',
  'pomodoro.fase.descansoLargo': 'Descans llarg',
  'pomodoro.ciclo': 'Cicle {actual} de {total}',
  'pomodoro.iniciar': 'Iniciar',
  'pomodoro.pausar': 'Pausar',
  'pomodoro.reiniciar': 'Reiniciar',
  'pomodoro.tareaAsociada.etiqueta': 'Tasca associada (opcional)',
  'pomodoro.tareaAsociada.ninguna': 'Cap',
  'pomodoro.historial.titulo': 'Historial recent',
  'pomodoro.historial.vacio': 'Encara no has completat cap sessió.',
  'pomodoro.historial.minutos': '{minutos} min',
  'kanban.titulo': 'Tauler Kanban',
  'kanban.columna.porHacer': 'Per fer',
  'kanban.columna.enProceso': 'En procés',
  'kanban.columna.hecha': 'Feta',
  'kanban.mover.anterior': 'Moure a la columna anterior',
  'kanban.mover.siguiente': 'Moure a la columna següent',
  'eisenhower.titulo': 'Matriu d\'Eisenhower',
  'eisenhower.cuadrante.hacer': 'Fer ja',
  'eisenhower.cuadrante.planificar': 'Planificar',
  'eisenhower.cuadrante.delegar': 'Delegar',
  'eisenhower.cuadrante.eliminar': 'Eliminar',
  'eisenhower.marcar.urgente': 'Urgent',
  'eisenhower.marcar.importante': 'Important',
  'eisenhower.autoUrgente': 'Urgent per data',
  'captura.placeholder': 'Què tens en ment?',
  'captura.boton': 'Capturar',
  'estadisticas.titulo': 'Estadístiques',
  'estadisticas.progresoGlobal': 'Progrés global',
  'estadisticas.distribucion.titulo': 'Distribució de tasques',
  'estadisticas.objetivos.titulo': 'Progrés per objectiu',
  'estadisticas.pareto.titulo': 'Tasques d\'alt impacte (Pareto 80/20)',
  'estadisticas.pareto.leyendaAltoImpacto': 'Alt impacte',
  'estadisticas.pareto.descripcion':
    '{marcadas} de {total} tasques estan marcades com d\'alt impacte ({porcentaje}%).',
  'estadisticas.pareto.vacio':
    'Encara no has marcat cap tasca com d\'alt impacte. Marca-les amb ★ des del tauler Kanban.',
  'pareto.marcar': 'Marcar com d\'alt impacte',
  'estadisticas.pomodoro.titulo': 'Pomodoro',
  'estadisticas.pomodoro.hoy': 'Completats hui',
  'estadisticas.pomodoro.semana': 'Completats esta setmana',
  'estadisticas.pomodoro.minutosSemana': 'Minuts de treball esta setmana',
  'estadisticas.pomodoro.vacio': 'Encara no has completat cap sessió de treball.',
  'estadisticas.racha': '{racha, plural, one {Ratxa: # dia seguit} other {Ratxa: # dies seguits}}',
  'estadisticas.racha.vacia': 'Encara no tens una ratxa activa. Comença hui!',
  'tema.activarOscuro': 'Activar mode fosc',
  'tema.activarClaro': 'Activar mode clar',
  'revision.titulo': 'Revisió setmanal',
  'revision.eslogan': 'Un colp d\'ull setmanal al que has avançat i al que s\'ha quedat arrere.',
  'revision.vencidas.titulo': 'Tasques vençudes',
  'revision.vencidas.vacio': 'No tens tasques vençudes. Molt bé!',
  'revision.completadas.titulo': 'Completades esta setmana',
  'revision.completadas.vacio': 'No has completat cap tasca esta setmana.',
  'revision.objetivosSinTocar.titulo': 'Objectius sense tocar',
  'revision.objetivosSinTocar.vacio': 'Tots els teus objectius tenen moviment recent.',
  'revision.objetivosSinTocar.diasInactivo':
    '{dias, plural, one {Sense canvis des de fa # dia} other {Sense canvis des de fa # dies}}',
  'revision.sueltas.titulo': 'Tasques soltes per organitzar',
  'revision.sueltas.vacio': 'Tot organitzat! No tens tasques soltes pendents.',
  'revision.sueltas.organizar': 'Organitzar en Objectius',
  'estadisticas.actividad.titulo': 'Activitat diària',
  'estadisticas.actividad.tooltip': '{cantidad, plural, =0 {Sense pomodoros} one {# pomodoro} other {# pomodoros}}',
  'estadisticas.actividad.menos': 'Menys',
  'estadisticas.actividad.mas': 'Més',
  'estadisticas.tiempoComparado.titulo': 'Temps estimat vs. real',
  'estadisticas.tiempoComparado.vacio':
    'Posa un temps estimat en una tasca (des del seu detall) i registra-li sessions de Pomodoro per a veure-la comparada ací.',
  'estadisticas.tiempoComparado.estimado': 'Estimat: {minutos} min',
  'estadisticas.tiempoComparado.real': 'Real: {minutos} min',
  'estadisticas.exportar.csv': 'Exportar CSV',
  'estadisticas.exportar.pdf': 'Imprimir / PDF',
  'agenda.titulo': 'Agenda',
  'agenda.filtro.dia': 'Dia',
  'agenda.filtro.semana': 'Setmana',
  'agenda.filtro.mes': 'Mes',
  'agenda.anterior': 'Anterior',
  'agenda.siguiente': 'Següent',
  'agenda.hoy': 'Hui',
  'agenda.sinHora': 'Tot el dia',
  'agenda.sinTareas': 'No hi ha tasques en este període.',
  'agenda.masTareas': '+{cantidad} més',
  'ajustes.titulo': 'Ajustos',
  'ajustes.google.titulo': 'Google Calendar',
  'ajustes.google.descripcion':
    'Sincronitza les teues tasques amb data límit i les teues sessions de Pomodoro completades amb el teu Google Calendar, en ambdós sentits.',
  'ajustes.google.conectar': 'Connectar amb Google',
  'ajustes.google.desconectar': 'Desconnectar',
  'ajustes.google.conectado': 'Compte connectat',
  'ajustes.google.noConectado': 'No connectat',
  'ajustes.google.ultimaSincronizacion': 'Última sincronització: {fecha}',
  'ajustes.google.nunca': 'mai',
  'ajustes.google.sincronizarAhora': 'Sincronitzar ara',
  'ajustes.google.sincronizando': 'Sincronitzant…',
  'ajustes.google.autoSyncInfo':
    'Mentre esta pestanya estiga oberta i connectada, la sincronització també es repetirà automàticament cada pocs minuts.',
  'ajustes.google.resumen':
    '{creados} creats, {actualizados} actualitzats, {eliminados} eliminats, {importados} importats des de Google.',
  'ajustes.google.conectadoOk': 'Compte de Google connectat correctament.',
  'ajustes.google.errorConexion': 'No s\'ha pogut completar la connexió amb Google.',
  'ajustes.google.noConfigurado':
    'La sincronització amb Google Calendar encara no està configurada en el servidor.',
  'ajustes.google.errores':
    '{cantidad, plural, one {# esdeveniment no s\'ha pogut sincronitzar amb Google Calendar.} other {# esdeveniments no s\'han pogut sincronitzar amb Google Calendar.}}',
  'nav.principal': 'Navegació principal',
  'nav.abrirMenu': 'Obrir el menú',
  'nav.cerrarMenu': 'Tancar el menú',
  'nav.seccion.planificar': 'Planificar',
  'nav.seccion.concentrarse': 'Concentrar-se',
  'nav.seccion.revisar': 'Revisar',
  'nav.inicio': 'Inici',
  'nav.objetivos': 'Objectius',
  'nav.agenda': 'Agenda',
  'nav.kanban': 'Kanban',
  'nav.eisenhower': 'Eisenhower',
  'nav.pomodoro': 'Pomodoro',
  'nav.revision': 'Revisió setmanal',
  'nav.estadisticas': 'Estadístiques',
  'nav.ajustes': 'Configuració',
  'consentimiento.pendiente.titulo': 'El teu compte està pendent de confirmació',
  'consentimiento.pendiente.explicacion': 'Com que eres menor d’edat, hem enviat un correu al teu pare, mare o tutor legal perquè confirme que pots utilitzar FocusFlow. Tan prompte com ho confirme, podràs començar.',
  'consentimiento.pendiente.comprobar': 'Ja ho ha confirmat',
  'consentimiento.pendiente.reenviar': 'Tornar a enviar el correu',
  'consentimiento.pendiente.reenviado': 'Correu reenviat. Demana al teu tutor que revise la safata d’entrada.',
  'consentimiento.pendiente.errorReenvio': 'No s’ha pogut tornar a enviar el correu',
  'consentimiento.confirmar.titulo': 'Confirmació del consentiment',
  'consentimiento.confirmar.confirmando': 'Confirmant…',
  'consentimiento.confirmar.exito': 'Gràcies! El compte ja està confirmat i es pot utilitzar FocusFlow amb normalitat.',
  'consentimiento.confirmar.error': 'No s’ha pogut confirmar el compte',
  'consentimiento.confirmar.sinToken': 'L’enllaç no és vàlid: falta el codi de confirmació.',
  'nav.planificador': 'Planificador escolar',
  'tarea.detalle.tipoEscolar': 'Tipus',
  'tipoEscolar.ninguno': 'Sense tipus',
  'tipoEscolar.examen': 'Examen',
  'tipoEscolar.examen.plural': 'Exàmens',
  'tipoEscolar.trabajo': 'Treball',
  'tipoEscolar.trabajo.plural': 'Treballs',
  'tipoEscolar.presentacion': 'Presentació',
  'tipoEscolar.presentacion.plural': 'Presentacions',
  'planificador.titulo': 'Planificador escolar',
  'planificador.descripcion': 'Els teus pròxims exàmens, treballs i presentacions, ordenats per data.',
  'planificador.nueva.titulo': 'Afegir examen o lliurament',
  'planificador.nueva.tituloPlaceholder': 'p. ex. Examen del tema 3',
  'planificador.nueva.asignatura': 'Assignatura (opcional)',
  'planificador.nueva.boton': 'Afegir al planificador',
  'planificador.filtro': 'Filtrar per tipus',
  'planificador.filtro.todos': 'Tot',
  'planificador.seccion.vencidas': 'Vençudes ({cantidad})',
  'planificador.seccion.estaSemana': 'Pròxims 7 dies ({cantidad})',
  'planificador.seccion.masAdelante': 'Més avant ({cantidad})',
  'planificador.seccion.sinFecha': 'Sense data ({cantidad})',
  'planificador.seccion.vacia': 'Res per ací.',
  'planificador.vacio': 'No tens exàmens, treballs ni presentacions pendents. Afig el primer!',
  'planificador.marcarHecha': 'Marcar «{titulo}» com a fet',
  'ajustes.modoEscolar.titulo': 'Mode escolar',
  'ajustes.modoEscolar.descripcion':
    'Afig el selector d’àmbit (Personal/Escolar) i el planificador d’exàmens, treballs i presentacions, per a separar la vida escolar de la resta. Si el desactives no s’esborra res: simplement tornes a veure totes les tasques juntes.',
  'ajustes.modoEscolar.activar': 'Activar el mode escolar',
};
