export const va = {
  'app.titulo': 'FocusFlow',
  'app.eslogan': 'Organitza els teus objectius, enfoca el teu temps.',
  'bienvenida.mensaje': 'Benvingut a FocusFlow!',
  'selector.idioma.etiqueta': 'Idioma',
  'auth.registro.titulo': 'Crear compte',
  'auth.registro.nombre': 'Nom',
  'auth.registro.correo': 'Correu electrònic',
  'auth.registro.contrasena': 'Contrasenya',
  'auth.registro.boton': 'Registrar-me',
  'auth.registro.enlaceLogin': 'Ja tens compte? Inicia sessió',
  'auth.login.titulo': 'Iniciar sessió',
  'auth.login.correo': 'Correu electrònic',
  'auth.login.contrasena': 'Contrasenya',
  'auth.login.boton': 'Entrar',
  'auth.login.enlaceRegistro': 'No tens compte? Registra\'t',
  'auth.cerrarSesion': 'Tancar sessió',
  'auth.bienvenidoUsuario': 'Hola, {nombre}',
  'inicio.irAObjetivos': 'Veure els meus objectius',
  'objetivos.titulo': 'Els meus objectius',
  'objetivos.nuevo.tituloPlaceholder': 'Títol de l\'objectiu',
  'objetivos.nuevo.descripcionPlaceholder': 'Descripció (opcional)',
  'objetivos.nuevo.boton': 'Crear objectiu',
  'objetivos.vacio': 'Encara no tens objectius. Crea el primer!',
  'objetivos.eliminar': 'Eliminar objectiu',
  'objetivos.progreso': '{completadas} de {total} tasques',
  'tareas.tituloPlaceholder': 'Nova tasca',
  'tareas.anadir': 'Afegir',
  'tareas.sueltas.titulo': 'Tasques soltes',
  'tareas.eliminar': 'Eliminar tasca',
  'inicio.irAPomodoro': 'Temporitzador Pomodoro',
  'pomodoro.fase.trabajo': 'Treball',
  'pomodoro.fase.descansoCorto': 'Descans curt',
  'pomodoro.fase.descansoLargo': 'Descans llarg',
  'pomodoro.ciclo': 'Cicle {actual} de {total}',
  'pomodoro.iniciar': 'Iniciar',
  'pomodoro.pausar': 'Pausar',
  'pomodoro.reiniciar': 'Reiniciar',
};
